// Iron Sharpens Iron v2.2.0 — 30 Facts About Christians Config (en/es/fr)
window.PLAN = {
  title: "30 Facts About Christians",
  title_es: "30 Verdades sobre los cristianos",
  title_fr: "30 vérités sur les chrétiens",
  subtitle: "30 FACTS ABOUT CHRISTIANS — 30-DAY CHALLENGE",
  subtitle_es: "30 VERDADES SOBRE LOS CRISTIANOS — RETO DE 30 DÍAS",
  subtitle_fr: "30 VÉRITÉS SUR LES CHRÉTIENS — DÉFI DE 30 JOURS",
  storageKey: "isi-june-v1",
  startDate: "2026-06-01",
  totalDays: 30,
  days: [
{day:1,reading:"2 Corinthians 5:21",topic:"Righteous",topic_es:"Justo",topic_fr:"Juste",ph:1,
  summary:"For our sake he made him to be sin who knew no sin, so that in him we might become the righteousness of God.",
  summary_es:"Al que no conoció pecado, por nosotros lo hizo pecado, para que nosotros fuésemos hechos justicia de Dios en él.",
  summary_fr:"Celui qui n’a point connu le péché, il l’a fait devenir péché pour nous, afin que nous devenions en lui justice de Dieu."},
{day:2,reading:"Romans 8:1–2",topic:"Not Condemned",topic_es:"Sin condenación",topic_fr:"Non condamné",
  summary:"There is therefore now no condemnation for those who are in Christ Jesus.",
  summary_es:"Ahora, pues, ninguna condenación hay para los que están en Cristo Jesús, los que no andan conforme a la carne, sino conforme al Espíritu.",
  summary_fr:"Il n’y a donc maintenant aucune condamnation pour ceux qui sont en Jésus-Christ."},
{day:3,reading:"Romans 8:35–39",topic:"Loved",topic_es:"Amado",topic_fr:"Aimé",
  summary:"Who shall separate us from the love of Christ? Shall tribulation, or distress, or persecution, or famine, or nakedness, or danger, or sword?",
  summary_es:"¿Quién nos separará del amor de Cristo? ¿Tribulación, o angustia, o persecución, o hambre, o desnudez, o peligro, o espada?",
  summary_fr:"Qui nous séparera de l’amour de Christ ? Sera-ce la tribulation, ou l’angoisse, ou la persécution, ou la faim, ou la nudité, ou le péril, ou l’épée ?"},
{day:4,reading:"1 Corinthians 6:19–20",topic:"Indwelt by the Holy Spirit",topic_es:"Habitado por el Espíritu Santo",topic_fr:"Habité par le Saint-Esprit",
  summary:"Or do you not know that your body is a temple of the Holy Spirit within you, whom you have from God? You are not your own,",
  summary_es:"¿O ignoráis que vuestro cuerpo es templo del Espíritu Santo, el cual está en vosotros, el cual tenéis de Dios, y que no sois vuestros?",
  summary_fr:"Ne savez-vous pas que votre corps est le temple du Saint-Esprit qui est en vous, que vous avez reçu de Dieu, et que vous ne vous appartenez point à vous-mêmes ?"},
{day:5,reading:"Colossians 2:13",topic:"Forgiven",topic_es:"Perdonado",topic_fr:"Pardonné",
  summary:"And you, who were dead in your trespasses and the uncircumcision of your flesh, God made alive together with him, having forgiven us all our trespasses,",
  summary_es:"Y a vosotros, estando muertos en pecados y en la incircuncisión de vuestra carne, os dio vida juntamente con él, perdonándoos todos los pecados,",
  summary_fr:"Vous qui étiez morts par vos offenses et par l’incirconcision de votre chair, il vous a rendus à la vie avec lui, en nous faisant grâce pour toutes nos offenses ;"},
{day:6,reading:"Romans 5:1",topic:"Justified",topic_es:"Justificado",topic_fr:"Justifié",
  summary:"Therefore, since we have been justified by faith, we have peace with God through our Lord Jesus Christ.",
  summary_es:"Justificados, pues, por la fe, tenemos paz para con Dios por medio de nuestro Señor Jesucristo;",
  summary_fr:"Étant donc justifiés par la foi, nous avons la paix avec Dieu par notre Seigneur Jésus-Christ,"},
{day:7,reading:"2 Corinthians 5:17",topic:"New Creation",topic_es:"Nueva criatura",topic_fr:"Nouvelle créature",
  summary:"Therefore, if anyone is in Christ, he is a new creation. The old has passed away; behold, the new has come.",
  summary_es:"De modo que si alguno está en Cristo, nueva criatura es; las cosas viejas pasaron; he aquí todas son hechas nuevas.",
  summary_fr:"Si quelqu’un est en Christ, il est une nouvelle créature. Les choses anciennes sont passées ; voici, toutes choses sont devenues nouvelles."},
{day:8,reading:"Philippians 4:7",topic:"Guarded by Peace",topic_es:"Guardado por la paz",topic_fr:"Gardé par la paix",ph:2,
  summary:"And the peace of God, which surpasses all understanding, will guard your hearts and your minds in Christ Jesus.",
  summary_es:"Y la paz de Dios, que sobrepasa todo entendimiento, guardará vuestros corazones y vuestros pensamientos en Cristo Jesús.",
  summary_fr:"Et la paix de Dieu, qui surpasse toute intelligence, gardera vos cœurs et vos pensées en Jésus-Christ."},
{day:9,reading:"Galatians 3:13",topic:"Redeemed",topic_es:"Redimido",topic_fr:"Racheté",
  summary:"Christ redeemed us from the curse of the law by becoming a curse for us — for it is written, ‘Cursed is everyone who is hanged on a tree’ —",
  summary_es:"Cristo nos redimió de la maldición de la ley, hecho por nosotros maldición (porque está escrito: Maldito todo el que es colgado en un madero),",
  summary_fr:"Christ nous a rachetés de la malédiction de la loi, étant devenu malédiction pour nous — car il est écrit : Maudit est quiconque est pendu au bois —"},
{day:10,reading:"Ephesians 1:3",topic:"Blessed",topic_es:"Bendecido",topic_fr:"Béni",
  summary:"Blessed be the God and Father of our Lord Jesus Christ, who has blessed us in Christ with every spiritual blessing in the heavenly places,",
  summary_es:"Bendito sea el Dios y Padre de nuestro Señor Jesucristo, que nos bendijo con toda bendición espiritual en los lugares celestiales en Cristo,",
  summary_fr:"Béni soit Dieu, le Père de notre Seigneur Jésus-Christ, qui nous a bénis de toutes sortes de bénédictions spirituelles dans les lieux célestes en Christ !"},
{day:11,reading:"Romans 8:35–39",topic:"Loved",topic_es:"Amado",topic_fr:"Aimé",
  summary:"Who shall separate us from the love of Christ? Shall tribulation, or distress, or persecution, or famine, or nakedness, or danger, or sword?",
  summary_es:"¿Quién nos separará del amor de Cristo? ¿Tribulación, o angustia, o persecución, o hambre, o desnudez, o peligro, o espada?",
  summary_fr:"Qui nous séparera de l’amour de Christ ? Sera-ce la tribulation, ou l’angoisse, ou la persécution, ou la faim, ou la nudité, ou le péril, ou l’épée ?"},
{day:12,reading:"Ephesians 1:3–6",topic:"Chosen",topic_es:"Escogido",topic_fr:"Choisi",
  summary:"Blessed be the God and Father of our Lord Jesus Christ, who has blessed us in Christ with every spiritual blessing in the heavenly places,",
  summary_es:"Bendito sea el Dios y Padre de nuestro Señor Jesucristo, que nos bendijo con toda bendición espiritual en los lugares celestiales en Cristo,",
  summary_fr:"Béni soit Dieu, le Père de notre Seigneur Jésus-Christ, qui nous a bénis de toutes sortes de bénédictions spirituelles dans les lieux célestes en Christ !"},
{day:13,reading:"Colossians 2:13",topic:"Alive",topic_es:"Vivo",topic_fr:"Vivant",
  summary:"And you, who were dead in your trespasses and the uncircumcision of your flesh, God made alive together with him, having forgiven us all our trespasses,",
  summary_es:"Y a vosotros, estando muertos en pecados y en la incircuncisión de vuestra carne, os dio vida juntamente con él, perdonándoos todos los pecados,",
  summary_fr:"Vous qui étiez morts par vos offenses et par l’incirconcision de votre chair, il vous a rendus à la vie avec lui, en nous faisant grâce pour toutes nos offenses ;"},
{day:14,reading:"John 1:12",topic:"Child of God",topic_es:"Hijo de Dios",topic_fr:"Enfant de Dieu",
  summary:"But to all who did receive him, who believed in his name, he gave the right to become children of God,",
  summary_es:"Mas a todos los que le recibieron, a los que creen en su nombre, les dio potestad de ser hechos hijos de Dios;",
  summary_fr:"Mais à tous ceux qui l’ont reçue, à ceux qui croient en son nom, elle a donné le pouvoir de devenir enfants de Dieu,"},
{day:15,reading:"Hebrews 4:16",topic:"Direct Access",topic_es:"Acceso directo",topic_fr:"Accès direct",ph:3,
  summary:"Let us then with confidence draw near to the throne of grace, that we may receive mercy and find grace to help in time of need.",
  summary_es:"Acerquémonos, pues, confiadamente al trono de la gracia, para alcanzar misericordia y hallar gracia para el oportuno socorro.",
  summary_fr:"Approchons-nous donc avec assurance du trône de la grâce, afin d’obtenir miséricorde et de trouver grâce, pour être secourus dans nos besoins."},
{day:16,reading:"Psalm 139:13–16",topic:"Precisely Made",topic_es:"Formado con precisión",topic_fr:"Formé avec précision",
  summary:"For you formed my inward parts; you knitted me together in my mother’s womb.",
  summary_es:"Porque tú formaste mis entrañas; tú me hiciste en el vientre de mi madre.",
  summary_fr:"C’est toi qui as formé mes reins, qui m’as tissé dans le sein de ma mère."},
{day:17,reading:"Hebrews 13:5–6",topic:"Protected",topic_es:"Protegido",topic_fr:"Protégé",
  summary:"Keep your life free from love of money, and be content with what you have, for he has said, ‘I will never leave you nor forsake you.’",
  summary_es:"Sean vuestras costumbres sin avaricia, contentos con lo que tenéis ahora; porque él dijo: No te desampararé, ni te dejaré;",
  summary_fr:"Ne vous livrez pas à l’amour de l’argent ; contentez-vous de ce que vous avez ; car Dieu lui-même a dit : Je ne te délaisserai point, et je ne t’abandonnerai point."},
{day:18,reading:"Psalm 139:7–12",topic:"Never Alone",topic_es:"Nunca solo",topic_fr:"Jamais seul",
  summary:"Where shall I go from your Spirit? Or where shall I flee from your presence?",
  summary_es:"¿A dónde me iré de tu Espíritu? ¿Y a dónde huiré de tu presencia?",
  summary_fr:"Où irais-je loin de ton esprit, où fuirais-je loin de ta face ?"},
{day:19,reading:"John 15:15",topic:"Friend of God",topic_es:"Amigo de Dios",topic_fr:"Ami de Dieu",
  summary:"No longer do I call you servants, for the servant does not know what his master is doing; but I have called you friends, for all that I have heard from my Father I have made known to you.",
  summary_es:"Ya no os llamaré siervos, porque el siervo no sabe lo que hace su señor; pero os he llamado amigos, porque todas las cosas que oí de mi Padre, os las he dado a conocer.",
  summary_fr:"Je ne vous appelle plus serviteurs, parce que le serviteur ne sait pas ce que fait son maître ; mais je vous ai appelés amis, parce que je vous ai fait connaître tout ce que j’ai appris de mon Père."},
{day:20,reading:"Galatians 3:28",topic:"Unified",topic_es:"Unidos",topic_fr:"Unifié",
  summary:"There is neither Jew nor Greek, there is neither slave nor free, there is no male and female, for you are all one in Christ Jesus.",
  summary_es:"Ya no hay judío ni griego; no hay esclavo ni libre; no hay varón ni mujer; porque todos vosotros sois uno en Cristo Jesús.",
  summary_fr:"Il n’y a plus ni Juif ni Grec, il n’y a plus ni esclave ni libre, il n’y a plus ni homme ni femme ; car tous vous êtes un en Jésus-Christ."},
{day:21,reading:"1 Corinthians 1:8",topic:"Blameless",topic_es:"Irreprensible",topic_fr:"Irréprochable",
  summary:"who will sustain you to the end, guiltless in the day of our Lord Jesus Christ.",
  summary_es:"el cual también os confirmará hasta el fin, para que seáis irreprensibles en el día de nuestro Señor Jesucristo.",
  summary_fr:"Il vous affermira aussi jusqu’à la fin, pour que vous soyez irréprochables au jour de notre Seigneur Jésus-Christ."},
{day:22,reading:"Philippians 4:19",topic:"All Needs Supplied",topic_es:"Todas las necesidades suplidas",topic_fr:"Tous les besoins comblés",ph:4,
  summary:"And my God will supply every need of yours according to his riches in glory in Christ Jesus.",
  summary_es:"Mi Dios, pues, suplirá todo lo que os falta conforme a sus riquezas en gloria en Cristo Jesús.",
  summary_fr:"Et mon Dieu pourvoira à tous vos besoins selon sa richesse, avec gloire, en Jésus-Christ."},
{day:23,reading:"Psalm 34:18",topic:"God Is Near",topic_es:"Dios está cerca",topic_fr:"Dieu est près",
  summary:"The Lord is near to the brokenhearted and saves the crushed in spirit.",
  summary_es:"Cercano está Jehová a los quebrantados de corazón; y salva a los contritos de espíritu.",
  summary_fr:"L’Éternel est près de ceux qui ont le cœur brisé, et il sauve ceux qui ont l’esprit dans l’abattement."},
{day:24,reading:"Colossians 3:1–4",topic:"Resurrection Guaranteed",topic_es:"Resurrección garantizada",topic_fr:"Résurrection garantie",
  summary:"If then you have been raised with Christ, seek the things that are above, where Christ is, seated at the right hand of God.",
  summary_es:"Si, pues, habéis resucitado con Cristo, buscad las cosas de arriba, donde está Cristo sentado a la diestra de Dios.",
  summary_fr:"Si donc vous êtes ressuscités avec Christ, cherchez les choses d’en haut, où Christ est assis à la droite de Dieu."},
{day:25,reading:"Romans 8:26",topic:"Prayers Are Heard",topic_es:"Las oraciones son oídas",topic_fr:"Les prières sont entendues",
  summary:"Likewise the Spirit helps us in our weakness. For we do not know what to pray for as we ought, but the Spirit himself intercedes for us with groanings too deep for words.",
  summary_es:"Y de igual manera el Espíritu nos ayuda en nuestra debilidad; pues qué hemos de pedir como conviene, no lo sabemos, pero el Espíritu mismo intercede por nosotros con gemidos indecibles.",
  summary_fr:"De même aussi l’Esprit nous aide dans notre faiblesse, car nous ne savons pas ce qu’il nous convient de demander dans nos prières. Mais l’Esprit lui-même intercède par des soupirs inexprimables ;"},
{day:26,reading:"Psalm 84:11",topic:"Blessed",topic_es:"Bendecido",topic_fr:"Béni",
  summary:"For the Lord God is a sun and shield; the Lord bestows favor and honor. No good thing does he withhold from those who walk uprightly.",
  summary_es:"Porque sol y escudo es Jehová Dios; gracia y gloria dará Jehová. No quitará el bien a los que andan en integridad.",
  summary_fr:"Car l’Éternel Dieu est un soleil et un bouclier, l’Éternel donne la grâce et la gloire, il ne refuse aucun bien à ceux qui marchent dans l’intégrité."},
{day:27,reading:"Hebrews 12:5–6",topic:"Disciplined When in Sin",topic_es:"Disciplinado en el pecado",topic_fr:"Discipliné dans le péché",
  summary:"And have you forgotten the exhortation that addresses you as sons? ‘My son, do not regard lightly the discipline of the Lord, nor be weary when reproved by him.’",
  summary_es:"y habéis ya olvidado la exhortación que como a hijos se os dirige, diciendo: Hijo mío, no menosprecies la disciplina del Señor, ni desmayes cuando eres reprendido por él;",
  summary_fr:"Et vous avez oublié l’exhortation qui vous est adressée comme à des fils : Mon fils, ne méprise pas le châtiment du Seigneur, et ne perds pas courage lorsqu’il te reprend ;"},
{day:28,reading:"1 Corinthians 6:9–11",topic:"Purified",topic_es:"Purificado",topic_fr:"Purifié",
  summary:"Or do you not know that the unrighteous will not inherit the kingdom of God? Do not be deceived: neither the sexually immoral, nor idolaters, nor adulterers, nor men who practice homosexuality,",
  summary_es:"¿No sabéis que los injustos no heredarán el reino de Dios? No erréis; ni los fornicarios, ni los idólatras, ni los adúlteros, ni los afeminados, ni los que se echan con varones,",
  summary_fr:"Ne savez-vous pas que les injustes n’hériteront point le royaume de Dieu ? Ne vous y trompez pas : ni les impudiques, ni les idolâtres, ni les adultères, ni les efféminés, ni les infâmes,"},
{day:29,reading:"Ephesians 2:10",topic:"God’s Workmanship",topic_es:"Hechura de Dios",topic_fr:"L’ouvrage de Dieu",
  summary:"For we are his workmanship, created in Christ Jesus for good works, which God prepared beforehand, that we should walk in them.",
  summary_es:"Porque somos hechura suya, creados en Cristo Jesús para buenas obras, las cuales Dios preparó de antemano para que anduviésemos en ellas.",
  summary_fr:"Car nous sommes son ouvrage, ayant été créés en Jésus-Christ pour de bonnes œuvres, que Dieu a préparées d’avance, afin que nous les pratiquions."},
{day:30,reading:"Philippians 3:20",topic:"Citizen of Heaven",topic_es:"Ciudadano del cielo",topic_fr:"Citoyen du ciel",
  summary:"But our citizenship is in heaven, and from it we await a Savior, the Lord Jesus Christ,",
  summary_es:"Mas nuestra ciudadanía está en los cielos, de donde también esperamos al Salvador, al Señor Jesucristo;",
  summary_fr:"Mais notre cité à nous est dans les cieux, d’où nous attendons aussi comme Sauveur le Seigneur Jésus-Christ,"}
],
  verses: {
1:{r:"2 Corinthians 5:21",r_es:"2 Corintios 5:21",r_fr:"2 Corinthiens 5:21",
  t:"For our sake he made him to be sin who knew no sin, so that in him we might become the righteousness of God.",
  t_es:"Al que no conoció pecado, por nosotros lo hizo pecado, para que nosotros fuésemos hechos justicia de Dios en él.",
  t_fr:"Celui qui n’a point connu le péché, il l’a fait devenir péché pour nous, afin que nous devenions en lui justice de Dieu."},
8:{r:"Philippians 4:7",r_es:"Filipenses 4:7",r_fr:"Philippiens 4:7",
  t:"And the peace of God, which surpasses all understanding, will guard your hearts and your minds in Christ Jesus.",
  t_es:"Y la paz de Dios, que sobrepasa todo entendimiento, guardará vuestros corazones y vuestros pensamientos en Cristo Jesús.",
  t_fr:"Et la paix de Dieu, qui surpasse toute intelligence, gardera vos cœurs et vos pensées en Jésus-Christ."},
15:{r:"Hebrews 4:16",r_es:"Hebreos 4:16",r_fr:"Hébreux 4:16",
  t:"Let us then with confidence draw near to the throne of grace, that we may receive mercy and find grace to help in time of need.",
  t_es:"Acerquémonos, pues, confiadamente al trono de la gracia, para alcanzar misericordia y hallar gracia para el oportuno socorro.",
  t_fr:"Approchons-nous donc avec assurance du trône de la grâce, afin d’obtenir miséricorde et de trouver grâce, pour être secourus dans nos besoins."},
22:{r:"Philippians 4:19",r_es:"Filipenses 4:19",r_fr:"Philippiens 4:19",
  t:"And my God will supply every need of yours according to his riches in glory in Christ Jesus.",
  t_es:"Mi Dios, pues, suplirá todo lo que os falta conforme a sus riquezas en gloria en Cristo Jesús.",
  t_fr:"Et mon Dieu pourvoira à tous vos besoins selon sa richesse, avec gloire, en Jésus-Christ."}
},
  checks: [
  {k:"read",l:"Read the passage",l_es:"Lee el pasaje",l_fr:"Lis le passage"},
  {k:"pray",l:"Pray & journal",l_es:"Ora y escribe en tu diario",l_fr:"Prie et tiens un journal"},
  {k:"workout",l:"Workout (3–5x/week)",l_es:"Entrena (3–5x por semana)",l_fr:"Entraînement (3–5x par semaine)"},
  {k:"abstain",l:"Abstain from your one thing",l_es:"Abstente de aquello que decidiste",l_fr:"Abstiens-toi de la chose que tu as choisie"},
  {k:"marco",l:"Marco Polo update",l_es:"Mensaje en Marco Polo",l_fr:"Mise à jour Marco Polo"}
]
};
