// Iron Sharpens Iron v2.2.0 — Psalms Config (en/es/fr)
window.PLAN = {
  title: "Psalms",
  title_es: "Salmos",
  title_fr: "Psaumes",
  subtitle: "PSALMS — 30-DAY CHALLENGE",
  subtitle_es: "SALMOS — RETO DE 30 DÍAS",
  subtitle_fr: "PSAUMES — DÉFI DE 30 JOURS",
  storageKey: "isi-psalms-v2",
  totalDays: 30,
  days: [
{day:1,reading:"Psalm 1",topic:"The Two Paths",topic_es:"Los dos caminos",topic_fr:"Les deux chemins",ph:1,
  summary:"The righteous man delights in the law of the Lord. He is like a tree planted by streams of water. The wicked are like chaff the wind drives away. Two paths, two destinies.",
  summary_es:"El hombre justo se deleita en la ley de Jehová. Es como un árbol plantado junto a corrientes de aguas. Los impíos son como el tamo que arrebata el viento. Dos caminos, dos destinos.",
  summary_fr:"Le juste fait ses délices de la loi de l’Éternel. Il est comme un arbre planté près d’un courant d’eau. Les méchants sont comme la paille que le vent emporte. Deux chemins, deux destinées."},
{day:2,reading:"Psalm 5",topic:"A Prayer for Protection",topic_es:"Oración por protección",topic_fr:"Prière pour la protection",
  summary:"David cries out to God in the morning. The Lord hates wickedness. ‘Lead me, O Lord, in your righteousness — make your way straight before me.’",
  summary_es:"David clama a Dios en la mañana. Jehová aborrece la maldad. ‘Guíame, Jehová, en tu justicia — endereza delante de mí tu camino.’",
  summary_fr:"David crie à Dieu dès le matin. L’Éternel hait la méchanceté. ‘Éternel, conduis-moi dans ta justice — aplanis ta voie sous mes pas.’"},
{day:3,reading:"Psalm 15",topic:"Who May Dwell with God?",topic_es:"¿Quién habitará con Dios?",topic_fr:"Qui demeurera avec Dieu ?",
  summary:"Lord, who may live on your holy mountain? He who walks blamelessly, speaks truth in his heart, and keeps his oath even when it hurts.",
  summary_es:"Jehová, ¿quién habitará en tu monte santo? El que anda en integridad, habla verdad en su corazón y aun jurando en daño suyo, no por eso cambia.",
  summary_fr:"Éternel, qui séjournera dans ta sainte montagne ? Celui qui marche dans l’intégrité, qui dit la vérité selon son cœur, et qui ne se rétracte pas, s’il fait un serment à son préjudice."},
{day:4,reading:"Psalm 19",topic:"The Heavens Declare God’s Glory",topic_es:"Los cielos cuentan la gloria de Dios",topic_fr:"Les cieux racontent la gloire de Dieu",
  summary:"The heavens declare the glory of God. The law of the Lord is perfect, reviving the soul. ‘Let the words of my mouth and the meditation of my heart be acceptable in your sight.’",
  summary_es:"Los cielos cuentan la gloria de Dios. La ley de Jehová es perfecta, que convierte el alma. ‘Sean gratos los dichos de mi boca y la meditación de mi corazón delante de ti.’",
  summary_fr:"Les cieux racontent la gloire de Dieu. La loi de l’Éternel est parfaite, elle restaure l’âme. ‘Reçois favorablement les paroles de ma bouche et les sentiments de mon cœur.’"},
{day:5,reading:"Psalm 23",topic:"The Lord Is My Shepherd",topic_es:"Jehová es mi pastor",topic_fr:"L’Éternel est mon berger",
  summary:"The Lord is my shepherd; I shall not want. He leads me beside still waters and restores my soul. Even through the valley of the shadow of death — I will fear no evil.",
  summary_es:"Jehová es mi pastor; nada me faltará. Junto a aguas de reposo me pastoreará. Confortará mi alma. Aunque ande en valle de sombra de muerte — no temeré mal alguno.",
  summary_fr:"L’Éternel est mon berger : je ne manquerai de rien. Il me dirige près des eaux paisibles. Il restaure mon âme. Quand je marche dans la vallée de l’ombre de la mort — je ne crains aucun mal."},
{day:6,reading:"Psalm 25",topic:"Teach Me Your Paths",topic_es:"Enséñame tus caminos",topic_fr:"Enseigne-moi tes voies",
  summary:"To you, O Lord, I lift up my soul. Show me your ways, teach me your paths. Guard my life and rescue me — I take refuge in you.",
  summary_es:"A ti, oh Jehová, levantaré mi alma. Muéstrame, oh Jehová, tus caminos; enséñame tus sendas. Guarda mi alma y líbrame — en ti me he refugiado.",
  summary_fr:"Éternel, j’élève à toi mon âme. Éternel, fais-moi connaître tes voies, enseigne-moi tes sentiers. Garde mon âme et sauve-moi — c’est en toi que je me confie."},
{day:7,reading:"Psalm 27",topic:"The Lord Is My Light",topic_es:"Jehová es mi luz",topic_fr:"L’Éternel est ma lumière",
  summary:"The Lord is my light and my salvation — whom shall I fear? One thing I ask: to dwell in the house of the Lord all the days of my life. Wait for the Lord; be strong.",
  summary_es:"Jehová es mi luz y mi salvación; ¿de quién temeré? Una cosa he demandado a Jehová: que esté yo en la casa de Jehová todos los días de mi vida. Espera a Jehová; esfuérzate.",
  summary_fr:"L’Éternel est ma lumière et mon salut : de qui aurais-je crainte ? Je demande à l’Éternel une chose : habiter dans la maison de l’Éternel tous les jours de ma vie. Espère en l’Éternel ! Fortifie-toi."},
{day:8,reading:"Psalm 32",topic:"The Joy of Forgiveness",topic_es:"El gozo del perdón",topic_fr:"La joie du pardon",ph:2,
  summary:"Blessed is the one whose transgression is forgiven. When David kept silent, his bones wasted away. He confessed — and the Lord forgave. Be glad in the Lord, you righteous.",
  summary_es:"Bienaventurado aquel cuya transgresión ha sido perdonada. Mientras callé, se envejecieron mis huesos. Confesé — y Jehová perdonó. Alegraos en Jehová, vosotros los justos.",
  summary_fr:"Heureux celui à qui la transgression est remise. Tant que je me suis tu, mes os se consumaient. J’ai confessé — et l’Éternel a pardonné. Justes, réjouissez-vous en l’Éternel."},
{day:9,reading:"Psalm 34",topic:"Taste and See",topic_es:"Gustad y ved",topic_fr:"Goûtez et voyez",
  summary:"I sought the Lord and He answered me. ‘Oh, taste and see that the Lord is good!’ The righteous cry out and the Lord hears them. He is close to the brokenhearted.",
  summary_es:"Busqué a Jehová, y él me oyó. ‘Gustad, y ved que es bueno Jehová.’ Claman los justos, y Jehová oye. Cercano está Jehová a los quebrantados de corazón.",
  summary_fr:"J’ai cherché l’Éternel, et il m’a répondu. ‘Sentez et voyez combien l’Éternel est bon !’ Quand les justes crient, l’Éternel entend. L’Éternel est près de ceux qui ont le cœur brisé."},
{day:10,reading:"Psalm 37",topic:"Trust and Do Not Fret",topic_es:"Confía y no te impacientes",topic_fr:"Confie-toi et ne t’irrite pas",
  summary:"Do not fret because of evildoers. Trust in the Lord and do good. Delight yourself in the Lord, and He will give you the desires of your heart. Commit your way to Him.",
  summary_es:"No te impacientes a causa de los malignos. Confía en Jehová, y haz el bien. Deléitate asimismo en Jehová, y él te concederá las peticiones de tu corazón. Encomienda a Jehová tu camino.",
  summary_fr:"Ne t’irrite pas contre les méchants. Confie-toi en l’Éternel, et pratique le bien. Fais de l’Éternel tes délices, et il te donnera ce que ton cœur désire. Recommande ton sort à l’Éternel."},
{day:11,reading:"Psalm 42",topic:"Thirsting for God",topic_es:"Sed de Dios",topic_fr:"Soif de Dieu",
  summary:"As the deer pants for flowing streams, so pants my soul for you, O God. ‘Why are you cast down, O my soul? Hope in God, for I shall again praise Him.’",
  summary_es:"Como el ciervo brama por las corrientes de las aguas, así clama por ti, oh Dios, el alma mía. ‘¿Por qué te abates, oh alma mía? Espera en Dios; aún he de alabarle.’",
  summary_fr:"Comme une biche soupire après des courants d’eau, ainsi mon âme soupire après toi, ô Dieu ! ‘Pourquoi t’abats-tu, mon âme ? Espère en Dieu, car je le louerai encore.’"},
{day:12,reading:"Psalm 46",topic:"God Is Our Refuge",topic_es:"Dios es nuestro refugio",topic_fr:"Dieu est notre refuge",
  summary:"God is our refuge and strength, a very present help in trouble. Therefore we will not fear. ‘Be still, and know that I am God.’",
  summary_es:"Dios es nuestro amparo y fortaleza, nuestro pronto auxilio en las tribulaciones. Por tanto, no temeremos. ‘Estad quietos, y conoced que yo soy Dios.’",
  summary_fr:"Dieu est pour nous un refuge et un appui, un secours qui ne manque jamais dans la détresse. C’est pourquoi nous ne craignons rien. ‘Arrêtez, et sachez que je suis Dieu.’"},
{day:13,reading:"Psalm 51",topic:"Create in Me a Clean Heart",topic_es:"Crea en mí un corazón limpio",topic_fr:"Crée en moi un cœur pur",
  summary:"David’s prayer after his sin with Bathsheba. ‘Against you, you only, have I sinned.’ Create in me a clean heart, O God. Restore the joy of your salvation.",
  summary_es:"La oración de David tras su pecado con Betsabé. ‘Contra ti, contra ti solo he pecado.’ Crea en mí, oh Dios, un corazón limpio. Vuélveme el gozo de tu salvación.",
  summary_fr:"La prière de David après son péché avec Bath-Schéba. ‘J’ai péché contre toi seul.’ Ô Dieu, crée en moi un cœur pur. Rends-moi la joie de ton salut."},
{day:14,reading:"Psalm 56",topic:"When I Am Afraid, I Trust",topic_es:"Cuando temo, confío",topic_fr:"Quand je suis dans la crainte, je me confie",
  summary:"When I am afraid, I put my trust in you. In God, whose word I praise — what can man do to me? You have kept count of my tossings; you put my tears in your bottle.",
  summary_es:"En el día que temo, yo en ti confío. En Dios alabaré su palabra — ¿qué puede hacerme el hombre? Mis huidas tú has contado; pon mis lágrimas en tu redoma.",
  summary_fr:"Quand je suis dans la crainte, en toi je me confie. Je me glorifierai en Dieu, en sa parole — que peut me faire l’homme ? Tu comptes les pas de ma vie errante ; recueille mes larmes dans ton outre."},
{day:15,reading:"Psalm 62",topic:"My Soul Waits for God Alone",topic_es:"Mi alma reposa solo en Dios",topic_fr:"Mon âme se repose en Dieu seul",ph:3,
  summary:"For God alone my soul waits in silence; from Him comes my salvation. He alone is my rock. Trust in Him at all times. Pour out your heart before Him.",
  summary_es:"En Dios solamente está acallada mi alma; de él viene mi salvación. Él solamente es mi roca. Esperad en él en todo tiempo, oh pueblos; derramad delante de él vuestro corazón.",
  summary_fr:"Oui, c’est en Dieu que mon âme se confie ; de lui vient mon salut. Lui seul est mon rocher. En tout temps, peuples, confiez-vous en lui ; répandez vos cœurs en sa présence."},
{day:16,reading:"Psalm 63",topic:"Seeking God in the Wilderness",topic_es:"Buscar a Dios en el desierto",topic_fr:"Chercher Dieu au désert",
  summary:"O God, you are my God; earnestly I seek you. My soul thirsts for you in a dry and weary land. Your steadfast love is better than life.",
  summary_es:"Dios, Dios mío eres tú; de madrugada te buscaré. Mi alma tiene sed de ti, en tierra seca y árida donde no hay aguas. Mejor es tu misericordia que la vida.",
  summary_fr:"Ô Dieu ! tu es mon Dieu, je te cherche. Mon âme a soif de toi, dans une terre aride, desséchée, sans eau. Ta bonté vaut mieux que la vie."},
{day:17,reading:"Psalm 73",topic:"The Prosperity of the Wicked",topic_es:"La prosperidad de los impíos",topic_fr:"La prospérité des méchants",
  summary:"Asaph nearly stumbles watching the wicked prosper. Then he enters the sanctuary and understands their end. ‘Whom have I in heaven but you?’ God is the strength of my heart.",
  summary_es:"Asaf casi tropieza al ver la prosperidad de los impíos. Luego entra en el santuario y comprende el fin de ellos. ‘¿A quién tengo yo en los cielos sino a ti?’ Dios es la fortaleza de mi corazón.",
  summary_fr:"Asaph manque de chanceler en voyant la prospérité des méchants. Puis il entre dans le sanctuaire et comprend leur fin. ‘Qui ai-je au ciel que toi ?’ Dieu est le rocher de mon cœur."},
{day:18,reading:"Psalm 77",topic:"Remembering God’s Works",topic_es:"Recordar las obras de Dios",topic_fr:"Se souvenir des œuvres de Dieu",
  summary:"In the day of trouble I seek the Lord. Has God forgotten to be gracious? Then I remember His deeds — the wonders of old. You are the God who works wonders.",
  summary_es:"En el día de mi angustia busqué al Señor. ¿Ha olvidado Dios el tener misericordia? Entonces me acuerdo de las obras de JAH — las maravillas que hiciste antiguamente. Tú eres el Dios que hace maravillas.",
  summary_fr:"Au jour de ma détresse, je cherche le Seigneur. Dieu a-t-il oublié d’avoir compassion ? Alors je me souviens des œuvres de l’Éternel — des merveilles d’autrefois. Tu es le Dieu qui fait des prodiges."},
{day:19,reading:"Psalm 82",topic:"God Judges the Judges",topic_es:"Dios juzga a los jueces",topic_fr:"Dieu juge les juges",
  summary:"God takes His stand in the divine council. ‘How long will you judge unjustly?’ Defend the weak and fatherless. Rescue the weak and needy. Rise up, O God, judge the earth.",
  summary_es:"Dios está en la reunión de los dioses. ‘¿Hasta cuándo juzgaréis injustamente?’ Defended al débil y al huérfano; librad al afligido y al menesteroso. Levántate, oh Dios, juzga la tierra.",
  summary_fr:"Dieu se tient dans l’assemblée de Dieu. ‘Jusqu’à quand jugerez-vous avec iniquité ?’ Rendez justice au faible et à l’orphelin. Délivrez le misérable et l’indigent. Lève-toi, ô Dieu, juge la terre."},
{day:20,reading:"Psalm 84",topic:"How Lovely Is Your Dwelling Place",topic_es:"¡Cuán amables son tus moradas!",topic_fr:"Que tes demeures sont aimables !",
  summary:"My soul longs for the courts of the Lord. Blessed are those whose strength is in you. A day in your courts is better than a thousand elsewhere. The Lord bestows favor and honor.",
  summary_es:"Anhela mi alma los atrios de Jehová. Bienaventurado el hombre que tiene en ti sus fuerzas. Mejor es un día en tus atrios que mil fuera de ellos. Gracia y gloria dará Jehová.",
  summary_fr:"Mon âme soupire après les parvis de l’Éternel. Heureux ceux qui placent en toi leur appui. Mieux vaut un jour dans tes parvis que mille ailleurs. L’Éternel donne la grâce et la gloire."},
{day:21,reading:"Psalm 90",topic:"Teach Us to Number Our Days",topic_es:"Enséñanos a contar nuestros días",topic_fr:"Enseigne-nous à compter nos jours",
  summary:"Lord, you have been our dwelling place in all generations. Our days pass away under your wrath. ‘Teach us to number our days that we may get a heart of wisdom.’",
  summary_es:"Señor, tú nos has sido refugio de generación en generación. Todos nuestros días declinan a causa de tu ira. ‘Enséñanos de tal modo a contar nuestros días, que traigamos al corazón sabiduría.’",
  summary_fr:"Seigneur, tu as été pour nous un refuge, de génération en génération. Tous nos jours s’évanouissent par ton courroux. ‘Enseigne-nous à bien compter nos jours, afin que notre cœur parvienne à la sagesse.’"},
{day:22,reading:"Psalm 91",topic:"Under the Shadow of the Almighty",topic_es:"A la sombra del Omnipotente",topic_fr:"À l’ombre du Tout-Puissant",ph:4,
  summary:"He who dwells in the shelter of the Most High will abide in the shadow of the Almighty. A thousand may fall at your side — it will not come near you. He will command His angels concerning you.",
  summary_es:"El que habita al abrigo del Altísimo morará bajo la sombra del Omnipotente. Caerán a tu lado mil — mas a ti no llegará. Pues a sus ángeles mandará acerca de ti.",
  summary_fr:"Celui qui demeure sous l’abri du Très-Haut repose à l’ombre du Tout-Puissant. Que mille tombent à ton côté — tu ne seras pas atteint. Car il ordonnera à ses anges de te garder."},
{day:23,reading:"Psalm 100",topic:"Shout for Joy",topic_es:"Cantad jubilosos",topic_fr:"Poussez vers Dieu des cris de joie",
  summary:"Make a joyful noise to the Lord, all the earth! Know that the Lord, He is God. Enter His gates with thanksgiving. His steadfast love endures forever.",
  summary_es:"Cantad alegres a Dios, habitantes de toda la tierra. Reconoced que Jehová es Dios. Entrad por sus puertas con acción de gracias. Para siempre es su misericordia.",
  summary_fr:"Poussez vers l’Éternel des cris de joie, vous tous, habitants de la terre ! Sachez que l’Éternel est Dieu. Entrez dans ses portes avec des louanges. Sa bonté dure toujours."},
{day:24,reading:"Psalm 103",topic:"Bless the Lord, O My Soul",topic_es:"Bendice, alma mía, a Jehová",topic_fr:"Mon âme, bénis l’Éternel",
  summary:"Bless the Lord, O my soul, and forget not all His benefits. He forgives, heals, redeems, crowns you with steadfast love. As a father shows compassion to his children, so the Lord.",
  summary_es:"Bendice, alma mía, a Jehová, y no olvides ninguno de sus beneficios. Él es quien perdona, sana, rescata y te corona de favores y misericordias. Como el padre se compadece de los hijos, se compadece Jehová.",
  summary_fr:"Mon âme, bénis l’Éternel, et n’oublie aucun de ses bienfaits ! Il pardonne, guérit, rachète, te couronne de bonté et de miséricorde. Comme un père a compassion de ses enfants, l’Éternel a compassion de ceux qui le craignent."},
{day:25,reading:"Psalm 121",topic:"My Help Comes from the Lord",topic_es:"Mi socorro viene de Jehová",topic_fr:"Mon secours vient de l’Éternel",
  summary:"I lift up my eyes to the hills. From where does my help come? My help comes from the Lord, who made heaven and earth. He will not let your foot be moved. He who keeps you will not slumber.",
  summary_es:"Alzaré mis ojos a los montes; ¿de dónde vendrá mi socorro? Mi socorro viene de Jehová, que hizo los cielos y la tierra. No dará tu pie al resbaladero, ni se dormirá el que te guarda.",
  summary_fr:"Je lève mes yeux vers les montagnes : d’où me viendra le secours ? Le secours me vient de l’Éternel, qui a fait les cieux et la terre. Il ne permettra point que ton pied chancelle ; celui qui te garde ne sommeillera point."},
{day:26,reading:"Psalm 127",topic:"Unless the Lord Builds the House",topic_es:"Si Jehová no edifica la casa",topic_fr:"Si l’Éternel ne bâtit la maison",
  summary:"Unless the Lord builds the house, those who build it labor in vain. Unless the Lord watches over the city, the watchman stays awake in vain. Children are a heritage from the Lord.",
  summary_es:"Si Jehová no edificare la casa, en vano trabajan los que la edifican; si Jehová no guardare la ciudad, en vano vela la guardia. Herencia de Jehová son los hijos.",
  summary_fr:"Si l’Éternel ne bâtit la maison, ceux qui la bâtissent travaillent en vain ; si l’Éternel ne garde la ville, celui qui la garde veille en vain. Les fils sont un héritage de l’Éternel."},
{day:27,reading:"Psalm 139",topic:"Fearfully and Wonderfully Made",topic_es:"Formidables y maravillosas son tus obras",topic_fr:"Tes œuvres sont admirables",
  summary:"O Lord, you have searched me and known me. Where shall I go from your Spirit? I am fearfully and wonderfully made. ‘Search me, O God, and know my heart.’",
  summary_es:"Oh Jehová, tú me has examinado y conocido. ¿A dónde me iré de tu Espíritu? Formidables, maravillosas son tus obras. ‘Examíname, oh Dios, y conoce mi corazón.’",
  summary_fr:"Éternel, tu me sondes et tu me connais. Où irais-je loin de ton Esprit ? Tes œuvres sont admirables. ‘Sonde-moi, ô Dieu, et connais mon cœur !’"},
{day:28,reading:"Psalm 142",topic:"A Cry from the Cave",topic_es:"Un clamor desde la cueva",topic_fr:"Un cri du fond de la caverne",
  summary:"David’s prayer from the cave. ‘I cry to you, O Lord; I say, you are my refuge.’ No one cares for my soul — but you, Lord. Set me free from my prison.",
  summary_es:"La oración de David desde la cueva. ‘He clamado a ti, oh Jehová; dije: tú eres mi esperanza.’ No hay quien tenga cuidado de mi vida — mas tú, Jehová. Saca mi alma de la cárcel.",
  summary_fr:"La prière de David dans la caverne. ‘Éternel ! Je crie à toi. Je dis : tu es mon refuge.’ Personne ne s’inquiète de mon âme — mais toi, Éternel. Tire-moi de ma prison."},
{day:29,reading:"Psalm 144",topic:"Blessed Be the Lord, My Rock",topic_es:"Bendito sea Jehová, mi roca",topic_fr:"Béni soit l’Éternel, mon rocher",
  summary:"Blessed be the Lord, my rock, who trains my hands for war and my fingers for battle. He is my steadfast love and my fortress, my stronghold and my deliverer.",
  summary_es:"Bendito sea Jehová, mi roca, quien adiestra mis manos para la batalla, y mis dedos para la guerra. Misericordia mía y mi castillo, fortaleza mía y mi libertador.",
  summary_fr:"Béni soit l’Éternel, mon rocher, qui exerce mes mains au combat, mes doigts à la bataille ! Il est ma bonté et ma forteresse, ma haute retraite et mon libérateur."},
{day:30,reading:"Psalm 150",topic:"Let Everything Praise the Lord",topic_es:"Todo lo que respira alabe a Jehová",topic_fr:"Que tout ce qui respire loue l’Éternel",
  summary:"Praise the Lord! Praise Him with trumpet, lute, harp, tambourine, strings, pipe, and cymbals. Let everything that has breath praise the Lord!",
  summary_es:"¡Alabad a Jehová! Alabadle a son de bocina, salterio y arpa. Alabadle con pandero y danza, con cuerdas y flautas, con címbalos. ¡Todo lo que respira alabe a JAH!",
  summary_fr:"Louez l’Éternel ! Louez-le au son de la trompette, du luth, de la harpe, du tambourin, des instruments à cordes, du chalumeau et des cymbales ! Que tout ce qui respire loue l’Éternel !"}
],
  verses: {
1:{r:"Psalm 19:1",r_es:"Salmo 19:1",r_fr:"Psaume 19:1",
  t:"The heavens declare the glory of God, and the sky above proclaims his handiwork.",
  t_es:"Los cielos cuentan la gloria de Dios, y el firmamento anuncia la obra de sus manos.",
  t_fr:"Les cieux racontent la gloire de Dieu, et l’étendue manifeste l’œuvre de ses mains."},
8:{r:"Psalm 51:10",r_es:"Salmo 51:10",r_fr:"Psaume 51:10",
  t:"Create in me a clean heart, O God, and renew a right spirit within me.",
  t_es:"Crea en mí, oh Dios, un corazón limpio, y renueva un espíritu recto dentro de mí.",
  t_fr:"Ô Dieu ! crée en moi un cœur pur, renouvelle en moi un esprit bien disposé."},
15:{r:"Psalm 84:11",r_es:"Salmo 84:11",r_fr:"Psaume 84:11",
  t:"For the Lord God is a sun and shield; the Lord bestows favor and honor. No good thing does he withhold from those who walk uprightly.",
  t_es:"Porque sol y escudo es Jehová Dios; gracia y gloria dará Jehová. No quitará el bien a los que andan en integridad.",
  t_fr:"Car l’Éternel Dieu est un soleil et un bouclier ; l’Éternel donne la grâce et la gloire. Il ne refuse aucun bien à ceux qui marchent dans l’intégrité."},
22:{r:"Psalm 139:23–24",r_es:"Salmo 139:23–24",r_fr:"Psaume 139:23–24",
  t:"Search me, O God, and know my heart! Try me and know my thoughts! And see if there be any grievous way in me, and lead me in the way everlasting!",
  t_es:"Examíname, oh Dios, y conoce mi corazón; pruébame y conoce mis pensamientos; y ve si hay en mí camino de perversidad, y guíame en el camino eterno.",
  t_fr:"Sonde-moi, ô Dieu, et connais mon cœur ! Éprouve-moi, et connais mes pensées ! Regarde si je suis sur une mauvaise voie, et conduis-moi sur la voie de l’éternité !"}
},
  checks: [
  {k:"read",l:"Read the passage",l_es:"Lee el pasaje",l_fr:"Lis le passage"},
  {k:"pray",l:"Pray & journal",l_es:"Ora y escribe en tu diario",l_fr:"Prie et tiens un journal"},
  {k:"workout",l:"Workout (3–5x/week)",l_es:"Entrena (3–5x por semana)",l_fr:"Entraîne-toi (3–5x par semaine)"},
  {k:"danger",l:"Stay Dangerous (1x/phase)",l_es:"Mantente peligroso (1x por fase)",l_fr:"Reste dangereux (1x par phase)"},
  {k:"abstain",l:"Abstain from your one thing",l_es:"Abstente de aquello que decidiste",l_fr:"Abstiens-toi de la chose que tu as choisie"},
  {k:"marco",l:"Marco Polo update",l_es:"Mensaje en Marco Polo",l_fr:"Mise à jour Marco Polo"}
]
};
