// Iron Sharpens Iron v2.2.0 — Gospel of Matthew (August) Config (en/es/fr)
window.PLAN = {
  title: "Gospel of Matthew",
  title_es: "Evangelio de Mateo",
  title_fr: "Évangile de Matthieu",
  subtitle: "GOSPEL OF MATTHEW — 30-DAY CHALLENGE",
  subtitle_es: "EVANGELIO DE MATEO — RETO DE 30 DÍAS",
  subtitle_fr: "ÉVANGILE DE MATTHIEU — DÉFI DE 30 JOURS",
  storageKey: "isi-august-v1",
  startDate: "2026-08-01",
  totalDays: 30,
  days: [
{day:1,reading:"Matthew 1",topic:"The Genealogy & Birth of Jesus",topic_es:"La genealogía y el nacimiento de Jesús",topic_fr:"La généalogie et la naissance de Jésus",ph:1,
  summary:"“Behold, the virgin shall conceive and bear a son, and they shall call his name Immanuel” (which means, God with us).",
  summary_es:"He aquí, una virgen concebirá y dará a luz un hijo, y llamarás su nombre Emanuel, que traducido es: Dios con nosotros.",
  summary_fr:"Voici, la vierge sera enceinte, elle enfantera un fils, et on lui donnera le nom d’Emmanuel, ce qui signifie Dieu avec nous."},
{day:2,reading:"Matthew 2",topic:"Wise Men & Flight to Egypt",topic_es:"Los magos y la huida a Egipto",topic_fr:"Les mages et la fuite en Égypte",
  summary:"“Where is he who has been born king of the Jews? For we saw his star when it rose and have come to worship him.”",
  summary_es:"¿Dónde está el rey de los judíos, que ha nacido? Porque su estrella hemos visto en el oriente, y venimos a adorarle.",
  summary_fr:"Où est le roi des Juifs qui vient de naître ? car nous avons vu son étoile en Orient, et nous sommes venus pour l’adorer."},
{day:3,reading:"Matthew 3",topic:"John the Baptist & Jesus’ Baptism",topic_es:"Juan el Bautista y el bautismo de Jesús",topic_fr:"Jean-Baptiste et le baptême de Jésus",
  summary:"And behold, a voice from heaven said, “This is my beloved Son, with whom I am well pleased.”",
  summary_es:"Y hubo una voz de los cielos, que decía: Este es mi Hijo amado, en quien tengo complacencia.",
  summary_fr:"Et voici, une voix fit entendre des cieux ces paroles : Celui-ci est mon Fils bien-aimé, en qui j’ai mis toute mon affection."},
{day:4,reading:"Matthew 4",topic:"Temptation & First Disciples",topic_es:"La tentación y los primeros discípulos",topic_fr:"La tentation et les premiers disciples",
  summary:"And he said to them, “Follow me, and I will make you fishers of men.”",
  summary_es:"Y les dijo: Venid en pos de mí, y os haré pescadores de hombres.",
  summary_fr:"Il leur dit : Suivez-moi, et je vous ferai pêcheurs d’hommes."},
{day:5,reading:"Matthew 5",topic:"Sermon on the Mount: The Beatitudes",topic_es:"Sermón del Monte: las Bienaventuranzas",topic_fr:"Sermon sur la montagne : les Béatitudes",
  summary:"In the same way, let your light shine before others, so that they may see your good works and give glory to your Father who is in heaven.",
  summary_es:"Así alumbre vuestra luz delante de los hombres, para que vean vuestras buenas obras, y glorifiquen a vuestro Padre que está en los cielos.",
  summary_fr:"Que votre lumière luise ainsi devant les hommes, afin qu’ils voient vos bonnes œuvres, et qu’ils glorifient votre Père qui est dans les cieux."},
{day:6,reading:"Matthew 6",topic:"Prayer, Fasting & Anxiety",topic_es:"Oración, ayuno y ansiedad",topic_fr:"Prière, jeûne et anxiété",
  summary:"For where your treasure is, there your heart will be also.",
  summary_es:"Porque donde esté vuestro tesoro, allí estará también vuestro corazón.",
  summary_fr:"Car là où est ton trésor, là aussi sera ton cœur."},
{day:7,reading:"Matthew 7",topic:"Judging, the Narrow Gate, Two Builders",topic_es:"Juzgar, la puerta estrecha y los dos constructores",topic_fr:"Juger, la porte étroite et les deux bâtisseurs",
  summary:"Everyone then who hears these words of mine and does them will be like a wise man who built his house on the rock.",
  summary_es:"Cualquiera, pues, que me oye estas palabras, y las hace, le compararé a un hombre prudente, que edificó su casa sobre la roca.",
  summary_fr:"C’est pourquoi, quiconque entend ces paroles que je dis et les met en pratique, sera semblable à un homme prudent qui a bâti sa maison sur le roc."},
{day:8,reading:"Matthew 8",topic:"Healings & the Cost of Following",topic_es:"Sanidades y el precio de seguirlo",topic_fr:"Guérisons et le prix de le suivre",ph:2,
  summary:"And the men marveled, saying, “What sort of man is this, that even winds and sea obey him?”",
  summary_es:"Y los hombres se maravillaron, diciendo: ¿Qué hombre es éste, que aun los vientos y el mar le obedecen?",
  summary_fr:"Ces hommes furent saisis d’étonnement : Quel est celui-ci, disaient-ils, à qui obéissent même les vents et la mer ?"},
{day:9,reading:"Matthew 9",topic:"More Healings & the Call of Matthew",topic_es:"Más sanidades y el llamado de Mateo",topic_fr:"D’autres guérisons et l’appel de Matthieu",
  summary:"Go and learn what this means: ‘I desire mercy, and not sacrifice.’ For I came not to call the righteous, but sinners.",
  summary_es:"Id, pues, y aprended lo que significa: Misericordia quiero, y no sacrificio. Porque no he venido a llamar a justos, sino a pecadores, al arrepentimiento.",
  summary_fr:"Allez, et apprenez ce que signifie : Je prends plaisir à la miséricorde, et non aux sacrifices. Car je ne suis pas venu appeler des justes, mais des pécheurs."},
{day:10,reading:"Matthew 10",topic:"Sending Out the Twelve",topic_es:"Envío de los doce",topic_fr:"L’envoi des douze",
  summary:"Whoever finds his life will lose it, and whoever loses his life for my sake will find it.",
  summary_es:"El que halla su vida, la perderá; y el que pierde su vida por causa de mí, la hallará.",
  summary_fr:"Celui qui conservera sa vie la perdra, et celui qui perdra sa vie à cause de moi la retrouvera."},
{day:11,reading:"Matthew 11",topic:"John’s Question & Jesus’ Invitation",topic_es:"La pregunta de Juan y la invitación de Jesús",topic_fr:"La question de Jean et l’invitation de Jésus",
  summary:"Come to me, all who labor and are heavy laden, and I will give you rest.",
  summary_es:"Venid a mí todos los que estáis trabajados y cargados, y yo os haré descansar.",
  summary_fr:"Venez à moi, vous tous qui êtes fatigués et chargés, et je vous donnerai du repos."},
{day:12,reading:"Matthew 12",topic:"Lord of the Sabbath & Blasphemy Warning",topic_es:"Señor del sábado y advertencia de blasfemia",topic_fr:"Seigneur du sabbat et avertissement de blasphème",
  summary:"For the Son of Man is lord of the Sabbath.",
  summary_es:"Porque el Hijo del Hombre es Señor del día de reposo.",
  summary_fr:"Car le Fils de l’homme est maître du sabbat."},
{day:13,reading:"Matthew 13",topic:"Parables of the Kingdom",topic_es:"Parábolas del Reino",topic_fr:"Paraboles du Royaume",
  summary:"The kingdom of heaven is like treasure hidden in a field, which a man found and covered up. Then in his joy he goes and sells all that he has and buys that field.",
  summary_es:"Además, el reino de los cielos es semejante a un tesoro escondido en un campo, el cual un hombre halla, y lo esconde de nuevo; y gozoso por ello va y vende todo lo que tiene, y compra aquel campo.",
  summary_fr:"Le royaume des cieux est encore semblable à un trésor caché dans un champ. L’homme qui l’a trouvé le cache ; et, dans sa joie, il va vendre tout ce qu’il a, et achète ce champ."},
{day:14,reading:"Matthew 14",topic:"John Beheaded & Feeding the 5,000",topic_es:"Decapitación de Juan y alimentación de los 5.000",topic_fr:"La décapitation de Jean et la multiplication des pains",
  summary:"But immediately Jesus spoke to them, saying, “Take heart; it is I. Do not be afraid.”",
  summary_es:"Pero en seguida Jesús les habló, diciendo: ¡Tened ánimo; yo soy, no temáis!",
  summary_fr:"Jésus leur dit aussitôt : Rassurez-vous, c’est moi ; n’ayez pas peur !"},
{day:15,reading:"Matthew 15",topic:"Clean & Unclean, Faith of a Canaanite Woman",topic_es:"Limpio e inmundo, la fe de la cananea",topic_fr:"Pur et impur, la foi de la Cananéenne",ph:3,
  summary:"Then Jesus answered her, “O woman, great is your faith! Be it done for you as you desire.” And her daughter was healed instantly.",
  summary_es:"Entonces respondiendo Jesús, dijo: Oh mujer, grande es tu fe; hágase contigo como quieres. Y su hija fue sanada desde aquella hora.",
  summary_fr:"Alors Jésus lui dit : Femme, ta foi est grande ; qu’il te soit fait comme tu veux. Et, à l’heure même, sa fille fut guérie."},
{day:16,reading:"Matthew 16",topic:"Peter’s Confession & the Cross Foretold",topic_es:"La confesión de Pedro y el anuncio de la cruz",topic_fr:"La confession de Pierre et l’annonce de la croix",
  summary:"And I tell you, you are Peter, and on this rock I will build my church, and the gates of hell shall not prevail against it.",
  summary_es:"Y yo también te digo, que tú eres Pedro, y sobre esta roca edificaré mi iglesia; y las puertas del Hades no prevalecerán contra ella.",
  summary_fr:"Et moi, je te dis que tu es Pierre, et que sur cette pierre je bâtirai mon Église, et que les portes du séjour des morts ne prévaudront point contre elle."},
{day:17,reading:"Matthew 17",topic:"The Transfiguration",topic_es:"La Transfiguración",topic_fr:"La Transfiguration",
  summary:"A voice from the cloud said, “This is my beloved Son, with whom I am well pleased; listen to him.”",
  summary_es:"Una nube de luz los cubrió; y he aquí una voz desde la nube, que decía: Este es mi Hijo amado, en quien tengo complacencia; a él oíd.",
  summary_fr:"Et voici, une voix fit entendre de la nuée ces paroles : Celui-ci est mon Fils bien-aimé, en qui j’ai mis toute mon affection : écoutez-le !"},
{day:18,reading:"Matthew 18",topic:"Humility, Forgiveness & the Lost Sheep",topic_es:"Humildad, perdón y la oveja perdida",topic_fr:"Humilité, pardon et la brebis perdue",
  summary:"For where two or three are gathered in my name, there am I among them.",
  summary_es:"Porque donde están dos o tres congregados en mi nombre, allí estoy yo en medio de ellos.",
  summary_fr:"Car là où deux ou trois sont assemblés en mon nom, je suis au milieu d’eux."},
{day:19,reading:"Matthew 19",topic:"Marriage, Riches & Rewards",topic_es:"Matrimonio, riquezas y recompensas",topic_fr:"Mariage, richesses et récompenses",
  summary:"But Jesus looked at them and said, “With man this is impossible, but with God all things are possible.”",
  summary_es:"Y mirándolos Jesús, les dijo: Para los hombres esto es imposible; mas para Dios todo es posible.",
  summary_fr:"Jésus les regarda, et leur dit : Aux hommes cela est impossible, mais à Dieu tout est possible."},
{day:20,reading:"Matthew 20",topic:"Workers in the Vineyard & Servant Leadership",topic_es:"Los obreros en la viña y el liderazgo de servicio",topic_fr:"Les ouvriers de la vigne et le leadership-serviteur",
  summary:"Even as the Son of Man came not to be served but to serve, and to give his life as a ransom for many.",
  summary_es:"Como el Hijo del Hombre no vino para ser servido, sino para servir, y para dar su vida en rescate por muchos.",
  summary_fr:"C’est ainsi que le Fils de l’homme est venu, non pour être servi, mais pour servir et donner sa vie comme la rançon de plusieurs."},
{day:21,reading:"Matthew 21",topic:"Triumphal Entry & Temple Cleansing",topic_es:"Entrada Triunfal y purificación del templo",topic_fr:"Entrée triomphale et purification du temple",
  summary:"“Hosanna to the Son of David! Blessed is he who comes in the name of the Lord! Hosanna in the highest!”",
  summary_es:"¡Hosanna al Hijo de David! ¡Bendito el que viene en el nombre del Señor! ¡Hosanna en las alturas!",
  summary_fr:"Hosanna au Fils de David ! Béni soit celui qui vient au nom du Seigneur ! Hosanna dans les lieux très hauts !"},
{day:22,reading:"Matthew 22",topic:"Parables & the Greatest Commandment",topic_es:"Parábolas y el gran mandamiento",topic_fr:"Paraboles et le grand commandement",ph:4,
  summary:"You shall love the Lord your God with all your heart and with all your soul and with all your mind. This is the great and first commandment. And a second is like it: You shall love your neighbor as yourself.",
  summary_es:"Amarás al Señor tu Dios con todo tu corazón, y con toda tu alma, y con toda tu mente. Este es el primero y grande mandamiento. Y el segundo es semejante: Amarás a tu prójimo como a ti mismo.",
  summary_fr:"Tu aimeras le Seigneur, ton Dieu, de tout ton cœur, de toute ton âme, et de toute ta pensée. C’est le premier et le plus grand commandement. Et voici le second, qui lui est semblable : Tu aimeras ton prochain comme toi-même."},
{day:23,reading:"Matthew 23",topic:"Seven Woes to the Pharisees",topic_es:"Siete ayes a los fariseos",topic_fr:"Sept malheurs aux pharisiens",
  summary:"The greatest among you shall be your servant. Whoever exalts himself will be humbled, and whoever humbles himself will be exalted.",
  summary_es:"El que es el mayor de vosotros, sea vuestro siervo. Porque el que se enaltece será humillado, y el que se humilla será enaltecido.",
  summary_fr:"Le plus grand parmi vous sera votre serviteur. Quiconque s’élèvera sera abaissé, et quiconque s’abaissera sera élevé."},
{day:24,reading:"Matthew 24",topic:"Signs of the End",topic_es:"Señales del fin",topic_fr:"Les signes de la fin",
  summary:"Heaven and earth will pass away, but my words will not pass away.",
  summary_es:"El cielo y la tierra pasarán, pero mis palabras no pasarán.",
  summary_fr:"Le ciel et la terre passeront, mais mes paroles ne passeront point."},
{day:25,reading:"Matthew 25",topic:"Ten Virgins, Talents & the Sheep and Goats",topic_es:"Las diez vírgenes, los talentos y las ovejas y los cabritos",topic_fr:"Les dix vierges, les talents et les brebis et les boucs",
  summary:"And the King will answer them, “Truly, I say to you, as you did it to one of the least of these my brothers, you did it to me.”",
  summary_es:"Y respondiendo el Rey, les dirá: De cierto os digo que en cuanto lo hicisteis a uno de estos mis hermanos más pequeños, a mí lo hicisteis.",
  summary_fr:"Et le roi leur répondra : Je vous le dis en vérité, toutes les fois que vous avez fait ces choses à l’un de ces plus petits de mes frères, c’est à moi que vous les avez faites."},
{day:26,reading:"Matthew 26",topic:"Gethsemane, Betrayal & Trial",topic_es:"Getsemaní, traición y juicio",topic_fr:"Gethsémani, trahison et procès",
  summary:"“My Father, if it be possible, let this cup pass from me; nevertheless, not as I will, but as you will.”",
  summary_es:"Padre mío, si es posible, pase de mí esta copa; pero no sea como yo quiero, sino como tú.",
  summary_fr:"Mon Père, s’il est possible, que cette coupe s’éloigne de moi ! Toutefois, non pas ce que je veux, mais ce que tu veux."},
{day:27,reading:"Matthew 27",topic:"The Crucifixion",topic_es:"La Crucifixión",topic_fr:"La Crucifixion",
  summary:"When the centurion and those who were with him saw the earthquake and what took place, they were filled with awe and said, “Truly this was the Son of God!”",
  summary_es:"El centurión, y los que estaban con él guardando a Jesús, visto el terremoto, y las cosas que habían sido hechas, temieron en gran manera, y dijeron: Verdaderamente éste era Hijo de Dios.",
  summary_fr:"Le centenier et ceux qui étaient avec lui pour garder Jésus, voyant le tremblement de terre et ce qui venait d’arriver, furent saisis d’une grande frayeur, et dirent : Assurément, cet homme était Fils de Dieu."},
{day:28,reading:"Matthew 28",topic:"The Resurrection & Great Commission",topic_es:"La Resurrección y la Gran Comisión",topic_fr:"La Résurrection et la Grande Commission",
  summary:"Go therefore and make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit, teaching them to observe all that I have commanded you. And behold, I am with you always, to the end of the age.",
  summary_es:"Por tanto, id, y haced discípulos a todas las naciones, bautizándolos en el nombre del Padre, y del Hijo, y del Espíritu Santo; enseñándoles que guarden todas las cosas que os he mandado; y he aquí yo estoy con vosotros todos los días, hasta el fin del mundo.",
  summary_fr:"Allez, faites de toutes les nations des disciples, les baptisant au nom du Père, du Fils et du Saint-Esprit, et enseignez-leur à observer tout ce que je vous ai prescrit. Et voici, je suis avec vous tous les jours, jusqu’à la fin du monde."},
{day:29,reading:"Matthew 1–14",topic:"Full Re-Read: Part 1",topic_es:"Relectura completa: Parte 1",topic_fr:"Relecture intégrale : Partie 1",
  summary:"So whatever you wish that others would do to you, do also to them, for this is the Law and the Prophets.",
  summary_es:"Así que, todas las cosas que queráis que los hombres hagan con vosotros, así también haced vosotros con ellos; porque esto es la ley y los profetas.",
  summary_fr:"Tout ce que vous voulez que les hommes fassent pour vous, faites-le de même pour eux, car c’est la loi et les prophètes."},
{day:30,reading:"Matthew 15–28",topic:"Full Re-Read: Part 2",topic_es:"Relectura completa: Parte 2",topic_fr:"Relecture intégrale : Partie 2",
  summary:"He is not here, for he has risen, as he said. Come, see the place where he lay.",
  summary_es:"No está aquí, pues ha resucitado, como dijo. Venid, ved el lugar donde fue puesto el Señor.",
  summary_fr:"Il n’est point ici ; il est ressuscité, comme il l’avait dit. Venez, voyez le lieu où il était couché."}
],
  verses: {
1:{r:"Matthew 1:21",r_es:"Mateo 1:21",r_fr:"Matthieu 1:21",
  t:"She will bear a son, and you shall call his name Jesus, for he will save his people from their sins.",
  t_es:"Y dará a luz un hijo, y llamarás su nombre JESÚS, porque él salvará a su pueblo de sus pecados.",
  t_fr:"Elle enfantera un fils, et tu lui donneras le nom de Jésus ; c’est lui qui sauvera son peuple de ses péchés."},
8:{r:"Matthew 6:33",r_es:"Mateo 6:33",r_fr:"Matthieu 6:33",
  t:"But seek first the kingdom of God and his righteousness, and all these things will be added to you.",
  t_es:"Mas buscad primeramente el reino de Dios y su justicia, y todas estas cosas os serán añadidas.",
  t_fr:"Cherchez premièrement le royaume et la justice de Dieu ; et toutes ces choses vous seront données par-dessus."},
15:{r:"Matthew 10:16",r_es:"Mateo 10:16",r_fr:"Matthieu 10:16",
  t:"Behold, I am sending you out as sheep in the midst of wolves, so be wise as serpents and innocent as doves.",
  t_es:"He aquí, yo os envío como a ovejas en medio de lobos; sed, pues, prudentes como serpientes, y sencillos como palomas.",
  t_fr:"Voici, je vous envoie comme des brebis au milieu des loups. Soyez donc prudents comme les serpents, et simples comme les colombes."},
22:{r:"Matthew 16:24",r_es:"Mateo 16:24",r_fr:"Matthieu 16:24",
  t:"Then Jesus told his disciples, “If anyone would come after me, let him deny himself and take up his cross and follow me.”",
  t_es:"Entonces Jesús dijo a sus discípulos: Si alguno quiere venir en pos de mí, niéguese a sí mismo, y tome su cruz, y sígame.",
  t_fr:"Alors Jésus dit à ses disciples : Si quelqu’un veut venir après moi, qu’il renonce à lui-même, qu’il se charge de sa croix, et qu’il me suive."}
},
  checks: [
  {k:"read",l:"Read the passage",l_es:"Lee el pasaje",l_fr:"Lis le passage"},
  {k:"pray",l:"Pray & journal",l_es:"Ora y escribe en tu diario",l_fr:"Prie et tiens un journal"},
  {k:"workout",l:"Workout (3–5x/week)",l_es:"Entrena (3–5x por semana)",l_fr:"Entraînement (3–5x par semaine)"},
  {k:"abstain",l:"Abstain from your one thing",l_es:"Abstente de aquello que decidiste",l_fr:"Abstiens-toi de la chose que tu as choisie"},
  {k:"marco",l:"Marco Polo update",l_es:"Mensaje en Marco Polo",l_fr:"Mise à jour Marco Polo"}
]
};
