#!/usr/bin/env node
// Deterministic plan.json -> <month>/config.js + <month>/index.html.
// Model output is never written as executable code: the JSON is parsed here
// and re-serialized with JSON.stringify, so string content cannot escape its
// literal (validate.mjs additionally bans "<" in every string field).
//
// Usage: node pipeline/serialize.mjs <plan.json> <output-dir>

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const [, , planPath, outDir] = process.argv;
if (!planPath || !outDir) {
  console.error("Usage: node pipeline/serialize.mjs <plan.json> <output-dir>");
  process.exit(1);
}

const plan = JSON.parse(readFileSync(planPath, "utf8"));

// Only known keys, in stable order — anything unexpected in the JSON is dropped.
const DAY_KEYS = ["day", "reading", "topic", "topic_es", "topic_fr", "ph", "summary", "summary_es", "summary_fr"];
const VERSE_KEYS = ["r", "r_es", "r_fr", "t", "t_es", "t_fr"];
const CHECK_KEYS = ["k", "l", "l_es", "l_fr"];

function pick(obj, keys) {
  const out = {};
  for (const k of keys) if (obj[k] !== undefined) out[k] = obj[k];
  return out;
}

const clean = {
  title: plan.title,
  title_es: plan.title_es,
  title_fr: plan.title_fr,
  subtitle: plan.subtitle,
  subtitle_es: plan.subtitle_es,
  subtitle_fr: plan.subtitle_fr,
  storageKey: plan.storageKey,
  startDate: plan.startDate,
  totalDays: plan.totalDays,
  days: (plan.days || []).map((d) => pick(d, DAY_KEYS)),
  verses: Object.fromEntries(
    Object.entries(plan.verses || {}).map(([k, v]) => [k, pick(v, VERSE_KEYS)])
  ),
  checks: (plan.checks || []).map((c) => pick(c, CHECK_KEYS)),
};

const configJS =
  "// Iron Sharpens Iron — " + String(clean.title) + " Config (generated by pipeline)\n" +
  "window.PLAN = " + JSON.stringify(clean, null, 2) + ";\n";

function escHTML(s) {
  return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

const MONTHS = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
const [y, m] = String(clean.startDate).split("-").map(Number);
const monthLabel = MONTHS[(m || 1) - 1] + " " + y;
const description = "Iron Sharpens Iron: " + clean.title + " — " + monthLabel + " — 30-day challenge.";

const templatePath = join(dirname(fileURLToPath(import.meta.url)), "index.template.html");
const indexHTML = readFileSync(templatePath, "utf8")
  .replaceAll("{{TITLE}}", escHTML(clean.title))
  .replaceAll("{{SUBTITLE}}", escHTML(clean.subtitle))
  .replaceAll("{{DESCRIPTION}}", escHTML(description));

mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, "config.js"), configJS);
writeFileSync(join(outDir, "index.html"), indexHTML);
console.log("Wrote " + join(outDir, "config.js") + " and index.html (" + clean.days.length + " days)");
