// Iron Sharpens Iron v2.2.0 — Acts Config (en/es/fr)
window.PLAN = {
  title: "Acts",
  title_es: "Hechos",
  title_fr: "Actes",
  subtitle: "ACTS — 30-DAY CHALLENGE",
  subtitle_es: "HECHOS — RETO DE 30 DÍAS",
  subtitle_fr: "ACTES — DÉFI DE 30 JOURS",
  storageKey: "isi-acts-v2",
  totalDays: 30,
  days: [
{day:1,reading:"Acts 1",topic:"The Ascension & the Wait",topic_es:"La Ascensión y la espera",topic_fr:"L’Ascension et l’attente",ph:1,
  summary:"Jesus gives final instructions, ascends to heaven, and the disciples wait in Jerusalem for the promised Holy Spirit. Matthias replaces Judas.",
  summary_es:"Jesús da instrucciones finales, asciende al cielo, y los discípulos esperan en Jerusalén la promesa del Espíritu Santo. Matías reemplaza a Judas.",
  summary_fr:"Jésus donne les dernières instructions, monte au ciel, et les disciples attendent à Jérusalem la promesse du Saint-Esprit. Matthias remplace Judas."},
{day:2,reading:"Acts 2",topic:"Pentecost & the First Church",topic_es:"Pentecostés y la primera iglesia",topic_fr:"La Pentecôte et la première Église",
  summary:"The Holy Spirit falls at Pentecost. Peter preaches and 3,000 are saved. The first church is born — devoted to teaching, fellowship, breaking of bread, and prayer.",
  summary_es:"El Espíritu Santo desciende en Pentecostés. Pedro predica y 3.000 son salvos. Nace la primera iglesia — dedicada a la enseñanza, la comunión, el partimiento del pan y la oración.",
  summary_fr:"Le Saint-Esprit descend à la Pentecôte. Pierre prêche et 3 000 sont sauvés. La première Église naît — persévérant dans l’enseignement, la communion, la fraction du pain et la prière."},
{day:3,reading:"Acts 3",topic:"Healing at the Temple Gate",topic_es:"Sanidad a la puerta del templo",topic_fr:"Guérison à la porte du temple",
  summary:"Peter heals a lame man at the Beautiful Gate and preaches to the crowd, pointing them to Jesus as the author of life.",
  summary_es:"Pedro sana a un cojo en la Puerta la Hermosa y predica a la multitud, señalándoles a Jesús como el autor de la vida.",
  summary_fr:"Pierre guérit un boiteux à la Belle Porte et prêche à la foule, leur montrant Jésus comme le Prince de la vie."},
{day:4,reading:"Acts 4",topic:"Boldness Before the Council",topic_es:"Audacia ante el concilio",topic_fr:"Hardiesse devant le sanhédrin",
  summary:"Peter and John are arrested and brought before the Sanhedrin. Filled with the Spirit, they speak boldly. The believers pray for courage and share everything.",
  summary_es:"Pedro y Juan son arrestados y llevados ante el Sanedrín. Llenos del Espíritu, hablan con denuedo. Los creyentes oran por valor y comparten todo.",
  summary_fr:"Pierre et Jean sont arrêtés et conduits devant le sanhédrin. Remplis de l’Esprit, ils parlent avec hardiesse. Les croyants prient pour le courage et partagent tout."},
{day:5,reading:"Acts 5",topic:"Ananias & Sapphira, Apostles Arrested",topic_es:"Ananías y Safira, los apóstoles arrestados",topic_fr:"Ananias et Saphira, les apôtres arrêtés",
  summary:"God judges Ananias and Sapphira for lying to the Holy Spirit. The apostles perform signs, are arrested, beaten, and rejoice that they were counted worthy to suffer.",
  summary_es:"Dios juzga a Ananías y Safira por mentir al Espíritu Santo. Los apóstoles hacen señales, son arrestados, azotados y se gozan de haber sido tenidos por dignos de sufrir.",
  summary_fr:"Dieu juge Ananias et Saphira pour avoir menti au Saint-Esprit. Les apôtres opèrent des signes, sont arrêtés, battus et se réjouissent d’avoir été jugés dignes de souffrir."},
{day:6,reading:"Acts 6",topic:"The Seven Chosen, Stephen’s Ministry",topic_es:"Los siete escogidos, el ministerio de Esteban",topic_fr:"Le choix des sept, le ministère d’Étienne",
  summary:"The church appoints seven men to serve. Stephen, full of grace and power, performs wonders and is accused before the council.",
  summary_es:"La iglesia designa a siete hombres para servir. Esteban, lleno de gracia y poder, hace prodigios y es acusado ante el concilio.",
  summary_fr:"L’Église choisit sept hommes pour servir. Étienne, plein de grâce et de puissance, fait des prodiges et est traduit devant le sanhédrin."},
{day:7,reading:"Acts 7",topic:"Stephen’s Speech & Martyrdom",topic_es:"El discurso de Esteban y su martirio",topic_fr:"Le discours d’Étienne et son martyre",
  summary:"Stephen delivers a sweeping history of Israel’s rebellion, calls out the council, and becomes the first Christian martyr — forgiving his killers as he dies.",
  summary_es:"Esteban presenta una amplia historia de la rebelión de Israel, increpa al concilio y se convierte en el primer mártir cristiano — perdonando a sus asesinos al morir.",
  summary_fr:"Étienne dresse une vaste histoire de la rébellion d’Israël, dénonce le sanhédrin et devient le premier martyr chrétien — pardonnant à ceux qui le tuent en mourant."},
{day:8,reading:"Acts 8",topic:"The Gospel Spreads to Samaria & Ethiopia",topic_es:"El evangelio se extiende a Samaria y Etiopía",topic_fr:"L’Évangile s’étend à la Samarie et à l’Éthiopie",ph:2,
  summary:"Persecution scatters the church. Philip preaches in Samaria and baptizes the Ethiopian eunuch. The gospel begins to move beyond Jerusalem.",
  summary_es:"La persecución dispersa a la iglesia. Felipe predica en Samaria y bautiza al eunuco etíope. El evangelio empieza a salir más allá de Jerusalén.",
  summary_fr:"La persécution disperse l’Église. Philippe prêche en Samarie et baptise l’eunuque éthiopien. L’Évangile commence à sortir au-delà de Jérusalem."},
{day:9,reading:"Acts 9",topic:"Saul’s Conversion",topic_es:"La conversión de Saulo",topic_fr:"La conversion de Saul",
  summary:"Saul meets the risen Christ on the road to Damascus and is radically converted. The persecutor becomes a preacher. Ananias baptizes him.",
  summary_es:"Saulo encuentra al Cristo resucitado camino a Damasco y se convierte radicalmente. El perseguidor se vuelve predicador. Ananías lo bautiza.",
  summary_fr:"Saul rencontre le Christ ressuscité sur le chemin de Damas et est radicalement converti. Le persécuteur devient prédicateur. Ananias le baptise."},
{day:10,reading:"Acts 10",topic:"Peter & Cornelius — Gospel to the Gentiles",topic_es:"Pedro y Cornelio — el evangelio a los gentiles",topic_fr:"Pierre et Corneille — l’Évangile aux païens",
  summary:"God gives Peter a vision and sends him to Cornelius, a Roman centurion. The Holy Spirit falls on Gentiles for the first time. No one is unclean.",
  summary_es:"Dios da a Pedro una visión y lo envía a Cornelio, un centurión romano. El Espíritu Santo desciende sobre los gentiles por primera vez. Nadie es inmundo.",
  summary_fr:"Dieu donne à Pierre une vision et l’envoie chez Corneille, un centurion romain. Le Saint-Esprit tombe sur les païens pour la première fois. Personne n’est impur."},
{day:11,reading:"Acts 11",topic:"The Church Accepts the Gentiles",topic_es:"La iglesia acepta a los gentiles",topic_fr:"L’Église accueille les païens",
  summary:"Peter defends his visit to Cornelius. The church in Antioch is established — where believers are first called Christians.",
  summary_es:"Pedro defiende su visita a Cornelio. Se establece la iglesia en Antioquía — donde por primera vez los creyentes son llamados cristianos.",
  summary_fr:"Pierre défend sa visite à Corneille. L’Église d’Antioche est fondée — où les croyants sont pour la première fois appelés chrétiens."},
{day:12,reading:"Acts 12",topic:"James Killed, Peter Rescued",topic_es:"Jacobo muerto, Pedro liberado",topic_fr:"Jacques mis à mort, Pierre délivré",
  summary:"Herod kills James and imprisons Peter. An angel rescues Peter in the night. Herod is struck down by God for accepting worship.",
  summary_es:"Herodes mata a Jacobo y encarcela a Pedro. Un ángel libera a Pedro en la noche. Herodes es herido por Dios por aceptar adoración.",
  summary_fr:"Hérode tue Jacques et emprisonne Pierre. Un ange délivre Pierre dans la nuit. Hérode est frappé par Dieu pour avoir accepté l’adoration."},
{day:13,reading:"Acts 13",topic:"Paul’s First Missionary Journey Begins",topic_es:"Comienza el primer viaje misionero de Pablo",topic_fr:"Le premier voyage missionnaire de Paul commence",
  summary:"The church in Antioch sends Barnabas and Saul. Paul preaches in the synagogue at Pisidian Antioch, declaring justification by faith in Christ.",
  summary_es:"La iglesia de Antioquía envía a Bernabé y Saulo. Pablo predica en la sinagoga de Antioquía de Pisidia, declarando la justificación por la fe en Cristo.",
  summary_fr:"L’Église d’Antioche envoie Barnabas et Saul. Paul prêche à la synagogue d’Antioche de Pisidie, proclamant la justification par la foi en Christ."},
{day:14,reading:"Acts 14",topic:"Iconium, Lystra, Derbe",topic_es:"Iconio, Listra, Derbe",topic_fr:"Iconium, Lystre, Derbe",
  summary:"Paul and Barnabas preach, are mistaken for gods in Lystra, then Paul is stoned and left for dead. He gets up and keeps going.",
  summary_es:"Pablo y Bernabé predican, son tomados por dioses en Listra, y luego Pablo es apedreado y dado por muerto. Se levanta y sigue adelante.",
  summary_fr:"Paul et Barnabas prêchent, sont pris pour des dieux à Lystre, puis Paul est lapidé et laissé pour mort. Il se relève et poursuit."},
{day:15,reading:"Acts 15",topic:"The Jerusalem Council",topic_es:"El Concilio de Jerusalén",topic_fr:"Le concile de Jérusalem",ph:3,
  summary:"The church gathers to settle whether Gentiles must follow the Law. James declares: God makes no distinction. Salvation is by grace through faith.",
  summary_es:"La iglesia se reúne para decidir si los gentiles deben seguir la Ley. Jacobo declara: Dios no hace distinción. La salvación es por gracia mediante la fe.",
  summary_fr:"L’Église se réunit pour trancher si les païens doivent suivre la Loi. Jacques déclare : Dieu ne fait pas de distinction. Le salut est par grâce, au moyen de la foi."},
{day:16,reading:"Acts 16",topic:"Philippi & the Jailer",topic_es:"Filipos y el carcelero",topic_fr:"Philippes et le geôlier",
  summary:"Paul recruits Timothy, receives the Macedonian call, and travels to Philippi. Lydia believes. Paul and Silas sing in prison; the jailer is saved.",
  summary_es:"Pablo recluta a Timoteo, recibe el llamado a Macedonia y viaja a Filipos. Lidia cree. Pablo y Silas cantan en la cárcel; el carcelero es salvo.",
  summary_fr:"Paul s’adjoint Timothée, reçoit l’appel de la Macédoine et se rend à Philippes. Lydie croit. Paul et Silas chantent en prison ; le geôlier est sauvé."},
{day:17,reading:"Acts 17",topic:"Thessalonica, Berea, Athens",topic_es:"Tesalónica, Berea, Atenas",topic_fr:"Thessalonique, Bérée, Athènes",
  summary:"Paul reasons from Scripture in Thessalonica and Berea. In Athens he preaches on Mars Hill: ‘The God who made the world does not live in temples made by hands.’",
  summary_es:"Pablo razona desde las Escrituras en Tesalónica y Berea. En Atenas predica en el Areópago: ‘El Dios que hizo el mundo no habita en templos hechos por manos humanas.’",
  summary_fr:"Paul raisonne d’après les Écritures à Thessalonique et à Bérée. À Athènes, il prêche à l’Aréopage : ‘Le Dieu qui a fait le monde n’habite pas dans des temples faits de main d’homme.’"},
{day:18,reading:"Acts 18",topic:"Corinth & Aquila and Priscilla",topic_es:"Corinto y Aquila y Priscila",topic_fr:"Corinthe et Aquilas et Priscille",
  summary:"Paul stays in Corinth for 18 months, making tents and preaching. The Lord tells him: ‘Do not be afraid. I have many people in this city.’",
  summary_es:"Pablo se queda en Corinto 18 meses, haciendo tiendas y predicando. El Señor le dice: ‘No temas. Tengo mucho pueblo en esta ciudad.’",
  summary_fr:"Paul demeure 18 mois à Corinthe, fabriquant des tentes et prêchant. Le Seigneur lui dit : ‘Ne crains rien. J’ai un peuple nombreux dans cette ville.’"},
{day:19,reading:"Acts 19",topic:"Ephesus & the Riot",topic_es:"Éfeso y el alboroto",topic_fr:"Éphèse et l’émeute",
  summary:"Paul ministers powerfully in Ephesus for two years. A silversmith named Demetrius incites a riot because the gospel is threatening their idol business.",
  summary_es:"Pablo ministra con poder en Éfeso por dos años. Un platero llamado Demetrio incita un alboroto porque el evangelio amenaza su negocio de ídolos.",
  summary_fr:"Paul exerce un ministère puissant à Éphèse pendant deux ans. Un orfèvre nommé Démétrius soulève une émeute, car l’Évangile menace son commerce d’idoles."},
{day:20,reading:"Acts 20",topic:"Farewell to the Ephesian Elders",topic_es:"Despedida de los ancianos de Éfeso",topic_fr:"Adieux aux anciens d’Éphèse",
  summary:"Paul raises Eutychus, then gives a tearful farewell to the Ephesian elders at Miletus: ‘I did not shrink from declaring to you the whole counsel of God.’",
  summary_es:"Pablo resucita a Eutico y luego da una despedida con lágrimas a los ancianos de Éfeso en Mileto: ‘No he rehuido anunciaros todo el consejo de Dios.’",
  summary_fr:"Paul ressuscite Eutychus, puis fait des adieux émus aux anciens d’Éphèse à Milet : ‘Je n’ai rien caché de tout le dessein de Dieu.’"},
{day:21,reading:"Acts 21",topic:"Paul Arrives in Jerusalem",topic_es:"Pablo llega a Jerusalén",topic_fr:"Paul arrive à Jérusalem",
  summary:"Paul is warned not to go to Jerusalem but presses on. He is seized in the temple and arrested by Roman soldiers.",
  summary_es:"Pablo es advertido de no ir a Jerusalén, pero sigue adelante. Es capturado en el templo y arrestado por soldados romanos.",
  summary_fr:"Paul est averti de ne pas monter à Jérusalem mais il avance. Il est saisi dans le temple et arrêté par des soldats romains."},
{day:22,reading:"Acts 22",topic:"Paul’s Defense Before the Crowd",topic_es:"La defensa de Pablo ante la multitud",topic_fr:"La défense de Paul devant la foule",ph:4,
  summary:"Paul recounts his conversion on the Damascus road to the angry Jerusalem mob. When he mentions the Gentiles, they erupt.",
  summary_es:"Pablo relata su conversión en el camino de Damasco a la turba airada de Jerusalén. Cuando menciona a los gentiles, estallan.",
  summary_fr:"Paul raconte sa conversion sur le chemin de Damas à la foule en colère de Jérusalem. Quand il mentionne les païens, elle éclate."},
{day:23,reading:"Acts 23",topic:"The Plot Against Paul",topic_es:"El complot contra Pablo",topic_fr:"Le complot contre Paul",
  summary:"Paul stands before the Sanhedrin and divides the Pharisees and Sadducees. A conspiracy to kill him is uncovered, and he is transferred to Caesarea.",
  summary_es:"Pablo comparece ante el Sanedrín y divide a los fariseos y saduceos. Se descubre una conspiración para matarlo y es trasladado a Cesarea.",
  summary_fr:"Paul comparaît devant le sanhédrin et divise pharisiens et sadducéens. Un complot pour le tuer est découvert, et il est transféré à Césarée."},
{day:24,reading:"Acts 24",topic:"Paul Before Felix",topic_es:"Pablo ante Félix",topic_fr:"Paul devant Félix",
  summary:"Paul defends himself before Governor Felix, who is convicted but delays: ‘When I get an opportunity I will summon you.’ He leaves Paul in prison for two years.",
  summary_es:"Pablo se defiende ante el gobernador Félix, quien es convicto pero pospone: ‘Cuando tenga oportunidad, te llamaré.’ Deja a Pablo preso dos años.",
  summary_fr:"Paul se défend devant le gouverneur Félix, qui est convaincu mais diffère : ‘Quand j’en aurai l’occasion, je te rappellerai.’ Il laisse Paul en prison deux ans."},
{day:25,reading:"Acts 25",topic:"Paul Appeals to Caesar",topic_es:"Pablo apela al César",topic_fr:"Paul fait appel à César",
  summary:"Festus takes over from Felix. Paul, unwilling to be tried in Jerusalem, exercises his right as a Roman citizen: ‘I appeal to Caesar.’",
  summary_es:"Festo sucede a Félix. Pablo, no queriendo ser juzgado en Jerusalén, ejerce su derecho de ciudadano romano: ‘Apelo al César.’",
  summary_fr:"Festus succède à Félix. Paul, refusant d’être jugé à Jérusalem, fait valoir son droit de citoyen romain : ‘J’en appelle à César.’"},
{day:26,reading:"Acts 26",topic:"Paul Before Agrippa",topic_es:"Pablo ante Agripa",topic_fr:"Paul devant Agrippa",
  summary:"Paul gives his most eloquent defense before King Agrippa, who responds: ‘In a short time would you persuade me to be a Christian?’",
  summary_es:"Pablo presenta su defensa más elocuente ante el rey Agripa, quien responde: ‘Por poco me persuades a ser cristiano.’",
  summary_fr:"Paul fait sa défense la plus éloquente devant le roi Agrippa, qui répond : ‘Tu vas bientôt me persuader de devenir chrétien !’"},
{day:27,reading:"Acts 27",topic:"The Shipwreck",topic_es:"El naufragio",topic_fr:"Le naufrage",
  summary:"Paul sails for Rome. A violent storm batters the ship for two weeks. Paul encourages the crew: ‘Take heart, men. Not one of you will be lost.’ They shipwreck on Malta.",
  summary_es:"Pablo zarpa hacia Roma. Una tormenta violenta sacude el barco dos semanas. Pablo anima a la tripulación: ‘Tened buen ánimo. Ninguno de vosotros se perderá.’ Naufragan en Malta.",
  summary_fr:"Paul s’embarque pour Rome. Une violente tempête malmène le navire pendant deux semaines. Paul encourage l’équipage : ‘Prenez courage. Aucun de vous ne périra.’ Ils font naufrage à Malte."},
{day:28,reading:"Acts 28",topic:"Rome at Last",topic_es:"Por fin Roma",topic_fr:"Enfin Rome",
  summary:"Paul arrives in Rome, heals the sick on Malta, and spends two years under house arrest — preaching the kingdom of God and teaching about Jesus with all boldness.",
  summary_es:"Pablo llega a Roma, sana enfermos en Malta y pasa dos años bajo arresto domiciliario — predicando el reino de Dios y enseñando acerca de Jesús con toda confianza.",
  summary_fr:"Paul arrive à Rome, guérit des malades à Malte et passe deux ans en résidence surveillée — prêchant le royaume de Dieu et enseignant ce qui concerne Jésus avec toute hardiesse."},
{day:29,reading:"Acts 1–14",topic:"Full Re-Read: Part 1",topic_es:"Relectura completa: Parte 1",topic_fr:"Relecture intégrale : Partie 1",
  summary:"Review the first half of Acts — from the birth of the church at Pentecost through Paul’s first missionary journey. See how far the gospel has traveled.",
  summary_es:"Repasa la primera mitad de Hechos — desde el nacimiento de la iglesia en Pentecostés hasta el primer viaje misionero de Pablo. Mira hasta dónde ha llegado el evangelio.",
  summary_fr:"Revois la première moitié des Actes — de la naissance de l’Église à la Pentecôte au premier voyage missionnaire de Paul. Vois jusqu’où l’Évangile est parvenu."},
{day:30,reading:"Acts 15–28",topic:"Full Re-Read: Part 2",topic_es:"Relectura completa: Parte 2",topic_fr:"Relecture intégrale : Partie 2",
  summary:"Review the second half — from the Jerusalem Council through Paul’s arrival in Rome. The gospel has gone from Jerusalem to the ends of the earth.",
  summary_es:"Repasa la segunda mitad — desde el Concilio de Jerusalén hasta la llegada de Pablo a Roma. El evangelio ha ido desde Jerusalén hasta los confines de la tierra.",
  summary_fr:"Revois la seconde moitié — du concile de Jérusalem à l’arrivée de Paul à Rome. L’Évangile est allé de Jérusalem jusqu’aux extrémités de la terre."}
],
  verses: {
1:{r:"Acts 2:11",r_es:"Hechos 2:11",r_fr:"Actes 2:11",
  t:"...we hear them telling in our own tongues the mighty works of God.",
  t_es:"...les oímos hablar en nuestras lenguas las maravillas de Dios.",
  t_fr:"...nous les entendons parler dans nos langues des merveilles de Dieu."},
8:{r:"Acts 9:25",r_es:"Hechos 9:25",r_fr:"Actes 9:25",
  t:"But Saul increased all the more in strength, and confounded the Jews who lived in Damascus by proving that Jesus was the Christ.",
  t_es:"Pero Saulo mucho más se esforzaba, y confundía a los judíos que moraban en Damasco, demostrando que Jesús era el Cristo.",
  t_fr:"Cependant Saul se fortifiait de plus en plus, et il confondait les Juifs qui habitaient Damas, démontrant que Jésus est le Christ."},
15:{r:"Acts 14:11",r_es:"Hechos 14:11",r_fr:"Actes 14:11",
  t:"Men, why are you doing these things? We also are men, of like nature with you, and we bring you good news, that you should turn from these vain things to a living God.",
  t_es:"Varones, ¿por qué hacéis esto? Nosotros también somos hombres semejantes a vosotros, que os anunciamos que de estas vanidades os convirtáis al Dios vivo.",
  t_fr:"Ô hommes, pourquoi agissez-vous de la sorte ? Nous aussi, nous sommes des hommes de la même nature que vous ; et, vous apportant une bonne nouvelle, nous vous exhortons à renoncer à ces choses vaines, pour vous tourner vers le Dieu vivant."},
22:{r:"Acts 19:10",r_es:"Hechos 19:10",r_fr:"Actes 19:10",
  t:"This continued for two years, so that all the residents of Asia heard the word of the Lord, both Jews and Greeks.",
  t_es:"Así continuó por espacio de dos años, de manera que todos los que habitaban en Asia, judíos y griegos, oyeron la palabra del Señor Jesús.",
  t_fr:"Cela dura deux ans, de sorte que tous ceux qui habitaient l’Asie, Juifs et Grecs, entendirent la parole du Seigneur."}
},
  checks: [
  {k:"read",l:"Read the passage",l_es:"Lee el pasaje",l_fr:"Lis le passage"},
  {k:"pray",l:"Pray & journal",l_es:"Ora y escribe en tu diario",l_fr:"Prie et tiens un journal"},
  {k:"workout",l:"Workout (3–5x this week)",l_es:"Entrena (3–5x esta semana)",l_fr:"Entraîne-toi (3–5x cette semaine)"},
  {k:"abstain",l:"Abstain from your one thing",l_es:"Abstente de aquello que decidiste",l_fr:"Abstiens-toi de la chose que tu as choisie"},
  {k:"marco",l:"Marco Polo update",l_es:"Mensaje en Marco Polo",l_fr:"Mise à jour Marco Polo"}
]
};
