// Iron Sharpens Iron v2.2.0 — Gospel of Matthew Config (en/es/fr)
window.PLAN = {
  title: "Gospel of Matthew",
  title_es: "Evangelio de Mateo",
  title_fr: "Évangile de Matthieu",
  subtitle: "GOSPEL OF MATTHEW — 30-DAY CHALLENGE",
  subtitle_es: "EVANGELIO DE MATEO — RETO DE 30 DÍAS",
  subtitle_fr: "ÉVANGILE DE MATTHIEU — DÉFI DE 30 JOURS",
  storageKey: "isi-matthew-v2",
  totalDays: 30,
  days: [
{day:1,reading:"Matthew 1",topic:"The Genealogy & Birth of Jesus",topic_es:"La genealogía y el nacimiento de Jesús",topic_fr:"La généalogie et la naissance de Jésus",ph:1,
  summary:"The King’s lineage from Abraham through David to Joseph. An angel tells Joseph: ‘She will bear a son, and you shall call His name Jesus, for He will save His people from their sins.’",
  summary_es:"El linaje del Rey desde Abraham, pasando por David, hasta José. Un ángel le dice a José: ‘Dará a luz un hijo, y llamarás su nombre Jesús, porque él salvará a su pueblo de sus pecados.’",
  summary_fr:"La lignée du Roi depuis Abraham, par David, jusqu’à Joseph. Un ange dit à Joseph : ‘Elle enfantera un fils, et tu lui donneras le nom de Jésus ; car c’est lui qui sauvera son peuple de ses péchés.’"},
{day:2,reading:"Matthew 2",topic:"Wise Men & Flight to Egypt",topic_es:"Los magos y la huida a Egipto",topic_fr:"Les mages et la fuite en Égypte",
  summary:"The Magi follow the star and worship the newborn King. Herod slaughters the innocents. Joseph flees to Egypt and later settles in Nazareth.",
  summary_es:"Los magos siguen la estrella y adoran al Rey recién nacido. Herodes mata a los inocentes. José huye a Egipto y luego se establece en Nazaret.",
  summary_fr:"Les mages suivent l’étoile et adorent le Roi nouveau-né. Hérode massacre les innocents. Joseph fuit en Égypte, puis s’établit à Nazareth."},
{day:3,reading:"Matthew 3",topic:"John the Baptist & Jesus’ Baptism",topic_es:"Juan el Bautista y el bautismo de Jesús",topic_fr:"Jean-Baptiste et le baptême de Jésus",
  summary:"John preaches repentance in the wilderness. Jesus is baptized in the Jordan. The heavens open: ‘This is my beloved Son, with whom I am well pleased.’",
  summary_es:"Juan predica el arrepentimiento en el desierto. Jesús es bautizado en el Jordán. Los cielos se abren: ‘Este es mi Hijo amado, en quien tengo complacencia.’",
  summary_fr:"Jean prêche la repentance au désert. Jésus est baptisé dans le Jourdain. Les cieux s’ouvrent : ‘Celui-ci est mon Fils bien-aimé, en qui j’ai mis toute mon affection.’"},
{day:4,reading:"Matthew 4",topic:"Temptation & First Disciples",topic_es:"La tentación y los primeros discípulos",topic_fr:"La tentation et les premiers disciples",
  summary:"Jesus is tempted by Satan in the wilderness and overcomes with Scripture. He begins His ministry in Galilee and calls Peter, Andrew, James, and John.",
  summary_es:"Jesús es tentado por Satanás en el desierto y vence con la Escritura. Comienza su ministerio en Galilea y llama a Pedro, Andrés, Jacobo y Juan.",
  summary_fr:"Jésus est tenté par Satan au désert et triomphe par l’Écriture. Il commence son ministère en Galilée et appelle Pierre, André, Jacques et Jean."},
{day:5,reading:"Matthew 5",topic:"Sermon on the Mount: The Beatitudes",topic_es:"Sermón del Monte: las Bienaventuranzas",topic_fr:"Sermon sur la montagne : les Béatitudes",
  summary:"Jesus redefines blessedness. Salt and light. The higher standard of the Kingdom: anger is murder, lust is adultery. Love your enemies.",
  summary_es:"Jesús redefine la bienaventuranza. Sal y luz. El estándar más alto del Reino: la ira es homicidio, la concupiscencia es adulterio. Amad a vuestros enemigos.",
  summary_fr:"Jésus redéfinit le bonheur. Sel et lumière. L’exigence supérieure du Royaume : la colère est meurtre, la convoitise est adultère. Aimez vos ennemis."},
{day:6,reading:"Matthew 6",topic:"Prayer, Fasting & Anxiety",topic_es:"Oración, ayuno y ansiedad",topic_fr:"Prière, jeûne et anxiété",
  summary:"Jesus teaches the Lord’s Prayer, warns against showy religion, and commands: ‘Seek first the kingdom of God and His righteousness, and all these things will be added to you.’",
  summary_es:"Jesús enseña el Padre Nuestro, advierte contra la religión ostentosa y manda: ‘Buscad primeramente el reino de Dios y su justicia, y todas estas cosas os serán añadidas.’",
  summary_fr:"Jésus enseigne le Notre Père, met en garde contre la piété ostentatoire et commande : ‘Cherchez premièrement le royaume et la justice de Dieu ; et toutes ces choses vous seront données par-dessus.’"},
{day:7,reading:"Matthew 7",topic:"Judging, the Narrow Gate, Two Builders",topic_es:"Juzgar, la puerta estrecha y los dos constructores",topic_fr:"Juger, la porte étroite et les deux bâtisseurs",
  summary:"Don’t judge hypocritically. Enter through the narrow gate. By their fruits you will know them. The wise man builds his house on the rock.",
  summary_es:"No juzguéis con hipocresía. Entrad por la puerta estrecha. Por sus frutos los conoceréis. El sabio edifica su casa sobre la roca.",
  summary_fr:"Ne jugez pas avec hypocrisie. Entrez par la porte étroite. C’est à leurs fruits que vous les reconnaîtrez. L’homme sage bâtit sa maison sur le roc."},
{day:8,reading:"Matthew 8",topic:"Healings & the Cost of Following",topic_es:"Sanidades y el precio de seguirlo",topic_fr:"Guérisons et le prix de le suivre",ph:2,
  summary:"Jesus heals a leper, the centurion’s servant, Peter’s mother-in-law, and many others. He calms the storm. ‘Foxes have holes, but the Son of Man has nowhere to lay His head.’",
  summary_es:"Jesús sana a un leproso, al siervo del centurión, a la suegra de Pedro y a muchos otros. Calma la tempestad. ‘Las zorras tienen guaridas, pero el Hijo del Hombre no tiene dónde recostar su cabeza.’",
  summary_fr:"Jésus guérit un lépreux, le serviteur du centurion, la belle-mère de Pierre et beaucoup d’autres. Il calme la tempête. ‘Les renards ont des tanières, mais le Fils de l’homme n’a pas où reposer sa tête.’"},
{day:9,reading:"Matthew 9",topic:"More Healings & the Call of Matthew",topic_es:"Más sanidades y el llamado de Mateo",topic_fr:"D’autres guérisons et l’appel de Matthieu",
  summary:"Jesus heals the paralytic, calls Matthew from the tax booth, raises a girl from the dead. ‘The harvest is plentiful, but the laborers are few.’",
  summary_es:"Jesús sana al paralítico, llama a Mateo del banco de impuestos y resucita a una niña. ‘La mies es mucha, mas los obreros pocos.’",
  summary_fr:"Jésus guérit le paralytique, appelle Matthieu du bureau de péage et ressuscite une jeune fille. ‘La moisson est grande, mais il y a peu d’ouvriers.’"},
{day:10,reading:"Matthew 10",topic:"Sending Out the Twelve",topic_es:"Envío de los doce",topic_fr:"L’envoi des douze",
  summary:"Jesus sends His disciples with authority and warns them of persecution. ‘Be wise as serpents and innocent as doves.’ Don’t fear those who kill the body.",
  summary_es:"Jesús envía a sus discípulos con autoridad y les advierte de la persecución. ‘Sed prudentes como serpientes, y sencillos como palomas.’ No temáis a los que matan el cuerpo.",
  summary_fr:"Jésus envoie ses disciples avec autorité et les avertit de la persécution. ‘Soyez prudents comme les serpents, et simples comme les colombes.’ Ne craignez pas ceux qui tuent le corps."},
{day:11,reading:"Matthew 11",topic:"John’s Question & Jesus’ Invitation",topic_es:"La pregunta de Juan y la invitación de Jesús",topic_fr:"La question de Jean et l’invitation de Jésus",
  summary:"John the Baptist asks from prison: ‘Are you the one?’ Jesus responds with evidence. ‘Come to me, all who labor and are heavy laden, and I will give you rest.’",
  summary_es:"Juan el Bautista pregunta desde la cárcel: ‘¿Eres tú aquel?’ Jesús responde con evidencia. ‘Venid a mí todos los que estáis trabajados y cargados, y yo os haré descansar.’",
  summary_fr:"Jean-Baptiste demande de la prison : ‘Es-tu celui qui doit venir ?’ Jésus répond par les œuvres. ‘Venez à moi, vous tous qui êtes fatigués et chargés, et je vous donnerai du repos.’"},
{day:12,reading:"Matthew 12",topic:"Lord of the Sabbath & Blasphemy Warning",topic_es:"Señor del sábado y advertencia de blasfemia",topic_fr:"Seigneur du sabbat et avertissement de blasphème",
  summary:"Jesus is Lord of the Sabbath. He heals on the Sabbath and warns against blaspheming the Holy Spirit. ‘By your words you will be justified, and by your words condemned.’",
  summary_es:"Jesús es Señor del sábado. Sana en sábado y advierte contra la blasfemia contra el Espíritu Santo. ‘Por tus palabras serás justificado, y por tus palabras serás condenado.’",
  summary_fr:"Jésus est Maître du sabbat. Il guérit le jour du sabbat et avertit contre le blasphème contre le Saint-Esprit. ‘Par tes paroles tu seras justifié, et par tes paroles tu seras condamné.’"},
{day:13,reading:"Matthew 13",topic:"Parables of the Kingdom",topic_es:"Parábolas del Reino",topic_fr:"Paraboles du Royaume",
  summary:"The sower, the weeds, the mustard seed, the pearl of great price. Jesus teaches in parables — the Kingdom of Heaven is like nothing you’d expect.",
  summary_es:"El sembrador, la cizaña, la semilla de mostaza, la perla de gran precio. Jesús enseña en parábolas — el Reino de los cielos no se parece a nada que esperes.",
  summary_fr:"Le semeur, l’ivraie, le grain de moutarde, la perle de grand prix. Jésus enseigne en paraboles — le Royaume des cieux ne ressemble à rien de ce qu’on attend."},
{day:14,reading:"Matthew 14",topic:"John Beheaded & Feeding the 5,000",topic_es:"Decapitación de Juan y alimentación de los 5.000",topic_fr:"La décapitation de Jean et la multiplication des pains",
  summary:"Herod executes John the Baptist. Jesus feeds 5,000 with five loaves and two fish. He walks on water. Peter steps out in faith — and sinks.",
  summary_es:"Herodes ejecuta a Juan el Bautista. Jesús alimenta a 5.000 con cinco panes y dos peces. Camina sobre el agua. Pedro sale en fe — y se hunde.",
  summary_fr:"Hérode fait exécuter Jean-Baptiste. Jésus nourrit 5 000 personnes avec cinq pains et deux poissons. Il marche sur l’eau. Pierre s’élance avec foi — et coule."},
{day:15,reading:"Matthew 15",topic:"Clean & Unclean, Faith of a Canaanite Woman",topic_es:"Limpio e inmundo, la fe de la cananea",topic_fr:"Pur et impur, la foi de la Cananéenne",ph:3,
  summary:"Jesus confronts the Pharisees on traditions vs. God’s commands. What defiles comes from the heart. A Canaanite woman’s great faith moves Jesus to heal her daughter.",
  summary_es:"Jesús confronta a los fariseos sobre la tradición frente a los mandamientos de Dios. Lo que contamina sale del corazón. La gran fe de una cananea mueve a Jesús a sanar a su hija.",
  summary_fr:"Jésus confronte les pharisiens sur la tradition opposée aux commandements de Dieu. Ce qui souille vient du cœur. La grande foi d’une Cananéenne pousse Jésus à guérir sa fille."},
{day:16,reading:"Matthew 16",topic:"Peter’s Confession & the Cross Foretold",topic_es:"La confesión de Pedro y el anuncio de la cruz",topic_fr:"La confession de Pierre et l’annonce de la croix",
  summary:"‘Who do you say that I am?’ Peter: ‘You are the Christ, the Son of the living God.’ Jesus predicts His death: ‘If anyone would come after me, let him deny himself and take up his cross.’",
  summary_es:"‘¿Quién decís que soy yo?’ Pedro: ‘Tú eres el Cristo, el Hijo del Dios viviente.’ Jesús anuncia su muerte: ‘Si alguno quiere venir en pos de mí, niéguese a sí mismo, y tome su cruz.’",
  summary_fr:"‘Qui dites-vous que je suis ?’ Pierre : ‘Tu es le Christ, le Fils du Dieu vivant.’ Jésus annonce sa mort : ‘Si quelqu’un veut venir après moi, qu’il renonce à lui-même, qu’il se charge de sa croix.’"},
{day:17,reading:"Matthew 17",topic:"The Transfiguration",topic_es:"La Transfiguración",topic_fr:"La Transfiguration",
  summary:"Jesus is transfigured on the mountain before Peter, James, and John. Moses and Elijah appear. The Father speaks: ‘This is my beloved Son — listen to Him.’",
  summary_es:"Jesús es transfigurado en el monte ante Pedro, Jacobo y Juan. Aparecen Moisés y Elías. El Padre habla: ‘Este es mi Hijo amado — a él oíd.’",
  summary_fr:"Jésus est transfiguré sur la montagne devant Pierre, Jacques et Jean. Moïse et Élie apparaissent. Le Père parle : ‘Celui-ci est mon Fils bien-aimé — écoutez-le.’"},
{day:18,reading:"Matthew 18",topic:"Humility, Forgiveness & the Lost Sheep",topic_es:"Humildad, perdón y la oveja perdida",topic_fr:"Humilité, pardon et la brebis perdue",
  summary:"Unless you become like children, you will not enter the Kingdom. The parable of the lost sheep. Forgive seventy times seven. The unmerciful servant.",
  summary_es:"Si no os hacéis como niños, no entraréis en el Reino. La parábola de la oveja perdida. Perdonad setenta veces siete. El siervo malvado.",
  summary_fr:"Si vous ne devenez comme les petits enfants, vous n’entrerez pas dans le Royaume. La parabole de la brebis perdue. Pardonner soixante-dix fois sept fois. Le serviteur impitoyable."},
{day:19,reading:"Matthew 19",topic:"Marriage, Riches & Rewards",topic_es:"Matrimonio, riquezas y recompensas",topic_fr:"Mariage, richesses et récompenses",
  summary:"Jesus teaches on divorce, blesses the children, and confronts the rich young ruler. ‘With man this is impossible, but with God all things are possible.’",
  summary_es:"Jesús enseña sobre el divorcio, bendice a los niños y confronta al joven rico. ‘Para los hombres esto es imposible; mas para Dios todo es posible.’",
  summary_fr:"Jésus enseigne sur le divorce, bénit les petits enfants et confronte le jeune homme riche. ‘Aux hommes cela est impossible, mais à Dieu tout est possible.’"},
{day:20,reading:"Matthew 20",topic:"Workers in the Vineyard & Servant Leadership",topic_es:"Los obreros en la viña y el liderazgo de servicio",topic_fr:"Les ouvriers de la vigne et le leadership-serviteur",
  summary:"The last will be first. James and John’s mother asks for thrones. Jesus: ‘The Son of Man came not to be served but to serve, and to give His life as a ransom for many.’",
  summary_es:"Los últimos serán primeros. La madre de Jacobo y Juan pide tronos. Jesús: ‘El Hijo del Hombre no vino para ser servido, sino para servir, y para dar su vida en rescate por muchos.’",
  summary_fr:"Les derniers seront les premiers. La mère de Jacques et Jean demande des trônes. Jésus : ‘Le Fils de l’homme est venu, non pour être servi, mais pour servir et donner sa vie comme la rançon de plusieurs.’"},
{day:21,reading:"Matthew 21",topic:"Triumphal Entry & Temple Cleansing",topic_es:"Entrada Triunfal y purificación del templo",topic_fr:"Entrée triomphale et purification du temple",
  summary:"Jesus rides into Jerusalem on a donkey. The crowds shout Hosanna. He drives out the money changers and curses the fig tree. The religious leaders challenge His authority.",
  summary_es:"Jesús entra en Jerusalén sobre un asno. La multitud grita Hosanna. Echa a los cambistas y maldice la higuera. Los líderes religiosos cuestionan su autoridad.",
  summary_fr:"Jésus entre à Jérusalem sur un âne. La foule crie Hosanna. Il chasse les changeurs et maudit le figuier. Les chefs religieux contestent son autorité."},
{day:22,reading:"Matthew 22",topic:"Parables & the Greatest Commandment",topic_es:"Parábolas y el gran mandamiento",topic_fr:"Paraboles et le grand commandement",ph:4,
  summary:"The wedding banquet, paying taxes to Caesar, the Sadducees’ trap. The greatest commandment: love God with all your heart, and love your neighbor as yourself.",
  summary_es:"El banquete de bodas, pagar tributo al César, la trampa de los saduceos. El gran mandamiento: amar a Dios con todo el corazón y al prójimo como a uno mismo.",
  summary_fr:"Les noces, l’impôt à César, le piège des sadducéens. Le grand commandement : aimer Dieu de tout son cœur et son prochain comme soi-même."},
{day:23,reading:"Matthew 23",topic:"Seven Woes to the Pharisees",topic_es:"Siete ayes a los fariseos",topic_fr:"Sept malheurs aux pharisiens",
  summary:"Jesus unleashes seven woes against the scribes and Pharisees. Whitewashed tombs. ‘O Jerusalem, Jerusalem — how often I would have gathered your children together.’",
  summary_es:"Jesús desata siete ayes contra los escribas y fariseos. Sepulcros blanqueados. ‘¡Jerusalén, Jerusalén! ¡Cuántas veces quise juntar a tus hijos!’",
  summary_fr:"Jésus déchaîne sept malheurs contre les scribes et les pharisiens. Sépulcres blanchis. ‘Jérusalem, Jérusalem — combien de fois ai-je voulu rassembler tes enfants !’"},
{day:24,reading:"Matthew 24",topic:"Signs of the End",topic_es:"Señales del fin",topic_fr:"Les signes de la fin",
  summary:"The Olivet Discourse. Wars, famines, false prophets. ‘This gospel of the kingdom will be proclaimed throughout the whole world — and then the end will come.’ Stay ready.",
  summary_es:"El Discurso del Monte de los Olivos. Guerras, hambres, falsos profetas. ‘Este evangelio del reino será predicado en todo el mundo — y entonces vendrá el fin.’ Manténganse alerta.",
  summary_fr:"Le discours sur le mont des Oliviers. Guerres, famines, faux prophètes. ‘Cette bonne nouvelle du royaume sera prêchée dans le monde entier — alors viendra la fin.’ Tenez-vous prêts."},
{day:25,reading:"Matthew 25",topic:"Ten Virgins, Talents & the Sheep and Goats",topic_es:"Las diez vírgenes, los talentos y las ovejas y los cabritos",topic_fr:"Les dix vierges, les talents et les brebis et les boucs",
  summary:"Be prepared like the wise virgins. Invest what God gives you like the faithful servants. ‘Whatever you did for the least of these brothers of mine, you did for me.’",
  summary_es:"Estad preparados como las vírgenes prudentes. Invertid lo que Dios os da como los siervos fieles. ‘En cuanto lo hicisteis a uno de estos mis hermanos más pequeños, a mí lo hicisteis.’",
  summary_fr:"Soyez prêts comme les vierges sages. Faites fructifier ce que Dieu vous donne, comme les serviteurs fidèles. ‘Toutes les fois que vous avez fait ces choses à l’un de ces plus petits de mes frères, c’est à moi que vous les avez faites.’"},
{day:26,reading:"Matthew 26",topic:"Gethsemane, Betrayal & Trial",topic_es:"Getsemaní, traición y juicio",topic_fr:"Gethsémani, trahison et procès",
  summary:"The Last Supper. Jesus agonizes in Gethsemane: ‘Not my will, but yours.’ Judas betrays Him with a kiss. Peter denies Him three times. The Sanhedrin condemns Him.",
  summary_es:"La Última Cena. Jesús agoniza en Getsemaní: ‘No se haga mi voluntad, sino la tuya.’ Judas lo traiciona con un beso. Pedro lo niega tres veces. El Sanedrín lo condena.",
  summary_fr:"La Cène. Jésus agonise à Gethsémani : ‘Que ta volonté soit faite et non la mienne.’ Judas le trahit par un baiser. Pierre le renie trois fois. Le sanhédrin le condamne."},
{day:27,reading:"Matthew 27",topic:"The Crucifixion",topic_es:"La Crucifixión",topic_fr:"La Crucifixion",
  summary:"Pilate washes his hands. Jesus is mocked, beaten, and crucified. Darkness covers the land. ‘My God, my God, why have you forsaken me?’ The curtain is torn in two.",
  summary_es:"Pilato se lava las manos. Jesús es burlado, golpeado y crucificado. Las tinieblas cubren la tierra. ‘Dios mío, Dios mío, ¿por qué me has desamparado?’ El velo se rasga en dos.",
  summary_fr:"Pilate se lave les mains. Jésus est moqué, battu et crucifié. Les ténèbres couvrent le pays. ‘Mon Dieu, mon Dieu, pourquoi m’as-tu abandonné ?’ Le voile se déchire en deux."},
{day:28,reading:"Matthew 28",topic:"The Resurrection & Great Commission",topic_es:"La Resurrección y la Gran Comisión",topic_fr:"La Résurrection et la Grande Commission",
  summary:"The tomb is empty. Jesus is risen. He appears to the disciples and gives the Great Commission: ‘Go and make disciples of all nations — and I am with you always.’",
  summary_es:"La tumba está vacía. Jesús ha resucitado. Se aparece a los discípulos y da la Gran Comisión: ‘Id y haced discípulos a todas las naciones — y yo estoy con vosotros todos los días.’",
  summary_fr:"Le tombeau est vide. Jésus est ressuscité. Il apparaît aux disciples et donne la Grande Commission : ‘Allez, faites de toutes les nations des disciples — et je suis avec vous tous les jours.’"},
{day:29,reading:"Matthew 1–14",topic:"Full Re-Read: Part 1",topic_es:"Relectura completa: Parte 1",topic_fr:"Relecture intégrale : Partie 1",
  summary:"Review the first half of Matthew — from the King’s birth through the parables and miracles. The Kingdom has come near. See the whole arc.",
  summary_es:"Repasa la primera mitad de Mateo — desde el nacimiento del Rey hasta las parábolas y los milagros. El Reino se ha acercado. Mira todo el arco.",
  summary_fr:"Revois la première moitié de Matthieu — de la naissance du Roi aux paraboles et aux miracles. Le Royaume s’est approché. Vois tout l’arc."},
{day:30,reading:"Matthew 15–28",topic:"Full Re-Read: Part 2",topic_es:"Relectura completa: Parte 2",topic_fr:"Relecture intégrale : Partie 2",
  summary:"Review the second half — from Peter’s confession through the resurrection and Great Commission. The King suffers, dies, rises, and sends. Go.",
  summary_es:"Repasa la segunda mitad — desde la confesión de Pedro hasta la resurrección y la Gran Comisión. El Rey sufre, muere, resucita y envía. Id.",
  summary_fr:"Revois la seconde moitié — de la confession de Pierre à la résurrection et à la Grande Commission. Le Roi souffre, meurt, ressuscite et envoie. Allez."}
],
  verses: {
1:{r:"Matthew 1:21",r_es:"Mateo 1:21",r_fr:"Matthieu 1:21",
  t:"She will bear a son, and you shall call his name Jesus, for he will save his people from their sins.",
  t_es:"Y dará a luz un hijo, y llamarás su nombre JESÚS, porque él salvará a su pueblo de sus pecados.",
  t_fr:"Elle enfantera un fils, et tu lui donneras le nom de Jésus ; c’est lui qui sauvera son peuple de ses péchés."},
8:{r:"Matthew 6:33",r_es:"Mateo 6:33",r_fr:"Matthieu 6:33",
  t:"But seek first the kingdom of God and his righteousness, and all these things will be added to you.",
  t_es:"Mas buscad primeramente el reino de Dios y su justicia, y todas estas cosas os serán añadidas.",
  t_fr:"Cherchez premièrement le royaume et la justice de Dieu ; et toutes ces choses vous seront données par-dessus."},
15:{r:"Matthew 10:16",r_es:"Mateo 10:16",r_fr:"Matthieu 10:16",
  t:"Behold, I am sending you out as sheep in the midst of wolves, so be wise as serpents and innocent as doves.",
  t_es:"He aquí, yo os envío como a ovejas en medio de lobos; sed, pues, prudentes como serpientes, y sencillos como palomas.",
  t_fr:"Voici, je vous envoie comme des brebis au milieu des loups. Soyez donc prudents comme les serpents, et simples comme les colombes."},
22:{r:"Matthew 16:24",r_es:"Mateo 16:24",r_fr:"Matthieu 16:24",
  t:"Then Jesus told his disciples, ‘If anyone would come after me, let him deny himself and take up his cross and follow me.’",
  t_es:"Entonces Jesús dijo a sus discípulos: ‘Si alguno quiere venir en pos de mí, niéguese a sí mismo, y tome su cruz, y sígame.’",
  t_fr:"Alors Jésus dit à ses disciples : ‘Si quelqu’un veut venir après moi, qu’il renonce à lui-même, qu’il se charge de sa croix, et qu’il me suive.’"}
},
  checks: [
  {k:"read",l:"Read the passage",l_es:"Lee el pasaje",l_fr:"Lis le passage"},
  {k:"pray",l:"Pray & journal",l_es:"Ora y escribe en tu diario",l_fr:"Prie et tiens un journal"},
  {k:"workout",l:"Workout (3–5x/week)",l_es:"Entrena (3–5x por semana)",l_fr:"Entraîne-toi (3–5x par semaine)"},
  {k:"danger",l:"Stay Dangerous (1x/phase)",l_es:"Mantente peligroso (1x por fase)",l_fr:"Reste dangereux (1x par phase)"},
  {k:"abstain",l:"Abstain from your one thing",l_es:"Abstente de aquello que decidiste",l_fr:"Abstiens-toi de la chose que tu as choisie"},
  {k:"marco",l:"Marco Polo update",l_es:"Mensaje en Marco Polo",l_fr:"Mise à jour Marco Polo"}
]
};
