// Iron Sharpens Iron v2.2.0 — Gospel of Luke Config (en/es/fr)
window.PLAN = {
  title: "Gospel of Luke",
  title_es: "Evangelio de Lucas",
  title_fr: "Évangile de Luc",
  subtitle: "GOSPEL OF LUKE — 28-DAY CHALLENGE",
  subtitle_es: "EVANGELIO DE LUCAS — RETO DE 28 DÍAS",
  subtitle_fr: "ÉVANGILE DE LUC — DÉFI DE 28 JOURS",
  storageKey: "isi-luke-v2",
  totalDays: 28,
  days: [
{day:1,reading:"Luke 1",topic:"Announcements of John & Jesus",topic_es:"Anuncios de Juan y Jesús",topic_fr:"Annonces de Jean et de Jésus",ph:1,
  summary:"The angel Gabriel announces the birth of John the Baptist to Zechariah and the birth of Jesus to Mary. Mary’s Magnificat: ‘My soul magnifies the Lord.’",
  summary_es:"El ángel Gabriel anuncia el nacimiento de Juan el Bautista a Zacarías y el nacimiento de Jesús a María. El Magníficat de María: ‘Engrandece mi alma al Señor.’",
  summary_fr:"L’ange Gabriel annonce la naissance de Jean-Baptiste à Zacharie et la naissance de Jésus à Marie. Le Magnificat de Marie : ‘Mon âme exalte le Seigneur.’"},
{day:2,reading:"Luke 2",topic:"The Birth of Jesus",topic_es:"El nacimiento de Jesús",topic_fr:"La naissance de Jésus",
  summary:"Jesus is born in Bethlehem. Angels announce to shepherds. Simeon and Anna recognize the Messiah in the temple. The boy Jesus astounds the teachers at age twelve.",
  summary_es:"Jesús nace en Belén. Los ángeles anuncian a los pastores. Simeón y Ana reconocen al Mesías en el templo. El niño Jesús asombra a los maestros a los doce años.",
  summary_fr:"Jésus naît à Bethléhem. Les anges annoncent la nouvelle aux bergers. Siméon et Anne reconnaissent le Messie dans le temple. À douze ans, l’enfant Jésus étonne les docteurs."},
{day:3,reading:"Luke 3",topic:"John the Baptist & Jesus’ Baptism",topic_es:"Juan el Bautista y el bautismo de Jesús",topic_fr:"Jean-Baptiste et le baptême de Jésus",
  summary:"John preaches repentance and baptizes. Jesus is baptized and the Spirit descends. ‘You are my beloved Son; with you I am well pleased.’ Luke traces Jesus’ genealogy.",
  summary_es:"Juan predica el arrepentimiento y bautiza. Jesús es bautizado y desciende el Espíritu. ‘Tú eres mi Hijo amado; en ti tengo complacencia.’ Lucas traza la genealogía de Jesús.",
  summary_fr:"Jean prêche la repentance et baptise. Jésus est baptisé et l’Esprit descend. ‘Tu es mon Fils bien-aimé ; en toi j’ai mis toute mon affection.’ Luc retrace la généalogie de Jésus."},
{day:4,reading:"Luke 4",topic:"Temptation & Rejection at Nazareth",topic_es:"La tentación y el rechazo en Nazaret",topic_fr:"La tentation et le rejet à Nazareth",
  summary:"Jesus is tempted in the wilderness and overcomes with Scripture. He reads Isaiah in the Nazareth synagogue: ‘Today this Scripture has been fulfilled.’ They try to throw Him off a cliff.",
  summary_es:"Jesús es tentado en el desierto y vence con la Escritura. Lee a Isaías en la sinagoga de Nazaret: ‘Hoy se ha cumplido esta Escritura.’ Intentan despeñarlo.",
  summary_fr:"Jésus est tenté au désert et triomphe par l’Écriture. Il lit Ésaïe dans la synagogue de Nazareth : ‘Aujourd’hui cette Écriture est accomplie.’ Ils essaient de le précipiter du haut d’une falaise."},
{day:5,reading:"Luke 5",topic:"Calling the First Disciples",topic_es:"Llamado de los primeros discípulos",topic_fr:"L’appel des premiers disciples",
  summary:"The miraculous catch of fish. Peter falls at Jesus’ knees: ‘Depart from me, for I am a sinful man.’ Jesus heals a leper and a paralytic lowered through the roof.",
  summary_es:"La pesca milagrosa. Pedro cae a los pies de Jesús: ‘Apártate de mí, Señor, porque soy hombre pecador.’ Jesús sana a un leproso y a un paralítico que bajan por el techo.",
  summary_fr:"La pêche miraculeuse. Pierre se jette aux genoux de Jésus : ‘Retire-toi de moi, Seigneur, car je suis un homme pécheur.’ Jésus guérit un lépreux et un paralytique descendu par le toit."},
{day:6,reading:"Luke 6",topic:"Sermon on the Plain",topic_es:"El Sermón del llano",topic_fr:"Le sermon dans la plaine",
  summary:"Jesus chooses the twelve apostles. Blessed are the poor; woe to the rich. Love your enemies. Do not judge. Build your house on the rock.",
  summary_es:"Jesús elige a los doce apóstoles. Bienaventurados los pobres; ay de los ricos. Amad a vuestros enemigos. No juzguéis. Edifica tu casa sobre la roca.",
  summary_fr:"Jésus choisit les douze apôtres. Heureux les pauvres ; malheur aux riches. Aimez vos ennemis. Ne jugez pas. Bâtis ta maison sur le roc."},
{day:7,reading:"Luke 1–6",topic:"Phase 1 Re-Read",topic_es:"Relectura de la Fase 1",topic_fr:"Relecture de la phase 1",
  summary:"Re-read Luke 1–6. From the announcements to the Sermon on the Plain. Watch Luke’s emphasis on the poor, the outcast, and the power of the Spirit.",
  summary_es:"Relee Lucas 1–6. Desde los anuncios hasta el Sermón del llano. Observa el énfasis de Lucas en los pobres, los marginados y el poder del Espíritu.",
  summary_fr:"Relis Luc 1–6. Des annonces au sermon dans la plaine. Vois l’insistance de Luc sur les pauvres, les exclus et la puissance de l’Esprit."},
{day:8,reading:"Luke 7",topic:"Faith of the Centurion & a Sinful Woman",topic_es:"La fe del centurión y una mujer pecadora",topic_fr:"La foi du centurion et la femme pécheresse",ph:2,
  summary:"The centurion’s great faith astonishes Jesus. He raises a widow’s son from the dead. A sinful woman washes His feet with tears. ‘Her sins, which are many, are forgiven.’",
  summary_es:"La gran fe del centurión asombra a Jesús. Resucita al hijo de la viuda. Una mujer pecadora lava sus pies con lágrimas. ‘Sus muchos pecados le son perdonados.’",
  summary_fr:"La grande foi du centurion étonne Jésus. Il ressuscite le fils d’une veuve. Une femme pécheresse lave ses pieds de ses larmes. ‘Ses péchés, qui sont nombreux, lui sont pardonnés.’"},
{day:9,reading:"Luke 8",topic:"Parables & Power Over Nature",topic_es:"Parábolas y poder sobre la naturaleza",topic_fr:"Paraboles et pouvoir sur la nature",
  summary:"The parable of the sower. Jesus calms the storm, casts out Legion, heals the woman with bleeding, and raises Jairus’ daughter. ‘Who then is this?’",
  summary_es:"La parábola del sembrador. Jesús calma la tempestad, expulsa a Legión, sana a la mujer con flujo de sangre y resucita a la hija de Jairo. ‘¿Quién es este?’",
  summary_fr:"La parabole du semeur. Jésus calme la tempête, chasse Légion, guérit la femme malade depuis douze ans et ressuscite la fille de Jaïrus. ‘Qui donc est celui-ci ?’"},
{day:10,reading:"Luke 9",topic:"Sending the Twelve & the Transfiguration",topic_es:"El envío de los doce y la Transfiguración",topic_fr:"L’envoi des douze et la Transfiguration",
  summary:"Jesus sends the twelve, feeds 5,000. Peter confesses Christ. The Transfiguration. ‘If anyone would come after me, let him deny himself and take up his cross daily.’",
  summary_es:"Jesús envía a los doce, alimenta a 5.000. Pedro confiesa a Cristo. La Transfiguración. ‘Si alguno quiere venir en pos de mí, niéguese a sí mismo, tome su cruz cada día.’",
  summary_fr:"Jésus envoie les douze, nourrit 5 000 personnes. Pierre confesse le Christ. La Transfiguration. ‘Si quelqu’un veut venir après moi, qu’il renonce à lui-même, qu’il se charge chaque jour de sa croix.’"},
{day:11,reading:"Luke 10",topic:"The Good Samaritan & Mary and Martha",topic_es:"El Buen Samaritano, María y Marta",topic_fr:"Le Bon Samaritain, Marie et Marthe",
  summary:"Jesus sends seventy-two. The Good Samaritan redefines ‘neighbor.’ Martha is anxious; Mary chooses the better portion — sitting at Jesus’ feet.",
  summary_es:"Jesús envía a setenta y dos. El Buen Samaritano redefine ‘prójimo’. Marta se afana; María escoge la mejor parte — sentarse a los pies de Jesús.",
  summary_fr:"Jésus envoie soixante-douze. Le Bon Samaritain redéfinit ‘le prochain’. Marthe s’inquiète ; Marie a choisi la bonne part — s’asseoir aux pieds de Jésus."},
{day:12,reading:"Luke 11",topic:"Teaching on Prayer & Woes to the Pharisees",topic_es:"Enseñanza sobre la oración y ayes a los fariseos",topic_fr:"Enseignement sur la prière et malheurs aux pharisiens",
  summary:"Jesus teaches the Lord’s Prayer and persistence in asking. He casts out a demon and confronts the Pharisees: clean the inside of the cup first.",
  summary_es:"Jesús enseña el Padre Nuestro y la persistencia en pedir. Expulsa un demonio y confronta a los fariseos: limpiad primero lo de adentro del vaso.",
  summary_fr:"Jésus enseigne le Notre Père et la persévérance dans la demande. Il chasse un démon et confronte les pharisiens : nettoyez d’abord le dedans de la coupe."},
{day:13,reading:"Luke 12",topic:"Fear God, Not Man",topic_es:"Teme a Dios, no al hombre",topic_fr:"Crains Dieu, non l’homme",
  summary:"Beware of hypocrisy. Don’t fear those who kill the body. The parable of the rich fool. ‘Where your treasure is, there your heart will be also.’ Be ready.",
  summary_es:"Guardaos de la hipocresía. No temáis a los que matan el cuerpo. La parábola del rico insensato. ‘Donde está vuestro tesoro, allí estará también vuestro corazón.’ Estad preparados.",
  summary_fr:"Gardez-vous de l’hypocrisie. Ne craignez pas ceux qui tuent le corps. La parabole du riche insensé. ‘Là où est votre trésor, là aussi sera votre cœur.’ Tenez-vous prêts."},
{day:14,reading:"Luke 7–12",topic:"Phase 2 Re-Read",topic_es:"Relectura de la Fase 2",topic_fr:"Relecture de la phase 2",
  summary:"Re-read Luke 7–12. Miracles, parables, and growing opposition. Jesus is revealing who He is — and demanding a response.",
  summary_es:"Relee Lucas 7–12. Milagros, parábolas y creciente oposición. Jesús revela quién es — y exige una respuesta.",
  summary_fr:"Relis Luc 7–12. Miracles, paraboles et opposition croissante. Jésus révèle qui il est — et exige une réponse."},
{day:15,reading:"Luke 13",topic:"Repent or Perish",topic_es:"Arrepentíos o pereceréis",topic_fr:"Repentez-vous ou périssez",ph:3,
  summary:"Unless you repent, you will all likewise perish. The narrow door. Jesus weeps over Jerusalem: ‘How often would I have gathered your children together.’",
  summary_es:"Si no os arrepentís, todos pereceréis igualmente. La puerta angosta. Jesús llora sobre Jerusalén: ‘¡Cuántas veces quise juntar a tus hijos!’",
  summary_fr:"Si vous ne vous repentez, vous périrez tous également. La porte étroite. Jésus pleure sur Jérusalem : ‘Combien de fois ai-je voulu rassembler tes enfants !’"},
{day:16,reading:"Luke 14",topic:"The Cost of Discipleship",topic_es:"El precio del discipulado",topic_fr:"Le prix du disciple",
  summary:"Jesus heals on the Sabbath. The parable of the great banquet. ‘Whoever does not bear his own cross and come after me cannot be my disciple.’ Count the cost.",
  summary_es:"Jesús sana en sábado. La parábola del gran banquete. ‘El que no lleva su cruz y viene en pos de mí, no puede ser mi discípulo.’ Calcula el costo.",
  summary_fr:"Jésus guérit le jour du sabbat. La parabole du grand festin. ‘Quiconque ne porte pas sa croix et ne me suit pas ne peut être mon disciple.’ Calcule la dépense."},
{day:17,reading:"Luke 15",topic:"Lost Sheep, Lost Coin, Lost Son",topic_es:"La oveja perdida, la moneda perdida, el hijo perdido",topic_fr:"La brebis perdue, la pièce perdue, le fils perdu",
  summary:"Three parables of the lost. The shepherd leaves the ninety-nine. The woman searches for one coin. The father runs to embrace his prodigal son. Heaven rejoices over one sinner who repents.",
  summary_es:"Tres parábolas de lo perdido. El pastor deja las noventa y nueve. La mujer busca una moneda. El padre corre a abrazar al hijo pródigo. El cielo se alegra por un pecador que se arrepiente.",
  summary_fr:"Trois paraboles du perdu. Le berger laisse les quatre-vingt-dix-neuf. La femme cherche une pièce. Le père court embrasser son fils prodigue. Le ciel se réjouit pour un pécheur qui se repent."},
{day:18,reading:"Luke 16",topic:"The Shrewd Manager & the Rich Man and Lazarus",topic_es:"El mayordomo astuto y el rico y Lázaro",topic_fr:"L’économe rusé et l’homme riche et Lazare",
  summary:"Be faithful with little. You cannot serve God and money. The rich man in torment begs for a drop of water. A great chasm is fixed.",
  summary_es:"Sé fiel en lo poco. No podéis servir a Dios y a las riquezas. El rico en tormento ruega una gota de agua. Una gran sima ha sido fijada.",
  summary_fr:"Sois fidèle dans les petites choses. Vous ne pouvez servir Dieu et Mammon. Le riche dans le tourment supplie une goutte d’eau. Un grand abîme est fixé."},
{day:19,reading:"Luke 17",topic:"Faith, Gratitude & the Coming Kingdom",topic_es:"Fe, gratitud y el Reino venidero",topic_fr:"Foi, gratitude et le Royaume qui vient",
  summary:"If you had faith like a grain of mustard seed. Ten lepers are cleansed — only one returns to give thanks. The kingdom of God is in your midst.",
  summary_es:"Si tuvierais fe como un grano de mostaza. Diez leprosos son limpiados — solo uno vuelve a dar gracias. El reino de Dios está entre vosotros.",
  summary_fr:"Si vous aviez de la foi comme un grain de moutarde. Dix lépreux sont guéris — un seul revient rendre grâces. Le royaume de Dieu est au milieu de vous."},
{day:20,reading:"Luke 18",topic:"Persistent Prayer & the Rich Ruler",topic_es:"La oración persistente y el joven rico",topic_fr:"La prière persévérante et le jeune homme riche",
  summary:"The persistent widow and the unjust judge. The Pharisee and the tax collector. Let the children come. The rich ruler goes away sad. ‘What is impossible with man is possible with God.’",
  summary_es:"La viuda persistente y el juez injusto. El fariseo y el publicano. Dejad a los niños venir. El joven rico se va triste. ‘Lo que es imposible para los hombres, es posible para Dios.’",
  summary_fr:"La veuve persévérante et le juge inique. Le pharisien et le publicain. Laissez venir les enfants. Le jeune homme riche s’en va tout triste. ‘Ce qui est impossible aux hommes est possible à Dieu.’"},
{day:21,reading:"Luke 13–18",topic:"Phase 3 Re-Read",topic_es:"Relectura de la Fase 3",topic_fr:"Relecture de la phase 3",
  summary:"Re-read Luke 13–18. The cost of following Jesus, the heart of the Father for the lost, and the impossibility of serving two masters.",
  summary_es:"Relee Lucas 13–18. El precio de seguir a Jesús, el corazón del Padre por los perdidos y la imposibilidad de servir a dos señores.",
  summary_fr:"Relis Luc 13–18. Le prix de suivre Jésus, le cœur du Père pour les perdus, et l’impossibilité de servir deux maîtres."},
{day:22,reading:"Luke 19",topic:"Zacchaeus & the Triumphal Entry",topic_es:"Zaqueo y la Entrada Triunfal",topic_fr:"Zachée et l’entrée triomphale",ph:4,
  summary:"Jesus seeks and saves Zacchaeus. The parable of the ten minas. He rides into Jerusalem weeping over the city and cleanses the temple.",
  summary_es:"Jesús busca y salva a Zaqueo. La parábola de las diez minas. Entra en Jerusalén llorando sobre la ciudad y purifica el templo.",
  summary_fr:"Jésus cherche et sauve Zachée. La parabole des dix mines. Il entre dans Jérusalem en pleurant sur la ville et purifie le temple."},
{day:23,reading:"Luke 20",topic:"Authority Challenged",topic_es:"La autoridad cuestionada",topic_fr:"L’autorité contestée",
  summary:"The religious leaders challenge Jesus’ authority. The parable of the wicked tenants. ‘Render to Caesar the things that are Caesar’s, and to God the things that are God’s.’",
  summary_es:"Los líderes religiosos cuestionan la autoridad de Jesús. La parábola de los labradores malvados. ‘Dad al César lo que es del César, y a Dios lo que es de Dios.’",
  summary_fr:"Les chefs religieux contestent l’autorité de Jésus. La parabole des vignerons méchants. ‘Rendez à César ce qui est à César, et à Dieu ce qui est à Dieu.’"},
{day:24,reading:"Luke 21",topic:"Signs of the End",topic_es:"Señales del fin",topic_fr:"Les signes de la fin",
  summary:"The widow’s offering. Jesus prophesies the destruction of the temple and the signs before His return. ‘Heaven and earth will pass away, but my words will not pass away.’",
  summary_es:"La ofrenda de la viuda. Jesús profetiza la destrucción del templo y las señales antes de su venida. ‘El cielo y la tierra pasarán, pero mis palabras no pasarán.’",
  summary_fr:"L’offrande de la veuve. Jésus prophétise la destruction du temple et les signes précédant son retour. ‘Le ciel et la terre passeront, mais mes paroles ne passeront point.’"},
{day:25,reading:"Luke 22",topic:"The Last Supper, Gethsemane & Arrest",topic_es:"La Última Cena, Getsemaní y el arresto",topic_fr:"La Cène, Gethsémani et l’arrestation",
  summary:"Judas conspires. Jesus breaks bread: ‘This is my body given for you.’ He prays in agony on the Mount of Olives. Peter denies Him three times.",
  summary_es:"Judas conspira. Jesús parte el pan: ‘Esto es mi cuerpo, que por vosotros es dado.’ Ora en agonía en el monte de los Olivos. Pedro lo niega tres veces.",
  summary_fr:"Judas conspire. Jésus rompt le pain : ‘Ceci est mon corps, qui est donné pour vous.’ Il prie en agonie sur le mont des Oliviers. Pierre le renie trois fois."},
{day:26,reading:"Luke 23",topic:"Trial & Crucifixion",topic_es:"Juicio y Crucifixión",topic_fr:"Procès et Crucifixion",
  summary:"Jesus before Pilate and Herod. The crowd chooses Barabbas. ‘Father, forgive them, for they know not what they do.’ The thief on the cross: ‘Today you will be with me in paradise.’",
  summary_es:"Jesús ante Pilato y Herodes. La multitud elige a Barrabás. ‘Padre, perdónalos, porque no saben lo que hacen.’ El ladrón en la cruz: ‘Hoy estarás conmigo en el paraíso.’",
  summary_fr:"Jésus devant Pilate et Hérode. La foule choisit Barabbas. ‘Père, pardonne-leur, car ils ne savent ce qu’ils font.’ Le brigand sur la croix : ‘Aujourd’hui tu seras avec moi dans le paradis.’"},
{day:27,reading:"Luke 24",topic:"The Resurrection & Ascension",topic_es:"La Resurrección y la Ascensión",topic_fr:"La Résurrection et l’Ascension",
  summary:"The tomb is empty. Jesus walks with two disciples on the road to Emmaus and opens the Scriptures. He appears to the eleven, opens their minds, and ascends into heaven.",
  summary_es:"La tumba está vacía. Jesús camina con dos discípulos en el camino a Emaús y les abre las Escrituras. Se aparece a los once, abre sus mentes y asciende al cielo.",
  summary_fr:"Le tombeau est vide. Jésus marche avec deux disciples sur le chemin d’Emmaüs et leur ouvre les Écritures. Il apparaît aux onze, leur ouvre l’intelligence et monte au ciel."},
{day:28,reading:"Luke 19–24",topic:"Phase 4 Re-Read",topic_es:"Relectura de la Fase 4",topic_fr:"Relecture de la phase 4",
  summary:"Re-read Luke 19–24. The final week. Triumphal entry, last supper, the cross, the empty tomb, the road to Emmaus. The whole gospel in six chapters.",
  summary_es:"Relee Lucas 19–24. La semana final. Entrada triunfal, última cena, la cruz, la tumba vacía, el camino a Emaús. Todo el evangelio en seis capítulos.",
  summary_fr:"Relis Luc 19–24. La semaine finale. L’entrée triomphale, la Cène, la croix, le tombeau vide, le chemin d’Emmaüs. Tout l’évangile en six chapitres."}
],
  verses: {
1:{r:"Luke 2:11",r_es:"Lucas 2:11",r_fr:"Luc 2:11",
  t:"For unto you is born this day in the city of David a Savior, who is Christ the Lord.",
  t_es:"Que os ha nacido hoy, en la ciudad de David, un Salvador, que es CRISTO el Señor.",
  t_fr:"C’est qu’aujourd’hui, dans la ville de David, il vous est né un Sauveur, qui est le Christ, le Seigneur."},
8:{r:"Luke 9:25",r_es:"Lucas 9:25",r_fr:"Luc 9:25",
  t:"For what does it profit a man if he gains the whole world and loses or forfeits himself?",
  t_es:"Pues ¿qué aprovecha al hombre, si gana todo el mundo, y se destruye o se pierde a sí mismo?",
  t_fr:"Et que servirait-il à un homme de gagner tout le monde, s’il se détruisait ou se perdait lui-même ?"},
15:{r:"Luke 14:11",r_es:"Lucas 14:11",r_fr:"Luc 14:11",
  t:"For everyone who exalts himself will be humbled, and he who humbles himself will be exalted.",
  t_es:"Porque cualquiera que se enaltece, será humillado; y el que se humilla, será enaltecido.",
  t_fr:"Car quiconque s’élève sera abaissé, et quiconque s’abaisse sera élevé."},
22:{r:"Luke 19:10",r_es:"Lucas 19:10",r_fr:"Luc 19:10",
  t:"For the Son of Man came to seek and to save the lost.",
  t_es:"Porque el Hijo del Hombre vino a buscar y a salvar lo que se había perdido.",
  t_fr:"Car le Fils de l’homme est venu chercher et sauver ce qui était perdu."}
},
  checks: [
  {k:"read",l:"Read the passage",l_es:"Lee el pasaje",l_fr:"Lis le passage"},
  {k:"pray",l:"Pray & journal",l_es:"Ora y escribe en tu diario",l_fr:"Prie et tiens un journal"},
  {k:"workout",l:"Workout (3–5x/week)",l_es:"Entrena (3–5x por semana)",l_fr:"Entraîne-toi (3–5x par semaine)"},
  {k:"abstain",l:"Abstain from your one thing",l_es:"Abstente de aquello que decidiste",l_fr:"Abstiens-toi de la chose que tu as choisie"},
  {k:"marco",l:"Marco Polo update",l_es:"Mensaje en Marco Polo",l_fr:"Mise à jour Marco Polo"}
]
};
