// Iron Sharpens Iron v2.2.0 — Selected Scriptures Config (en/es/fr)
window.PLAN = {
  title: "Selected Scriptures",
  title_es: "Pasajes Seleccionados",
  title_fr: "Passages choisis",
  subtitle: "SELECTED SCRIPTURES — 30-DAY CHALLENGE",
  subtitle_es: "PASAJES SELECCIONADOS — RETO DE 30 DÍAS",
  subtitle_fr: "PASSAGES CHOISIS — DÉFI DE 30 JOURS",
  storageKey: "isi-select-v2",
  totalDays: 30,
  days: [
{day:1,reading:"Genesis 1–2",topic:"Creation Account",topic_es:"El relato de la creación",topic_fr:"Le récit de la création",ph:1,
  summary:"God creates the heavens and the earth in six days and rests on the seventh. Everything He made was good — and humanity was made in His image to steward creation.",
  summary_es:"Dios crea los cielos y la tierra en seis días y reposa en el séptimo. Todo lo que hizo era bueno — y el ser humano fue hecho a su imagen para administrar la creación.",
  summary_fr:"Dieu crée les cieux et la terre en six jours et se repose le septième. Tout ce qu’il a fait était bon — et l’homme est créé à son image pour gérer la création."},
{day:2,reading:"Genesis 3",topic:"How Sin Started, Promise of Jesus",topic_es:"Cómo comenzó el pecado y la promesa de Jesús",topic_fr:"L’origine du péché, la promesse de Jésus",
  summary:"The fall of man through Adam and Eve’s disobedience. God curses the serpent and promises a deliverer — the first gospel (protoevangelium) in Genesis 3:15.",
  summary_es:"La caída del hombre por la desobediencia de Adán y Eva. Dios maldice a la serpiente y promete un libertador — el primer evangelio (protoevangelio) en Génesis 3:15.",
  summary_fr:"La chute par la désobéissance d’Adam et Ève. Dieu maudit le serpent et promet un libérateur — le premier évangile (protévangile) en Genèse 3:15."},
{day:3,reading:"Exodus 20:1–20",topic:"The 10 Commandments",topic_es:"Los Diez Mandamientos",topic_fr:"Les Dix Commandements",
  summary:"God delivers the Ten Commandments to Moses on Mount Sinai — the moral law that reveals God’s holiness and our need for a Savior.",
  summary_es:"Dios entrega los Diez Mandamientos a Moisés en el monte Sinaí — la ley moral que revela la santidad de Dios y nuestra necesidad de un Salvador.",
  summary_fr:"Dieu remet les Dix Commandements à Moïse sur le mont Sinaï — la loi morale qui révèle la sainteté de Dieu et notre besoin d’un Sauveur."},
{day:4,reading:"Psalm 23",topic:"Prayer of Comfort",topic_es:"Oración de consuelo",topic_fr:"Prière de réconfort",
  summary:"David’s beloved psalm of trust. The Lord is our Shepherd — He leads, provides, protects, and comforts even through the valley of the shadow of death.",
  summary_es:"El amado salmo de confianza de David. Jehová es nuestro Pastor — guía, provee, protege y conforta aun en el valle de sombra de muerte.",
  summary_fr:"Le psaume de confiance bien-aimé de David. L’Éternel est notre berger — il conduit, pourvoit, protège et réconforte même dans la vallée de l’ombre de la mort."},
{day:5,reading:"Psalm 51",topic:"Prayer of Confession",topic_es:"Oración de confesión",topic_fr:"Prière de confession",
  summary:"David’s prayer of repentance after his sin with Bathsheba. A model for brokenness, confession, and the plea for God to create a clean heart.",
  summary_es:"La oración de arrepentimiento de David tras su pecado con Betsabé. Un modelo de quebranto, confesión y la súplica para que Dios cree un corazón limpio.",
  summary_fr:"La prière de repentance de David après son péché avec Bath-Schéba. Un modèle de brisure, de confession et de supplication pour que Dieu crée un cœur pur."},
{day:6,reading:"Psalm 139",topic:"Prayer of Praise",topic_es:"Oración de alabanza",topic_fr:"Prière de louange",
  summary:"David praises God’s omniscience, omnipresence, and sovereignty. God knows us intimately — we are fearfully and wonderfully made.",
  summary_es:"David alaba la omnisciencia, la omnipresencia y la soberanía de Dios. Dios nos conoce íntimamente — formidables y maravillosas son sus obras.",
  summary_fr:"David loue l’omniscience, l’omniprésence et la souveraineté de Dieu. Dieu nous connaît intimement — nous sommes une création merveilleuse."},
{day:7,reading:"Isaiah 53",topic:"Prophecy of Jesus",topic_es:"Profecía de Jesús",topic_fr:"Prophétie de Jésus",
  summary:"The Suffering Servant prophecy — written 700 years before Christ, yet describing His rejection, suffering, and atoning death with stunning precision.",
  summary_es:"La profecía del Siervo Sufriente — escrita 700 años antes de Cristo, y aun así describe su rechazo, su sufrimiento y su muerte expiatoria con precisión asombrosa.",
  summary_fr:"La prophétie du Serviteur souffrant — écrite 700 ans avant le Christ, et qui décrit pourtant son rejet, ses souffrances et sa mort expiatoire avec une précision saisissante."},
{day:8,reading:"Lamentations 3:19–25",topic:"How to Find Hope",topic_es:"Cómo hallar esperanza",topic_fr:"Comment trouver l’espérance",ph:2,
  summary:"In the midst of sorrow, Jeremiah declares God’s mercies are new every morning. Great is His faithfulness — hope is found in waiting on the Lord.",
  summary_es:"En medio del dolor, Jeremías declara que las misericordias de Dios son nuevas cada mañana. Grande es su fidelidad — la esperanza se halla esperando en Jehová.",
  summary_fr:"Au milieu de la douleur, Jérémie déclare que les compassions de Dieu se renouvellent chaque matin. Sa fidélité est grande — l’espérance se trouve dans l’attente du Seigneur."},
{day:9,reading:"Daniel 6",topic:"Daniel and the Lions Den",topic_es:"Daniel en el foso de los leones",topic_fr:"Daniel dans la fosse aux lions",
  summary:"Daniel’s faithfulness to God in the face of a death sentence. He keeps praying despite the decree — and God shuts the lions’ mouths.",
  summary_es:"La fidelidad de Daniel a Dios frente a una sentencia de muerte. Sigue orando a pesar del decreto — y Dios cierra la boca de los leones.",
  summary_fr:"La fidélité de Daniel à Dieu face à une sentence de mort. Il continue de prier malgré le décret — et Dieu ferme la gueule des lions."},
{day:10,reading:"Matthew 5",topic:"Jesus on Happiness & Hypocrisy",topic_es:"Jesús sobre la dicha y la hipocresía",topic_fr:"Jésus sur le bonheur et l’hypocrisie",
  summary:"The Sermon on the Mount begins with the Beatitudes — Jesus redefines blessedness. Salt and light. The higher standard of the Kingdom.",
  summary_es:"El Sermón del Monte comienza con las Bienaventuranzas — Jesús redefine la bienaventuranza. Sal y luz. El estándar más alto del Reino.",
  summary_fr:"Le sermon sur la montagne commence par les Béatitudes — Jésus redéfinit le bonheur. Sel et lumière. L’exigence supérieure du Royaume."},
{day:11,reading:"Matthew 6",topic:"Jesus on Prayer & Anxiety",topic_es:"Jesús sobre la oración y la ansiedad",topic_fr:"Jésus sur la prière et l’anxiété",
  summary:"Jesus teaches the Lord’s Prayer and calls us to lay down anxiety. ‘Seek first the kingdom of God and His righteousness, and all these things will be added to you.’",
  summary_es:"Jesús enseña el Padre Nuestro y nos llama a soltar la ansiedad. ‘Buscad primeramente el reino de Dios y su justicia, y todas estas cosas os serán añadidas.’",
  summary_fr:"Jésus enseigne le Notre Père et nous appelle à déposer l’anxiété. ‘Cherchez premièrement le royaume et la justice de Dieu ; et toutes ces choses vous seront données par-dessus.’"},
{day:12,reading:"Matthew 7",topic:"Jesus on Loving People & Salvation",topic_es:"Jesús sobre amar a la gente y la salvación",topic_fr:"Jésus sur l’amour du prochain et le salut",
  summary:"Jesus teaches about judging others, the golden rule, the narrow gate, and building your life on the rock. ‘By their fruits you will know them.’",
  summary_es:"Jesús enseña sobre el juzgar a otros, la regla de oro, la puerta estrecha y edificar tu vida sobre la roca. ‘Por sus frutos los conoceréis.’",
  summary_fr:"Jésus enseigne sur le jugement des autres, la règle d’or, la porte étroite et bâtir sa vie sur le roc. ‘C’est à leurs fruits que vous les reconnaîtrez.’"},
{day:13,reading:"John 17",topic:"Jesus Praying for His Followers",topic_es:"Jesús orando por los suyos",topic_fr:"Jésus priant pour les siens",
  summary:"Jesus’ High Priestly Prayer before the cross — He prays for His disciples’ unity, protection, sanctification, and for all who would believe through their testimony.",
  summary_es:"La oración sumo sacerdotal de Jesús antes de la cruz — ora por la unidad, la protección y la santificación de sus discípulos, y por todos los que creerán por su testimonio.",
  summary_fr:"La prière sacerdotale de Jésus avant la croix — il prie pour l’unité, la protection et la sanctification de ses disciples, et pour tous ceux qui croiront par leur témoignage."},
{day:14,reading:"John 19",topic:"Jesus’ Crucifixion",topic_es:"La crucifixión de Jesús",topic_fr:"La crucifixion de Jésus",
  summary:"The arrest, trial, and crucifixion of Jesus Christ. ‘It is finished.’ The Lamb of God takes away the sin of the world on the cross of Calvary.",
  summary_es:"El arresto, el juicio y la crucifixión de Jesucristo. ‘Consumado es.’ El Cordero de Dios quita el pecado del mundo en la cruz del Calvario.",
  summary_fr:"L’arrestation, le procès et la crucifixion de Jésus-Christ. ‘Tout est accompli.’ L’Agneau de Dieu ôte le péché du monde sur la croix du Calvaire."},
{day:15,reading:"John 20",topic:"Jesus’ Resurrection",topic_es:"La resurrección de Jesús",topic_fr:"La résurrection de Jésus",ph:3,
  summary:"The empty tomb. Mary Magdalene, Peter, and John discover that Jesus has risen. Thomas believes: ‘My Lord and my God!’",
  summary_es:"La tumba vacía. María Magdalena, Pedro y Juan descubren que Jesús ha resucitado. Tomás cree: ‘¡Señor mío, y Dios mío!’",
  summary_fr:"Le tombeau vide. Marie de Magdala, Pierre et Jean découvrent que Jésus est ressuscité. Thomas croit : ‘Mon Seigneur et mon Dieu !’"},
{day:16,reading:"Romans 8:26–30",topic:"God Works All Things for Good",topic_es:"Dios obra todas las cosas para bien",topic_fr:"Dieu fait concourir tout au bien",
  summary:"The Spirit intercedes for us. God works all things together for good for those who love Him. Those He foreknew, He predestined, called, justified, and glorified.",
  summary_es:"El Espíritu intercede por nosotros. Dios hace que todas las cosas obren para bien de los que le aman. A los que antes conoció, predestinó, llamó, justificó y glorificó.",
  summary_fr:"L’Esprit intercède pour nous. Dieu fait concourir toutes choses au bien de ceux qui l’aiment. Ceux qu’il a connus d’avance, il les a prédestinés, appelés, justifiés et glorifiés."},
{day:17,reading:"Romans 8:31–39",topic:"God’s Unbreakable Love",topic_es:"El amor inquebrantable de Dios",topic_fr:"L’amour incassable de Dieu",
  summary:"Nothing can separate us from the love of God in Christ Jesus. If God is for us, who can be against us? We are more than conquerors through Him.",
  summary_es:"Nada nos podrá separar del amor de Dios, que es en Cristo Jesús Señor nuestro. Si Dios es por nosotros, ¿quién contra nosotros? Somos más que vencedores por medio de él.",
  summary_fr:"Rien ne pourra nous séparer de l’amour de Dieu en Jésus-Christ. Si Dieu est pour nous, qui sera contre nous ? Nous sommes plus que vainqueurs par celui qui nous a aimés."},
{day:18,reading:"1 Corinthians 9:23–27",topic:"Discipline",topic_es:"Disciplina",topic_fr:"Discipline",
  summary:"Paul compares the Christian life to an athlete’s training. We run to win the imperishable crown — disciplining our bodies so we don’t become disqualified.",
  summary_es:"Pablo compara la vida cristiana al entrenamiento del atleta. Corremos para obtener la corona incorruptible — disciplinando nuestro cuerpo para no ser eliminados.",
  summary_fr:"Paul compare la vie chrétienne à l’entraînement de l’athlète. Nous courons pour remporter la couronne incorruptible — domptant notre corps pour ne pas être désapprouvés."},
{day:19,reading:"1 Corinthians 13",topic:"Love",topic_es:"El amor",topic_fr:"L’amour",
  summary:"Paul’s definitive description of love. Patient, kind, not envious or boastful. Love never fails. The greatest of faith, hope, and love — is love.",
  summary_es:"La descripción definitiva del amor por Pablo. Sufrido, benigno, no tiene envidia ni se jacta. El amor nunca deja de ser. Y el mayor de la fe, la esperanza y el amor — es el amor.",
  summary_fr:"La description définitive de l’amour par Paul. Patient, bienveillant, sans envie ni vantardise. L’amour ne périt jamais. Le plus grand entre la foi, l’espérance et l’amour — c’est l’amour."},
{day:20,reading:"2 Corinthians 5:17–21",topic:"The Heart of the Gospel",topic_es:"El corazón del evangelio",topic_fr:"Le cœur de l’Évangile",
  summary:"If anyone is in Christ, he is a new creation. God reconciled the world to Himself through Christ and gave us the ministry of reconciliation.",
  summary_es:"Si alguno está en Cristo, nueva criatura es. Dios reconcilió consigo al mundo por medio de Cristo y nos dio el ministerio de la reconciliación.",
  summary_fr:"Si quelqu’un est en Christ, il est une nouvelle créature. Dieu a réconcilié le monde avec lui-même par Christ et nous a confié le ministère de la réconciliation."},
{day:21,reading:"Galatians 5:16–26",topic:"Fruit of the Spirit",topic_es:"El fruto del Espíritu",topic_fr:"Le fruit de l’Esprit",
  summary:"Walk by the Spirit, not the flesh. The fruit of the Spirit: love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, self-control.",
  summary_es:"Andad en el Espíritu, no en la carne. El fruto del Espíritu: amor, gozo, paz, paciencia, benignidad, bondad, fe, mansedumbre, dominio propio.",
  summary_fr:"Marchez selon l’Esprit, et non selon la chair. Le fruit de l’Esprit : amour, joie, paix, patience, bonté, bienveillance, fidélité, douceur, maîtrise de soi."},
{day:22,reading:"Ephesians 4:25–32",topic:"How We Should and Shouldn’t Talk",topic_es:"Cómo debemos y no debemos hablar",topic_fr:"Comment nous devons (et ne devons pas) parler",ph:4,
  summary:"Put away falsehood. Speak truth. Don’t let the sun go down on anger. Let no corrupting talk come from your mouth — only what builds others up.",
  summary_es:"Desechad la mentira. Hablad verdad. No se ponga el sol sobre vuestro enojo. Ninguna palabra corrompida salga de vuestra boca — sino la que sea buena para edificar.",
  summary_fr:"Renoncez au mensonge. Dites la vérité. Que le soleil ne se couche pas sur votre colère. Qu’il ne sorte de votre bouche aucune parole mauvaise — mais ce qui édifie."},
{day:23,reading:"Ephesians 6:10–20",topic:"The Armor of God",topic_es:"La armadura de Dios",topic_fr:"L’armure de Dieu",
  summary:"Our battle is not against flesh and blood. Put on the full armor of God: truth, righteousness, the gospel, faith, salvation, the Word, and prayer.",
  summary_es:"Nuestra lucha no es contra carne y sangre. Vestíos de toda la armadura de Dios: verdad, justicia, el evangelio, fe, salvación, la Palabra y la oración.",
  summary_fr:"Notre lutte n’est pas contre la chair et le sang. Revêtez-vous de toutes les armes de Dieu : vérité, justice, l’Évangile, foi, salut, la Parole et la prière."},
{day:24,reading:"Philippians 2:1–11",topic:"Humility and the Example of Christ",topic_es:"Humildad y el ejemplo de Cristo",topic_fr:"Humilité et l’exemple du Christ",
  summary:"Have the mind of Christ — who, being in the form of God, emptied Himself and became a servant, obedient to death on a cross. God highly exalted Him.",
  summary_es:"Haya en vosotros este sentir que hubo en Cristo Jesús — el cual, siendo en forma de Dios, se despojó a sí mismo y tomó forma de siervo, obediente hasta la muerte de cruz. Por lo cual Dios también le exaltó.",
  summary_fr:"Ayez en vous les sentiments du Christ — lui qui, étant en forme de Dieu, s’est dépouillé et a pris la forme d’un serviteur, obéissant jusqu’à la mort sur la croix. C’est pourquoi Dieu l’a souverainement élevé."},
{day:25,reading:"Philippians 4:4–8",topic:"Peace of God That Guards Us",topic_es:"La paz de Dios que nos guarda",topic_fr:"La paix de Dieu qui nous garde",
  summary:"Rejoice in the Lord always. The peace of God, which surpasses all understanding, will guard your hearts and minds in Christ Jesus.",
  summary_es:"Regocijaos en el Señor siempre. La paz de Dios, que sobrepasa todo entendimiento, guardará vuestros corazones y vuestros pensamientos en Cristo Jesús.",
  summary_fr:"Réjouissez-vous toujours dans le Seigneur. La paix de Dieu, qui surpasse toute intelligence, gardera vos cœurs et vos pensées en Jésus-Christ."},
{day:26,reading:"James 1:1–18",topic:"Endurance When Faith Is Tested",topic_es:"Constancia cuando la fe es probada",topic_fr:"Endurance quand la foi est éprouvée",
  summary:"Count it all joy when you face trials — the testing of your faith produces steadfastness. Every good and perfect gift comes from the Father of lights.",
  summary_es:"Tened por sumo gozo cuando os halléis en diversas pruebas — la prueba de vuestra fe produce paciencia. Toda buena dádiva y todo don perfecto desciende del Padre de las luces.",
  summary_fr:"Considérez comme un sujet de joie complète les diverses épreuves — l’épreuve de votre foi produit la patience. Tout don excellent et tout don parfait descend du Père des lumières."},
{day:27,reading:"James 1:19–27",topic:"Pure and True Religion",topic_es:"Religión pura y verdadera",topic_fr:"Religion pure et véritable",
  summary:"Be quick to listen, slow to speak, slow to anger. Be doers of the Word, not hearers only. Pure religion is caring for orphans and widows.",
  summary_es:"Pronto para oír, tardo para hablar, tardo para airarse. Sed hacedores de la palabra, y no tan solamente oidores. La religión pura es visitar a los huérfanos y a las viudas.",
  summary_fr:"Soyez prompts à écouter, lents à parler, lents à la colère. Mettez en pratique la parole, et ne vous bornez pas à l’écouter. La religion pure consiste à visiter les orphelins et les veuves."},
{day:28,reading:"1 Peter 5:6–11",topic:"Humility and Enduring Suffering",topic_es:"Humildad y resistir el sufrimiento",topic_fr:"Humilité et endurer la souffrance",
  summary:"Humble yourselves under God’s mighty hand. Cast your anxieties on Him. Be sober-minded and watchful — resist the devil, firm in your faith.",
  summary_es:"Humillaos bajo la poderosa mano de Dios. Echad toda vuestra ansiedad sobre él. Sed sobrios, y velad — resistid al diablo, firmes en la fe.",
  summary_fr:"Humiliez-vous sous la puissante main de Dieu. Déchargez-vous sur lui de tous vos soucis. Soyez sobres, veillez — résistez au diable, fermes dans la foi."},
{day:29,reading:"1 John 4:7–21",topic:"Love That Removes Fear",topic_es:"Amor que echa fuera el temor",topic_fr:"L’amour qui chasse la crainte",
  summary:"God is love. He loved us first. Perfect love casts out fear. If God so loved us, we ought to love one another — for the one who does not love does not know God.",
  summary_es:"Dios es amor. Él nos amó primero. El perfecto amor echa fuera el temor. Si Dios nos ha amado así, debemos también nosotros amarnos unos a otros — el que no ama, no ha conocido a Dios.",
  summary_fr:"Dieu est amour. Il nous a aimés le premier. L’amour parfait bannit la crainte. Si Dieu nous a tant aimés, nous devons aussi nous aimer les uns les autres — celui qui n’aime pas n’a pas connu Dieu."},
{day:30,reading:"Revelation 22",topic:"Final Words & What Eternity Will Be",topic_es:"Palabras finales y cómo será la eternidad",topic_fr:"Paroles finales et l’éternité à venir",
  summary:"The river of life, the tree of life, and the new heaven and earth. No more curse, no more night. Jesus says, ‘Behold, I am coming soon.’ Amen. Come, Lord Jesus!",
  summary_es:"El río de vida, el árbol de la vida y el nuevo cielo y la nueva tierra. Ya no habrá maldición ni noche. Jesús dice: ‘He aquí, vengo pronto.’ Amén. ¡Ven, Señor Jesús!",
  summary_fr:"Le fleuve de la vie, l’arbre de la vie, et le nouveau ciel et la nouvelle terre. Plus de malédiction, plus de nuit. Jésus dit : ‘Voici, je viens bientôt.’ Amen. Viens, Seigneur Jésus !"}
],
  verses: {
1:{r:"Psalm 23:4",r_es:"Salmo 23:4",r_fr:"Psaume 23:4",
  t:"Even though I walk through the valley of the shadow of death, I will fear no evil, for you are with me; your rod and your staff, they comfort me.",
  t_es:"Aunque ande en valle de sombra de muerte, no temeré mal alguno, porque tú estarás conmigo; tu vara y tu cayado me infundirán aliento.",
  t_fr:"Quand je marche dans la vallée de l’ombre de la mort, je ne crains aucun mal, car tu es avec moi : ta houlette et ton bâton me rassurent."},
8:{r:"Lamentations 3:22–23",r_es:"Lamentaciones 3:22–23",r_fr:"Lamentations 3:22–23",
  t:"The steadfast love of the Lord never ceases; his mercies never come to an end; they are new every morning; great is your faithfulness.",
  t_es:"Por la misericordia de Jehová no hemos sido consumidos, porque nunca decayeron sus misericordias. Nuevas son cada mañana; grande es tu fidelidad.",
  t_fr:"Les bontés de l’Éternel ne sont pas épuisées, ses compassions ne sont pas à leur terme ; elles se renouvellent chaque matin. Oh ! que ta fidélité est grande !"},
15:{r:"Romans 8:28",r_es:"Romanos 8:28",r_fr:"Romains 8:28",
  t:"And we know that for those who love God all things work together for good, for those who are called according to his purpose.",
  t_es:"Y sabemos que a los que aman a Dios, todas las cosas les ayudan a bien, esto es, a los que conforme a su propósito son llamados.",
  t_fr:"Nous savons, du reste, que toutes choses concourent au bien de ceux qui aiment Dieu, de ceux qui sont appelés selon son dessein."},
22:{r:"Philippians 4:6–7",r_es:"Filipenses 4:6–7",r_fr:"Philippiens 4:6–7",
  t:"Do not be anxious about anything, but in everything by prayer and supplication with thanksgiving let your requests be made known to God. And the peace of God, which surpasses all understanding, will guard your hearts and your minds in Christ Jesus.",
  t_es:"Por nada estéis afanosos, sino sean conocidas vuestras peticiones delante de Dios en toda oración y ruego, con acción de gracias. Y la paz de Dios, que sobrepasa todo entendimiento, guardará vuestros corazones y vuestros pensamientos en Cristo Jesús.",
  t_fr:"Ne vous inquiétez de rien ; mais en toute chose faites connaître vos besoins à Dieu par des prières et des supplications, avec des actions de grâces. Et la paix de Dieu, qui surpasse toute intelligence, gardera vos cœurs et vos pensées en Jésus-Christ."}
},
  checks: [
  {k:"read",l:"Read the passage",l_es:"Lee el pasaje",l_fr:"Lis le passage"},
  {k:"pray",l:"Pray & journal",l_es:"Ora y escribe en tu diario",l_fr:"Prie et tiens un journal"},
  {k:"workout",l:"Workout (3–5x/week)",l_es:"Entrena (3–5x por semana)",l_fr:"Entraîne-toi (3–5x par semaine)"},
  {k:"abstain",l:"Abstain from your one thing",l_es:"Abstente de aquello que decidiste",l_fr:"Abstiens-toi de la chose que tu as choisie"},
  {k:"marco",l:"Marco Polo update",l_es:"Mensaje en Marco Polo",l_fr:"Mise à jour Marco Polo"}
]
};
