// Iron Sharpens Iron v2.2.0 — Gospel of John (May 2026) Config (en/es/fr)
window.PLAN = {
  title: "Gospel of John",
  title_es: "Evangelio de Juan",
  title_fr: "Évangile de Jean",
  subtitle: "GOSPEL OF JOHN — 30-DAY CHALLENGE",
  subtitle_es: "EVANGELIO DE JUAN — RETO DE 30 DÍAS",
  subtitle_fr: "ÉVANGILE DE JEAN — DÉFI DE 30 JOURS",
  storageKey: "isi-john-v2",
  totalDays: 30,
  days: [
{day:1,reading:"John 1",topic:"The Word Became Flesh",topic_es:"El Verbo se hizo carne",topic_fr:"La Parole s’est faite chair",ph:1,
  summary:"In the beginning was the Word. John the Baptist testifies. Jesus calls His first disciples — Andrew, Peter, Philip, and Nathanael. ‘We have found the Messiah.’",
  summary_es:"En el principio era el Verbo. Juan el Bautista da testimonio. Jesús llama a sus primeros discípulos — Andrés, Pedro, Felipe y Natanael. ‘Hemos hallado al Mesías.’",
  summary_fr:"Au commencement était la Parole. Jean-Baptiste rend témoignage. Jésus appelle ses premiers disciples — André, Pierre, Philippe et Nathanaël. ‘Nous avons trouvé le Messie.’"},
{day:2,reading:"John 2",topic:"Water to Wine & Temple Cleansing",topic_es:"Agua en vino y purificación del templo",topic_fr:"L’eau changée en vin et la purification du temple",
  summary:"Jesus turns water into wine at Cana — His first sign. He drives out the money changers: ‘Destroy this temple, and in three days I will raise it up.’",
  summary_es:"Jesús convierte el agua en vino en Caná — su primera señal. Echa a los cambistas: ‘Destruid este templo, y en tres días lo levantaré.’",
  summary_fr:"Jésus change l’eau en vin à Cana — son premier signe. Il chasse les changeurs : ‘Détruisez ce temple, et en trois jours je le relèverai.’"},
{day:3,reading:"John 3",topic:"You Must Be Born Again",topic_es:"Es necesario nacer de nuevo",topic_fr:"Il faut naître de nouveau",
  summary:"Jesus tells Nicodemus about the new birth. ‘For God so loved the world, that He gave His only Son.’ John the Baptist: ‘He must increase, I must decrease.’",
  summary_es:"Jesús habla a Nicodemo del nuevo nacimiento. ‘De tal manera amó Dios al mundo, que ha dado a su Hijo unigénito.’ Juan el Bautista: ‘Es necesario que él crezca, y que yo mengüe.’",
  summary_fr:"Jésus parle à Nicodème de la nouvelle naissance. ‘Dieu a tant aimé le monde qu’il a donné son Fils unique.’ Jean-Baptiste : ‘Il faut qu’il croisse, et que je diminue.’"},
{day:4,reading:"John 4",topic:"The Woman at the Well",topic_es:"La mujer junto al pozo",topic_fr:"La femme au puits",
  summary:"Jesus crosses cultural barriers to offer living water to the Samaritan woman. ‘God is spirit, and those who worship Him must worship in spirit and truth.’",
  summary_es:"Jesús cruza las barreras culturales y ofrece agua viva a la samaritana. ‘Dios es espíritu; y los que le adoran, en espíritu y en verdad es necesario que adoren.’",
  summary_fr:"Jésus franchit les barrières culturelles pour offrir l’eau vive à la Samaritaine. ‘Dieu est Esprit, et il faut que ceux qui l’adorent l’adorent en esprit et en vérité.’"},
{day:5,reading:"John 5:1–24",topic:"Healing at Bethesda & the Son’s Authority",topic_es:"Sanidad en Betesda y la autoridad del Hijo",topic_fr:"Guérison à Béthesda et l’autorité du Fils",
  summary:"Jesus heals the man at the pool of Bethesda on the Sabbath. ‘The Son gives life to whom He will.’ The religious leaders begin seeking to kill Him.",
  summary_es:"Jesús sana al hombre en el estanque de Betesda en sábado. ‘El Hijo da vida a los que él quiere.’ Los líderes religiosos comienzan a buscar matarlo.",
  summary_fr:"Jésus guérit l’homme à la piscine de Béthesda un jour de sabbat. ‘Le Fils donne la vie à qui il veut.’ Les chefs religieux commencent à chercher à le tuer."},
{day:6,reading:"John 5:25–47",topic:"Witnesses to Jesus",topic_es:"Testigos de Jesús",topic_fr:"Les témoins rendus à Jésus",
  summary:"Jesus declares the dead will hear His voice and live. He calls four witnesses: John the Baptist, His works, the Father, and the Scriptures. ‘You search the Scriptures — it is they that bear witness about me.’",
  summary_es:"Jesús declara que los muertos oirán su voz y vivirán. Convoca cuatro testigos: Juan el Bautista, sus obras, el Padre y las Escrituras. ‘Escudriñad las Escrituras — ellas son las que dan testimonio de mí.’",
  summary_fr:"Jésus déclare que les morts entendront sa voix et vivront. Il appelle quatre témoins : Jean-Baptiste, ses œuvres, le Père et les Écritures. ‘Vous sondez les Écritures — ce sont elles qui rendent témoignage de moi.’"},
{day:7,reading:"John 6:1–40",topic:"Feeding the 5,000 & Bread of Life",topic_es:"La alimentación de los 5.000 y el Pan de Vida",topic_fr:"La multiplication des pains et le Pain de Vie",
  summary:"Jesus feeds 5,000 with five loaves and two fish, then walks on water. ‘I am the bread of life. Whoever comes to me shall not hunger.’",
  summary_es:"Jesús alimenta a 5.000 con cinco panes y dos peces, y luego camina sobre el agua. ‘Yo soy el pan de vida; el que a mí viene, nunca tendrá hambre.’",
  summary_fr:"Jésus nourrit 5 000 personnes avec cinq pains et deux poissons, puis marche sur l’eau. ‘Je suis le pain de vie. Celui qui vient à moi n’aura jamais faim.’"},
{day:8,reading:"John 6:41–71",topic:"Hard Sayings & True Disciples",topic_es:"Palabras duras y verdaderos discípulos",topic_fr:"Paroles dures et vrais disciples",ph:2,
  summary:"Many grumble at Jesus’ teaching. ‘Unless you eat the flesh of the Son of Man and drink His blood, you have no life in you.’ Many turn back. Peter stays: ‘You have the words of eternal life.’",
  summary_es:"Muchos murmuran ante la enseñanza de Jesús. ‘Si no coméis la carne del Hijo del Hombre y bebéis su sangre, no tenéis vida en vosotros.’ Muchos se vuelven atrás. Pedro permanece: ‘Tú tienes palabras de vida eterna.’",
  summary_fr:"Beaucoup murmurent à l’enseignement de Jésus. ‘Si vous ne mangez la chair du Fils de l’homme et ne buvez son sang, vous n’avez point la vie en vous-mêmes.’ Beaucoup s’en retournent. Pierre reste : ‘Tu as les paroles de la vie éternelle.’"},
{day:9,reading:"John 7",topic:"Division at the Feast",topic_es:"División en la fiesta",topic_fr:"Division pendant la fête",
  summary:"Jesus goes to the Feast of Tabernacles. The crowds are divided — some say He is the Prophet, others say the Christ. ‘If anyone thirsts, let him come to me and drink.’",
  summary_es:"Jesús sube a la fiesta de los Tabernáculos. La multitud está dividida — unos dicen que es el Profeta, otros que el Cristo. ‘Si alguno tiene sed, venga a mí y beba.’",
  summary_fr:"Jésus monte à la fête des Tabernacles. La foule est divisée — certains disent qu’il est le Prophète, d’autres le Christ. ‘Si quelqu’un a soif, qu’il vienne à moi, et qu’il boive.’"},
{day:10,reading:"John 1–7",topic:"Re-Read: John 1–7",topic_es:"Relectura: Juan 1–7",topic_fr:"Relecture : Jean 1–7",
  summary:"Re-read the first seven chapters. From the Word made flesh through the feast. Watch the signs build, the opposition grow, and the ‘I AM’ claims sharpen. What did you miss the first time?",
  summary_es:"Relee los siete primeros capítulos. Desde el Verbo hecho carne hasta la fiesta. Observa cómo se acumulan las señales, crece la oposición y se afilan los ‘YO SOY’. ¿Qué se te pasó la primera vez?",
  summary_fr:"Relis les sept premiers chapitres. De la Parole faite chair jusqu’à la fête. Vois les signes s’accumuler, l’opposition grandir, et les ‘JE SUIS’ s’affirmer. Qu’as-tu manqué la première fois ?"},
{day:11,reading:"John 8:1–30",topic:"The Light of the World",topic_es:"La Luz del mundo",topic_fr:"La Lumière du monde",
  summary:"The woman caught in adultery — ‘Let him who is without sin cast the first stone.’ Jesus declares: ‘I am the light of the world. Whoever follows me will not walk in darkness.’",
  summary_es:"La mujer sorprendida en adulterio — ‘El que de vosotros esté sin pecado sea el primero en arrojar la piedra.’ Jesús declara: ‘Yo soy la luz del mundo; el que me sigue, no andará en tinieblas.’",
  summary_fr:"La femme prise en adultère — ‘Que celui qui est sans péché jette le premier la pierre.’ Jésus déclare : ‘Je suis la lumière du monde ; celui qui me suit ne marchera pas dans les ténèbres.’"},
{day:12,reading:"John 8:31–59",topic:"The Truth Will Set You Free",topic_es:"La verdad os hará libres",topic_fr:"La vérité vous affranchira",
  summary:"Jesus confronts the Pharisees about true freedom and true children of Abraham. ‘Before Abraham was, I AM.’ They pick up stones to throw at Him.",
  summary_es:"Jesús confronta a los fariseos sobre la verdadera libertad y los verdaderos hijos de Abraham. ‘Antes que Abraham fuese, YO SOY.’ Toman piedras para arrojárselas.",
  summary_fr:"Jésus confronte les pharisiens sur la vraie liberté et les vrais fils d’Abraham. ‘Avant qu’Abraham fût, JE SUIS.’ Ils prennent des pierres pour les lui jeter."},
{day:13,reading:"John 9",topic:"Healing the Man Born Blind",topic_es:"Sanidad del ciego de nacimiento",topic_fr:"Guérison de l’aveugle-né",
  summary:"Jesus heals a man blind from birth. The Pharisees interrogate him. ‘One thing I do know: I was blind, but now I see.’ Jesus reveals Himself as the Son of Man.",
  summary_es:"Jesús sana a un hombre ciego de nacimiento. Los fariseos lo interrogan. ‘Una cosa sé: que habiendo yo sido ciego, ahora veo.’ Jesús se revela como el Hijo del Hombre.",
  summary_fr:"Jésus guérit un homme aveugle de naissance. Les pharisiens l’interrogent. ‘Je sais une chose : c’est que j’étais aveugle, et maintenant je vois.’ Jésus se révèle comme le Fils de l’homme."},
{day:14,reading:"John 10:1–21",topic:"The Good Shepherd",topic_es:"El Buen Pastor",topic_fr:"Le Bon Berger",
  summary:"‘I am the good shepherd. The good shepherd lays down his life for the sheep.’ He knows His own and His own know Him. ‘I lay down my life that I may take it up again.’",
  summary_es:"‘Yo soy el buen pastor; el buen pastor su vida da por las ovejas.’ Conoce a las suyas y las suyas le conocen. ‘Yo pongo mi vida, para volverla a tomar.’",
  summary_fr:"‘Je suis le bon berger. Le bon berger donne sa vie pour ses brebis.’ Il connaît les siennes et les siennes le connaissent. ‘Je donne ma vie, afin de la reprendre.’"},
{day:15,reading:"John 10:22–42",topic:"Jesus and the Father Are One",topic_es:"Jesús y el Padre son uno",topic_fr:"Jésus et le Père sont un",ph:3,
  summary:"At the Feast of Dedication, Jesus declares: ‘I and the Father are one.’ They pick up stones again. ‘I give them eternal life, and they will never perish.’",
  summary_es:"En la fiesta de la Dedicación, Jesús declara: ‘Yo y el Padre uno somos.’ De nuevo toman piedras. ‘Yo les doy vida eterna; y no perecerán jamás.’",
  summary_fr:"À la fête de la Dédicace, Jésus déclare : ‘Moi et le Père nous sommes un.’ De nouveau ils prennent des pierres. ‘Je leur donne la vie éternelle ; et elles ne périront jamais.’"},
{day:16,reading:"John 11",topic:"The Resurrection and the Life",topic_es:"La Resurrección y la Vida",topic_fr:"La Résurrection et la Vie",
  summary:"Lazarus dies. Jesus weeps. Then He calls Lazarus out of the tomb. ‘I am the resurrection and the life. Whoever believes in me, though he die, yet shall he live.’",
  summary_es:"Lázaro muere. Jesús llora. Luego llama a Lázaro fuera del sepulcro. ‘Yo soy la resurrección y la vida; el que cree en mí, aunque esté muerto, vivirá.’",
  summary_fr:"Lazare meurt. Jésus pleure. Puis il appelle Lazare hors du tombeau. ‘Je suis la résurrection et la vie. Celui qui croit en moi vivra, quand même il serait mort.’"},
{day:17,reading:"John 12:1–26",topic:"Anointing at Bethany & Triumphal Entry",topic_es:"La unción en Betania y la Entrada Triunfal",topic_fr:"L’onction à Béthanie et l’entrée triomphale",
  summary:"Mary anoints Jesus’ feet with costly perfume. The crowd shouts Hosanna as He enters Jerusalem. ‘Unless a grain of wheat falls into the earth and dies, it remains alone.’",
  summary_es:"María unge los pies de Jesús con un perfume costoso. La multitud grita Hosanna cuando entra en Jerusalén. ‘Si el grano de trigo no cae en la tierra y muere, queda solo.’",
  summary_fr:"Marie oint les pieds de Jésus d’un parfum de grand prix. La foule crie Hosanna quand il entre à Jérusalem. ‘Si le grain de blé qui est tombé en terre ne meurt, il reste seul.’"},
{day:18,reading:"John 12:27–50",topic:"The Hour Has Come",topic_es:"La hora ha llegado",topic_fr:"L’heure est venue",
  summary:"Jesus’ soul is troubled. ‘Now is the judgment of this world; now will the ruler of this world be cast out.’ Despite the signs, many still do not believe.",
  summary_es:"El alma de Jesús está turbada. ‘Ahora es el juicio de este mundo; ahora el príncipe de este mundo será echado fuera.’ A pesar de las señales, muchos aún no creen.",
  summary_fr:"L’âme de Jésus est troublée. ‘Maintenant a lieu le jugement de ce monde ; maintenant le prince de ce monde sera jeté dehors.’ Malgré les signes, beaucoup ne croient toujours pas."},
{day:19,reading:"John 13",topic:"The Last Supper & Foot Washing",topic_es:"La Última Cena y el lavamiento de los pies",topic_fr:"La Cène et le lavement des pieds",
  summary:"Jesus washes the disciples’ feet — the King becomes the servant. ‘A new commandment I give to you: love one another as I have loved you.’ Judas departs into the night.",
  summary_es:"Jesús lava los pies de los discípulos — el Rey se hace siervo. ‘Un mandamiento nuevo os doy: que os améis unos a otros, como yo os he amado.’ Judas sale a la noche.",
  summary_fr:"Jésus lave les pieds de ses disciples — le Roi devient serviteur. ‘Je vous donne un commandement nouveau : aimez-vous les uns les autres, comme je vous ai aimés.’ Judas sort dans la nuit."},
{day:20,reading:"John 14:1–15",topic:"The Way, the Truth, the Life",topic_es:"El Camino, la Verdad y la Vida",topic_fr:"Le Chemin, la Vérité et la Vie",
  summary:"‘I am the way, the truth, and the life. No one comes to the Father except through me.’ ‘Whoever has seen me has seen the Father.’ Greater works than these you will do.",
  summary_es:"‘Yo soy el camino, y la verdad, y la vida; nadie viene al Padre, sino por mí.’ ‘El que me ha visto a mí, ha visto al Padre.’ Mayores obras que estas haréis.",
  summary_fr:"‘Je suis le chemin, la vérité et la vie. Nul ne vient au Père que par moi.’ ‘Celui qui m’a vu a vu le Père.’ Vous ferez de plus grandes œuvres que celles-ci."},
{day:21,reading:"John 14:16–31",topic:"The Promise of the Holy Spirit",topic_es:"La promesa del Espíritu Santo",topic_fr:"La promesse du Saint-Esprit",
  summary:"Jesus promises the Helper — the Spirit of truth who will be with them forever. ‘Peace I leave with you; my peace I give to you. Let not your hearts be troubled.’",
  summary_es:"Jesús promete al Consolador — el Espíritu de verdad que estará con ellos para siempre. ‘La paz os dejo, mi paz os doy. No se turbe vuestro corazón.’",
  summary_fr:"Jésus promet le Consolateur — l’Esprit de vérité qui demeurera avec eux pour toujours. ‘Je vous laisse la paix, je vous donne ma paix. Que votre cœur ne se trouble point.’"},
{day:22,reading:"John 8–14",topic:"Re-Read: John 8–14",topic_es:"Relectura: Juan 8–14",topic_fr:"Relecture : Jean 8–14",ph:4,
  summary:"Re-read John 8–14. Light of the world, good shepherd, resurrection and life, the way and truth. The upper room begins. Sit with these chapters again.",
  summary_es:"Relee Juan 8–14. Luz del mundo, buen pastor, resurrección y vida, camino y verdad. Comienza el aposento alto. Detente otra vez en estos capítulos.",
  summary_fr:"Relis Jean 8–14. Lumière du monde, bon berger, résurrection et vie, chemin et vérité. La chambre haute commence. Assieds-toi de nouveau dans ces chapitres."},
{day:23,reading:"John 15:1–17",topic:"The Vine and the Branches",topic_es:"La Vid y los pámpanos",topic_fr:"Le Cep et les sarments",
  summary:"‘I am the vine; you are the branches.’ Abide in Him and bear fruit. ‘Greater love has no one than this: that someone lay down his life for his friends.’",
  summary_es:"‘Yo soy la vid, vosotros los pámpanos.’ Permaneced en él y llevad fruto. ‘Nadie tiene mayor amor que este, que uno ponga su vida por sus amigos.’",
  summary_fr:"‘Je suis le cep, vous êtes les sarments.’ Demeurez en lui et portez du fruit. ‘Il n’y a pas de plus grand amour que de donner sa vie pour ses amis.’"},
{day:24,reading:"John 15:18–27",topic:"The World’s Hatred",topic_es:"El odio del mundo",topic_fr:"La haine du monde",
  summary:"‘If the world hates you, know that it has hated me before it hated you.’ You are not of the world. The Spirit of truth will bear witness about Jesus.",
  summary_es:"‘Si el mundo os aborrece, sabed que a mí me ha aborrecido antes que a vosotros.’ No sois del mundo. El Espíritu de verdad dará testimonio de Jesús.",
  summary_fr:"‘Si le monde vous hait, sachez qu’il m’a haï avant vous.’ Vous n’êtes pas du monde. L’Esprit de vérité rendra témoignage de Jésus."},
{day:25,reading:"John 16",topic:"The Spirit of Truth & Sorrow to Joy",topic_es:"El Espíritu de verdad y la tristeza convertida en gozo",topic_fr:"L’Esprit de vérité et la tristesse changée en joie",
  summary:"Jesus warns of persecution and promises the Spirit will guide them into all truth. ‘In the world you will have tribulation. But take heart; I have overcome the world.’",
  summary_es:"Jesús advierte de la persecución y promete que el Espíritu los guiará a toda verdad. ‘En el mundo tendréis aflicción; pero confiad, yo he vencido al mundo.’",
  summary_fr:"Jésus prévient de la persécution et promet que l’Esprit les conduira dans toute la vérité. ‘Vous aurez des tribulations dans le monde ; mais prenez courage, j’ai vaincu le monde.’"},
{day:26,reading:"John 17",topic:"Jesus’ High Priestly Prayer",topic_es:"La oración sumo sacerdotal de Jesús",topic_fr:"La prière sacerdotale de Jésus",
  summary:"Jesus prays for Himself, His disciples, and all who will believe. ‘Sanctify them in the truth; your word is truth.’ He prays for their unity and protection.",
  summary_es:"Jesús ora por sí mismo, por sus discípulos y por todos los que creerán. ‘Santifícalos en tu verdad; tu palabra es verdad.’ Pide por su unidad y protección.",
  summary_fr:"Jésus prie pour lui-même, pour ses disciples et pour tous ceux qui croiront. ‘Sanctifie-les par ta vérité : ta parole est la vérité.’ Il prie pour leur unité et leur protection."},
{day:27,reading:"John 18",topic:"Betrayal, Arrest & Peter’s Denial",topic_es:"Traición, arresto y la negación de Pedro",topic_fr:"Trahison, arrestation et reniement de Pierre",
  summary:"Judas betrays Jesus in the garden. Peter draws his sword, then denies Jesus three times. Jesus stands before Pilate: ‘My kingdom is not of this world.’",
  summary_es:"Judas traiciona a Jesús en el huerto. Pedro saca la espada y luego niega a Jesús tres veces. Jesús comparece ante Pilato: ‘Mi reino no es de este mundo.’",
  summary_fr:"Judas trahit Jésus au jardin. Pierre tire l’épée, puis renie Jésus trois fois. Jésus comparaît devant Pilate : ‘Mon royaume n’est pas de ce monde.’"},
{day:28,reading:"John 19",topic:"The Crucifixion",topic_es:"La Crucifixión",topic_fr:"La Crucifixion",
  summary:"Jesus is scourged, crowned with thorns, and crucified. ‘It is finished.’ The Lamb of God takes away the sin of the world. Joseph and Nicodemus bury Him.",
  summary_es:"Jesús es azotado, coronado de espinas y crucificado. ‘Consumado es.’ El Cordero de Dios quita el pecado del mundo. José y Nicodemo lo sepultan.",
  summary_fr:"Jésus est flagellé, couronné d’épines et crucifié. ‘Tout est accompli.’ L’Agneau de Dieu ôte le péché du monde. Joseph et Nicodème l’ensevelissent."},
{day:29,reading:"John 20",topic:"The Resurrection",topic_es:"La Resurrección",topic_fr:"La Résurrection",
  summary:"The empty tomb. Mary sees the risen Lord. Jesus appears to the disciples and to Thomas. ‘My Lord and my God!’ ‘Blessed are those who have not seen and yet have believed.’",
  summary_es:"La tumba vacía. María ve al Señor resucitado. Jesús se aparece a los discípulos y a Tomás. ‘¡Señor mío, y Dios mío!’ ‘Bienaventurados los que no vieron, y creyeron.’",
  summary_fr:"Le tombeau vide. Marie voit le Seigneur ressuscité. Jésus apparaît aux disciples et à Thomas. ‘Mon Seigneur et mon Dieu !’ ‘Heureux ceux qui n’ont pas vu, et qui ont cru !’"},
{day:30,reading:"John 21",topic:"Restoration of Peter",topic_es:"La restauración de Pedro",topic_fr:"La restauration de Pierre",
  summary:"Jesus appears at the Sea of Galilee. The miraculous catch. Three times He asks Peter: ‘Do you love me?’ Three times: ‘Feed my sheep.’ Peter is restored.",
  summary_es:"Jesús se aparece junto al mar de Galilea. La pesca milagrosa. Tres veces pregunta a Pedro: ‘¿Me amas?’ Tres veces: ‘Apacienta mis ovejas.’ Pedro es restaurado.",
  summary_fr:"Jésus apparaît au bord de la mer de Galilée. La pêche miraculeuse. Trois fois il demande à Pierre : ‘M’aimes-tu ?’ Trois fois : ‘Pais mes brebis.’ Pierre est restauré."}
],
  verses: {
1:{r:"John 3:16",r_es:"Juan 3:16",r_fr:"Jean 3:16",
  t:"For God so loved the world, that he gave his only Son, that whoever believes in him should not perish but have eternal life.",
  t_es:"Porque de tal manera amó Dios al mundo, que ha dado a su Hijo unigénito, para que todo aquel que en él cree, no se pierda, mas tenga vida eterna.",
  t_fr:"Car Dieu a tant aimé le monde qu’il a donné son Fils unique, afin que quiconque croit en lui ne périsse point, mais qu’il ait la vie éternelle."},
8:{r:"John 10:30",r_es:"Juan 10:30",r_fr:"Jean 10:30",
  t:"I and the Father are one.",
  t_es:"Yo y el Padre uno somos.",
  t_fr:"Moi et le Père nous sommes un."},
15:{r:"John 15:13",r_es:"Juan 15:13",r_fr:"Jean 15:13",
  t:"Greater love has no one than this, that someone lay down his life for his friends.",
  t_es:"Nadie tiene mayor amor que este, que uno ponga su vida por sus amigos.",
  t_fr:"Il n’y a pas de plus grand amour que de donner sa vie pour ses amis."},
22:{r:"John 17:17",r_es:"Juan 17:17",r_fr:"Jean 17:17",
  t:"Sanctify them in the truth; your word is truth.",
  t_es:"Santifícalos en tu verdad; tu palabra es verdad.",
  t_fr:"Sanctifie-les par ta vérité : ta parole est la vérité."}
},
  checks: [
  {k:"read",l:"Read the passage",l_es:"Lee el pasaje",l_fr:"Lis le passage"},
  {k:"pray",l:"Pray & journal",l_es:"Ora y escribe en tu diario",l_fr:"Prie et tiens un journal"},
  {k:"workout",l:"Workout (3–5x/week)",l_es:"Entrena (3–5x por semana)",l_fr:"Entraîne-toi (3–5x par semaine)"},
  {k:"abstain",l:"Abstain from your one thing",l_es:"Abstente de aquello que decidiste",l_fr:"Abstiens-toi de ta seule chose"},
  {k:"marco",l:"Marco Polo update",l_es:"Mensaje en Marco Polo",l_fr:"Mise à jour Marco Polo"}
]
};
