// Iron Sharpens Iron v2.2.0 — New Testament Letters Config (en/es/fr)
window.PLAN = {
  title: "New Testament Letters",
  title_es: "Cartas del Nuevo Testamento",
  title_fr: "Lettres du Nouveau Testament",
  subtitle: "NEW TESTAMENT LETTERS — 30-DAY CHALLENGE",
  subtitle_es: "CARTAS DEL NUEVO TESTAMENTO — RETO DE 30 DÍAS",
  subtitle_fr: "LETTRES DU NOUVEAU TESTAMENT — DÉFI DE 30 JOURS",
  storageKey: "isi-july-v1",
  startDate: "2026-07-01",
  totalDays: 30,
  days: [
{day:1,reading:"Galatians 1",topic:"Paul’s Apostleship & the True Gospel",topic_es:"El apostolado de Pablo y el verdadero evangelio",topic_fr:"L’apostolat de Paul et le vrai évangile",ph:1,
  summary:"For am I now seeking the approval of man, or of God? Or am I trying to please man? If I were still trying to please man, I would not be a servant of Christ.",
  summary_es:"Pues, ¿busco ahora el favor de los hombres, o el de Dios? ¿O trato de agradar a los hombres? Pues si todavía agradara a los hombres, no sería siervo de Cristo.",
  summary_fr:"Et maintenant, est-ce la faveur des hommes que je désire, ou celle de Dieu ? Est-ce que je cherche à plaire aux hommes ? Si je plaisais encore aux hommes, je ne serais pas serviteur de Christ."},
{day:2,reading:"Galatians 2",topic:"Justified by Faith, Not Works",topic_es:"Justificados por la fe, no por las obras",topic_fr:"Justifiés par la foi, non par les œuvres",
  summary:"yet we know that a person is not justified by works of the law but through faith in Jesus Christ, so we also have believed in Christ Jesus, in order to be justified by faith in Christ and not by works of the law, because by works of the law no one will be justified.",
  summary_es:"sabiendo que el hombre no es justificado por las obras de la ley, sino por la fe de Jesucristo, nosotros también hemos creído en Jesucristo, para ser justificados por la fe de Cristo y no por las obras de la ley, por cuanto por las obras de la ley nadie será justificado.",
  summary_fr:"Néanmoins, sachant que ce n’est pas par les œuvres de la loi que l’homme est justifié, mais par la foi en Jésus-Christ, nous aussi nous avons cru en Jésus-Christ, afin d’être justifiés par la foi en Christ et non par les œuvres de la loi, parce que nulle chair ne sera justifiée par les œuvres de la loi."},
{day:3,reading:"Galatians 3",topic:"Sons of God Through Faith",topic_es:"Hijos de Dios por la fe",topic_fr:"Fils de Dieu par la foi",
  summary:"for in Christ Jesus you are all sons of God, through faith.",
  summary_es:"pues todos sois hijos de Dios por la fe en Cristo Jesús;",
  summary_fr:"Car vous êtes tous fils de Dieu par la foi en Jésus-Christ;"},
{day:4,reading:"Galatians 4",topic:"Heirs, Not Slaves",topic_es:"Herederos, no esclavos",topic_fr:"Héritiers, non esclaves",
  summary:"So you are no longer a slave, but a son, and if a son, then an heir through God.",
  summary_es:"Así que ya no eres esclavo, sino hijo; y si hijo, también heredero de Dios por medio de Cristo.",
  summary_fr:"Ainsi tu n’es plus esclave, mais fils; et si tu es fils, tu es aussi héritier par la grâce de Dieu."},
{day:5,reading:"Galatians 5",topic:"Walk by the Spirit",topic_es:"Andad en el Espíritu",topic_fr:"Marchez par l’Esprit",
  summary:"But the fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, self-control; against such things there is no law.",
  summary_es:"Mas el fruto del Espíritu es amor, gozo, paz, paciencia, benignidad, bondad, fe, mansedumbre, templanza; contra tales cosas no hay ley.",
  summary_fr:"Mais le fruit de l’Esprit, c’est l’amour, la joie, la paix, la patience, la bonté, la bénignité, la fidélité, la douceur, la tempérance; la loi n’est pas contre ces choses."},
{day:6,reading:"Galatians 6",topic:"Bear One Another’s Burdens",topic_es:"Sobrellevad los unos las cargas de los otros",topic_fr:"Portez les fardeaux les uns des autres",
  summary:"Bear one another’s burdens, and so fulfill the law of Christ.",
  summary_es:"Sobrellevad los unos las cargas de los otros, y cumplid así la ley de Cristo.",
  summary_fr:"Portez les fardeaux les uns des autres, et vous accomplirez ainsi la loi de Christ."},
{day:7,reading:"Galatians 1–6",topic:"Galatians Re-Read",topic_es:"Relectura de Gálatas",topic_fr:"Relecture des Galates",
  summary:"For freedom Christ has set us free; stand firm therefore, and do not submit again to a yoke of slavery.",
  summary_es:"Estad, pues, firmes en la libertad con que Cristo nos hizo libres, y no estéis otra vez sujetos al yugo de esclavitud.",
  summary_fr:"C’est pour la liberté que Christ nous a affranchis. Demeurez donc fermes, et ne vous laissez pas mettre de nouveau sous le joug de la servitude."},
{day:8,reading:"Ephesians 1",topic:"Every Spiritual Blessing in Christ",topic_es:"Toda bendición espiritual en Cristo",topic_fr:"Toute bénédiction spirituelle en Christ",ph:2,
  summary:"Blessed be the God and Father of our Lord Jesus Christ, who has blessed us in Christ with every spiritual blessing in the heavenly places,",
  summary_es:"Bendito sea el Dios y Padre de nuestro Señor Jesucristo, que nos bendijo con toda bendición espiritual en los lugares celestiales en Cristo,",
  summary_fr:"Béni soit Dieu, le Père de notre Seigneur Jésus-Christ, qui nous a bénis de toutes sortes de bénédictions spirituelles dans les lieux célestes en Christ !"},
{day:9,reading:"Ephesians 2",topic:"Saved by Grace Through Faith",topic_es:"Salvos por gracia por medio de la fe",topic_fr:"Sauvés par la grâce, par le moyen de la foi",
  summary:"But God, being rich in mercy, because of the great love with which he loved us, even when we were dead in our trespasses, made us alive together with Christ — by grace you have been saved —",
  summary_es:"Pero Dios, que es rico en misericordia, por su gran amor con que nos amó, aun estando nosotros muertos en pecados, nos dio vida juntamente con Cristo (por gracia sois salvos),",
  summary_fr:"Mais Dieu, qui est riche en miséricorde, à cause du grand amour dont il nous a aimés, nous qui étions morts par nos offenses, nous a rendus à la vie avec Christ (c’est par grâce que vous êtes sauvés);"},
{day:10,reading:"Ephesians 3",topic:"The Mystery of Christ Revealed",topic_es:"El misterio de Cristo revelado",topic_fr:"Le mystère du Christ révélé",
  summary:"Now to him who is able to do far more abundantly than all that we ask or think, according to the power at work within us, to him be glory in the church and in Christ Jesus throughout all generations, forever and ever. Amen.",
  summary_es:"Y a Aquel que es poderoso para hacer todas las cosas mucho más abundantemente de lo que pedimos o entendemos, según el poder que actúa en nosotros, a él sea gloria en la iglesia en Cristo Jesús por todas las edades, por los siglos de los siglos. Amén.",
  summary_fr:"Or, à celui qui peut faire, par la puissance qui agit en nous, infiniment au delà de tout ce que nous demandons ou pensons, à lui soit la gloire dans l’Église et en Jésus-Christ, dans toutes les générations, aux siècles des siècles ! Amen !"},
{day:11,reading:"Ephesians 4",topic:"Unity & the New Self",topic_es:"Unidad y el nuevo hombre",topic_fr:"Unité et l’homme nouveau",
  summary:"Be kind to one another, tenderhearted, forgiving one another, as God in Christ forgave you.",
  summary_es:"Antes sed benignos unos con otros, misericordiosos, perdonándoos unos a otros, como Dios también os perdonó a vosotros en Cristo.",
  summary_fr:"Soyez bons les uns envers les autres, compatissants, vous pardonnant réciproquement, comme Dieu vous a pardonné en Christ."},
{day:12,reading:"Ephesians 5",topic:"Walk in Love & Light",topic_es:"Andad en amor y en luz",topic_fr:"Marchez dans l’amour et la lumière",
  summary:"for at one time you were darkness, but now you are light in the Lord. Walk as children of light",
  summary_es:"Porque en otro tiempo erais tinieblas, mas ahora sois luz en el Señor; andad como hijos de luz",
  summary_fr:"Autrefois vous étiez ténèbres, et maintenant vous êtes lumière dans le Seigneur. Marchez comme des enfants de lumière !"},
{day:13,reading:"Ephesians 6",topic:"The Armor of God",topic_es:"La armadura de Dios",topic_fr:"L’armure de Dieu",
  summary:"Put on the whole armor of God, that you may be able to stand against the schemes of the devil.",
  summary_es:"Vestíos de toda la armadura de Dios, para que podáis estar firmes contra las asechanzas del diablo.",
  summary_fr:"Revêtez-vous de toutes les armes de Dieu, afin de pouvoir tenir ferme contre les ruses du diable."},
{day:14,reading:"Ephesians 1–6",topic:"Ephesians Re-Read",topic_es:"Relectura de Efesios",topic_fr:"Relecture des Éphésiens",
  summary:"I therefore, a prisoner for the Lord, urge you to walk in a manner worthy of the calling to which you have been called,",
  summary_es:"Yo pues, preso en el Señor, os ruego que andéis como es digno de la vocación con que fuisteis llamados,",
  summary_fr:"Je vous exhorte donc, moi, le prisonnier dans le Seigneur, à marcher d’une manière digne de la vocation qui vous a été adressée,"},
{day:15,reading:"Philippians 1",topic:"To Live Is Christ",topic_es:"El vivir es Cristo",topic_fr:"Vivre, c’est Christ",ph:3,
  summary:"And I am sure of this, that he who began a good work in you will bring it to completion at the day of Jesus Christ.",
  summary_es:"estando persuadido de esto, que el que comenzó en vosotros la buena obra, la perfeccionará hasta el día de Jesucristo;",
  summary_fr:"Je suis persuadé que celui qui a commencé en vous cette bonne œuvre la rendra parfaite pour le jour de Jésus-Christ."},
{day:16,reading:"Philippians 2:1–12",topic:"The Mind of Christ",topic_es:"El sentir de Cristo",topic_fr:"La pensée du Christ",
  summary:"Have this mind among yourselves, which is yours in Christ Jesus,",
  summary_es:"Haya, pues, en vosotros este sentir que hubo también en Cristo Jesús,",
  summary_fr:"Ayez en vous les sentiments qui étaient en Jésus-Christ,"},
{day:17,reading:"Philippians 2:13–30",topic:"Working Out Your Salvation",topic_es:"Ocupaos en vuestra salvación",topic_fr:"Travailler à votre salut",
  summary:"for it is God who works in you, both to will and to work for his good pleasure.",
  summary_es:"porque Dios es el que en vosotros produce así el querer como el hacer, por su buena voluntad.",
  summary_fr:"car c’est Dieu qui produit en vous le vouloir et le faire, selon son bon plaisir."},
{day:18,reading:"Philippians 3",topic:"Pressing Toward the Goal",topic_es:"Prosiguiendo hacia la meta",topic_fr:"Courir vers le but",
  summary:"Brothers, I do not consider that I have made it my own. But one thing I do: forgetting what lies behind and straining forward to what lies ahead, I press on toward the goal for the prize of the upward call of God in Christ Jesus.",
  summary_es:"Hermanos, yo mismo no pretendo haberlo ya alcanzado; pero una cosa hago: olvidando ciertamente lo que queda atrás, y extendiéndome a lo que está delante, prosigo a la meta, al premio del supremo llamamiento de Dios en Cristo Jesús.",
  summary_fr:"Frères, je ne pense pas l’avoir saisi; mais je fais une chose: oubliant ce qui est en arrière et me portant vers ce qui est en avant, je cours vers le but, pour remporter le prix de la vocation céleste de Dieu en Jésus-Christ."},
{day:19,reading:"Philippians 4:1–9",topic:"Rejoice & the Peace of God",topic_es:"Regocijaos y la paz de Dios",topic_fr:"Réjouissez-vous et la paix de Dieu",
  summary:"do not be anxious about anything, but in everything by prayer and supplication with thanksgiving let your requests be made known to God. And the peace of God, which surpasses all understanding, will guard your hearts and your minds in Christ Jesus.",
  summary_es:"Por nada estéis afanosos, sino sean conocidas vuestras peticiones delante de Dios en toda oración y ruego, con acción de gracias. Y la paz de Dios, que sobrepasa todo entendimiento, guardará vuestros corazones y vuestros pensamientos en Cristo Jesús.",
  summary_fr:"Ne vous inquiétez de rien; mais en toute chose faites connaître vos besoins à Dieu par des prières et des supplications, avec des actions de grâces. Et la paix de Dieu, qui surpasse toute intelligence, gardera vos cœurs et vos pensées en Jésus-Christ."},
{day:20,reading:"Philippians 4:10–23",topic:"Contentment in Christ",topic_es:"Contentamiento en Cristo",topic_fr:"Le contentement en Christ",
  summary:"Not that I am speaking of being in need, for I have learned, in whatever situation I am, to be content.",
  summary_es:"No lo digo porque tenga escasez, pues he aprendido a contentarme, cualquiera que sea mi situación.",
  summary_fr:"Ce n’est pas en vue de mes besoins que je dis cela, car j’ai appris à être content de l’état où je me trouve."},
{day:21,reading:"Philippians 1–4",topic:"Philippians Re-Read",topic_es:"Relectura de Filipenses",topic_fr:"Relecture des Philippiens",
  summary:"Rejoice in the Lord always; again I will say, rejoice.",
  summary_es:"Regocijaos en el Señor siempre. Otra vez digo: ¡Regocijaos!",
  summary_fr:"Réjouissez-vous toujours dans le Seigneur; je le répète, réjouissez-vous."},
{day:22,reading:"Colossians 1–4",topic:"Colossians Overview",topic_es:"Vista general de Colosenses",topic_fr:"Vue d’ensemble des Colossiens",
  summary:"And he is before all things, and in him all things hold together.",
  summary_es:"Y él es antes de todas las cosas, y todas las cosas en él subsisten;",
  summary_fr:"Il est avant toutes choses, et toutes choses subsistent en lui."},
{day:23,reading:"Colossians 1:1–14",topic:"Thanksgiving & Prayer",topic_es:"Acción de gracias y oración",topic_fr:"Action de grâces et prière",ph:4,
  summary:"He has delivered us from the domain of darkness and transferred us to the kingdom of his beloved Son, in whom we have redemption, the forgiveness of sins.",
  summary_es:"el cual nos ha librado de la potestad de las tinieblas, y trasladado al reino de su amado Hijo, en quien tenemos redención por su sangre, el perdón de pecados.",
  summary_fr:"qui nous a délivrés de la puissance des ténèbres et nous a transportés dans le royaume du Fils de son amour, en qui nous avons la rédemption, la rémission des péchés."},
{day:24,reading:"Colossians 1:15–23",topic:"The Supremacy of Christ",topic_es:"La supremacía de Cristo",topic_fr:"La suprématie du Christ",
  summary:"He is the image of the invisible God, the firstborn of all creation.",
  summary_es:"Él es la imagen del Dios invisible, el primogénito de toda creación.",
  summary_fr:"Il est l’image du Dieu invisible, le premier-né de toute la création."},
{day:25,reading:"Colossians 2",topic:"Rooted in Christ, Not Tradition",topic_es:"Arraigados en Cristo, no en la tradición",topic_fr:"Enracinés en Christ, non dans la tradition",
  summary:"Therefore, as you received Christ Jesus the Lord, so walk in him, rooted and built up in him and established in the faith, just as you were taught, abounding in thanksgiving.",
  summary_es:"Por tanto, de la manera que habéis recibido al Señor Jesucristo, andad en él; arraigados y sobreedificados en él, y confirmados en la fe, así como habéis sido enseñados, abundando en acciones de gracias.",
  summary_fr:"Ainsi donc, comme vous avez reçu le Seigneur Jésus-Christ, marchez en lui, étant enracinés et fondés en lui, et affermis par la foi, d’après les instructions qui vous ont été données, et abondez en actions de grâces."},
{day:26,reading:"Colossians 3:1–11",topic:"Set Your Mind on Things Above",topic_es:"Poned la mira en las cosas de arriba",topic_fr:"Affectionnez-vous aux choses d’en haut",
  summary:"If then you have been raised with Christ, seek the things that are above, where Christ is, seated at the right hand of God.",
  summary_es:"Si, pues, habéis resucitado con Cristo, buscad las cosas de arriba, donde está Cristo sentado a la diestra de Dios.",
  summary_fr:"Si donc vous êtes ressuscités avec Christ, cherchez les choses d’en haut, où Christ est assis à la droite de Dieu."},
{day:27,reading:"Colossians 3:12–17",topic:"Put On the New Self",topic_es:"Vestíos del nuevo hombre",topic_fr:"Revêtez-vous de l’homme nouveau",
  summary:"And above all these put on love, which binds everything together in perfect harmony.",
  summary_es:"Y sobre todas estas cosas vestíos de amor, que es el vínculo perfecto.",
  summary_fr:"Mais par-dessus toutes ces choses revêtez-vous de la charité, qui est le lien de la perfection."},
{day:28,reading:"Colossians 3:18–25",topic:"Christian Relationships",topic_es:"Relaciones cristianas",topic_fr:"Relations chrétiennes",
  summary:"Whatever you do, work heartily, as for the Lord and not for men,",
  summary_es:"Y todo lo que hagáis, hacedlo de corazón, como para el Señor y no para los hombres;",
  summary_fr:"Tout ce que vous faites, faites-le de bon cœur, comme pour le Seigneur et non pour des hommes,"},
{day:29,reading:"Colossians 4",topic:"Final Greetings & Prayer",topic_es:"Saludos finales y oración",topic_fr:"Salutations finales et prière",
  summary:"Continue steadfastly in prayer, being watchful in it with thanksgiving.",
  summary_es:"Perseverad en la oración, velando en ella con acción de gracias;",
  summary_fr:"Persévérez dans la prière, veillez-y avec actions de grâces."},
{day:30,reading:"Colossians 1–4",topic:"Colossians Re-Read",topic_es:"Relectura de Colosenses",topic_fr:"Relecture des Colossiens",
  summary:"And whatever you do, in word or deed, do everything in the name of the Lord Jesus, giving thanks to God the Father through him.",
  summary_es:"Y todo lo que hacéis, sea de palabra o de hecho, hacedlo todo en el nombre del Señor Jesús, dando gracias a Dios Padre por medio de él.",
  summary_fr:"Et quoi que vous fassiez, en parole ou en œuvre, faites tout au nom du Seigneur Jésus, en rendant par lui des actions de grâces à Dieu le Père."}
],
  verses: {
1:{r:"Galatians 2:20",r_es:"Gálatas 2:20",r_fr:"Galates 2:20",
  t:"I have been crucified with Christ. It is no longer I who live, but Christ who lives in me. And the life I now live in the flesh I live by faith in the Son of God, who loved me and gave himself for me.",
  t_es:"Con Cristo estoy juntamente crucificado, y ya no vivo yo, mas vive Cristo en mí; y lo que ahora vivo en la carne, lo vivo en la fe del Hijo de Dios, el cual me amó y se entregó a sí mismo por mí.",
  t_fr:"J’ai été crucifié avec Christ ; et si je vis, ce n’est plus moi qui vis, c’est Christ qui vit en moi ; si je vis maintenant dans la chair, je vis dans la foi au Fils de Dieu, qui m’a aimé et qui s’est livré lui-même pour moi."},
8:{r:"Ephesians 2:8–9",r_es:"Efesios 2:8–9",r_fr:"Éphésiens 2:8–9",
  t:"For by grace you have been saved through faith. And this is not your own doing; it is the gift of God, not a result of works, so that no one may boast.",
  t_es:"Porque por gracia sois salvos por medio de la fe; y esto no de vosotros, pues es don de Dios; no por obras, para que nadie se gloríe.",
  t_fr:"Car c’est par la grâce que vous êtes sauvés, par le moyen de la foi. Et cela ne vient pas de vous, c’est le don de Dieu. Ce n’est point par les œuvres, afin que personne ne se glorifie."},
15:{r:"Philippians 1:21",r_es:"Filipenses 1:21",r_fr:"Philippiens 1:21",
  t:"For to me to live is Christ, and to die is gain.",
  t_es:"Porque para mí el vivir es Cristo, y el morir es ganancia.",
  t_fr:"car Christ est ma vie, et la mort m’est un gain."},
23:{r:"Colossians 3:2–3",r_es:"Colosenses 3:2–3",r_fr:"Colossiens 3:2–3",
  t:"Set your minds on things that are above, not on things that are on earth. For you have died, and your life is hidden with Christ in God.",
  t_es:"Poned la mira en las cosas de arriba, no en las de la tierra. Porque habéis muerto, y vuestra vida está escondida con Cristo en Dios.",
  t_fr:"Affectionnez-vous aux choses d’en haut, et non à celles qui sont sur la terre. Car vous êtes morts, et votre vie est cachée avec Christ en Dieu."}
},
  checks: [
  {k:"read",l:"Read the passage",l_es:"Lee el pasaje",l_fr:"Lis le passage"},
  {k:"pray",l:"Pray & journal",l_es:"Ora y escribe en tu diario",l_fr:"Prie et tiens un journal"},
  {k:"workout",l:"Workout (3–5x/week)",l_es:"Entrena (3–5x por semana)",l_fr:"Entraînement (3–5x par semaine)"},
  {k:"abstain",l:"Abstain from your one thing",l_es:"Abstente de aquello que decidiste",l_fr:"Abstiens-toi de la chose que tu as choisie"},
  {k:"marco",l:"Marco Polo update",l_es:"Mensaje en Marco Polo",l_fr:"Mise à jour Marco Polo"}
]
};
