// Iron Sharpens Iron v2.2.0 — New Testament Letters Config (en/es/fr)
window.PLAN = {
  title: "New Testament Letters",
  title_es: "Cartas del Nuevo Testamento",
  title_fr: "Lettres du Nouveau Testament",
  subtitle: "NEW TESTAMENT LETTERS — 30-DAY CHALLENGE",
  subtitle_es: "CARTAS DEL NUEVO TESTAMENTO — RETO DE 30 DÍAS",
  subtitle_fr: "LETTRES DU NOUVEAU TESTAMENT — DÉFI DE 30 JOURS",
  storageKey: "isi-july-v1",
  startDate: "2026-07-01",
  totalDays: 30,
  days: [
{day:1,reading:"Galatians 1",topic:"Paul’s Apostleship & the True Gospel",topic_es:"El apostolado de Pablo y el verdadero evangelio",topic_fr:"L’apostolat de Paul et le vrai évangile",ph:1,
  summary:"Paul, an apostle — not from men nor through man, but through Jesus Christ and God the Father, who raised him from the dead —",
  summary_es:"Pablo, apóstol (no de hombres ni por hombre, sino por Jesucristo y por Dios el Padre que lo resucitó de los muertos),",
  summary_fr:"Paul, apôtre, non de la part des hommes, ni par un homme, mais par Jésus-Christ et Dieu le Père, qui l’a ressuscité des morts,"},
{day:2,reading:"Galatians 2",topic:"Justified by Faith, Not Works",topic_es:"Justificados por la fe, no por las obras",topic_fr:"Justifiés par la foi, non par les œuvres",
  summary:"Then after fourteen years I went up again to Jerusalem with Barnabas, taking Titus along with me.",
  summary_es:"Después, pasados catorce años, subí otra vez a Jerusalén con Bernabé, llevando también conmigo a Tito.",
  summary_fr:"Quatorze ans après, je montai de nouveau à Jérusalem avec Barnabas, ayant aussi pris Tite avec moi ;"},
{day:3,reading:"Galatians 3",topic:"Sons of God Through Faith",topic_es:"Hijos de Dios por la fe",topic_fr:"Fils de Dieu par la foi",
  summary:"O foolish Galatians! Who has bewitched you? It was before your eyes that Jesus Christ was publicly portrayed as crucified.",
  summary_es:"¡Oh gálatas insensatos! ¿quién os fascinó para no obedecer a la verdad, a vosotros ante cuyos ojos Jesucristo fue ya presentado claramente entre vosotros como crucificado?",
  summary_fr:"Ô Galates dépourvus de sens ! qui vous a fascinés, vous, aux yeux de qui Jésus-Christ a été peint comme crucifié ?"},
{day:4,reading:"Galatians 4",topic:"Heirs, Not Slaves",topic_es:"Herederos, no esclavos",topic_fr:"Héritiers, non esclaves",
  summary:"I mean that the heir, as long as he is a child, is no different from a slave, though he is the owner of everything,",
  summary_es:"Pero también digo: Entre tanto que el heredero es niño, en nada difiere del esclavo, aunque es señor de todo;",
  summary_fr:"Or, aussi longtemps que l’héritier est enfant, je dis qu’il ne diffère en rien d’un esclave, quoiqu’il soit le maître de tout ;"},
{day:5,reading:"Galatians 5",topic:"Walk by the Spirit",topic_es:"Andad en el Espíritu",topic_fr:"Marchez par l’Esprit",
  summary:"For freedom Christ has set us free; stand firm therefore, and do not submit again to a yoke of slavery.",
  summary_es:"Estad, pues, firmes en la libertad con que Cristo nos hizo libres, y no estéis otra vez sujetos al yugo de esclavitud.",
  summary_fr:"C’est pour la liberté que Christ nous a affranchis. Demeurez donc fermes, et ne vous laissez pas mettre de nouveau sous le joug de la servitude."},
{day:6,reading:"Galatians 6",topic:"Bear One Another’s Burdens",topic_es:"Sobrellevad los unos las cargas de los otros",topic_fr:"Portez les fardeaux les uns des autres",
  summary:"Brothers, if anyone is caught in any transgression, you who are spiritual should restore him in a spirit of gentleness. Keep watch on yourself, lest you too be tempted.",
  summary_es:"Hermanos, si alguno fuere sorprendido en alguna falta, vosotros que sois espirituales, restauradle con espíritu de mansedumbre, considerándote a ti mismo, no sea que tú también seas tentado.",
  summary_fr:"Frères, si un homme vient à être surpris en quelque faute, vous qui êtes spirituels, redressez-le avec un esprit de douceur. Prends garde à toi-même, de peur que tu ne sois aussi tenté."},
{day:7,reading:"Galatians 1–6",topic:"Galatians Re-Read",topic_es:"Relectura de Gálatas",topic_fr:"Relecture des Galates",
  summary:"Read all six chapters of Galatians in one sitting. Watch the argument build: gospel defended, faith over works, freedom in Christ, walk by the Spirit.",
  summary_es:"Lee los seis capítulos de Gálatas de una sola vez. Observa cómo se construye el argumento: el evangelio defendido, la fe sobre las obras, la libertad en Cristo, andar en el Espíritu.",
  summary_fr:"Lis les six chapitres des Galates d’une traite. Vois l’argument se construire : l’évangile défendu, la foi par-dessus les œuvres, la liberté en Christ, marcher par l’Esprit."},
{day:8,reading:"Ephesians 1",topic:"Every Spiritual Blessing in Christ",topic_es:"Toda bendición espiritual en Cristo",topic_fr:"Toute bénédiction spirituelle en Christ",ph:2,
  summary:"Paul, an apostle of Christ Jesus by the will of God, To the saints who are in Ephesus, and are faithful in Christ Jesus:",
  summary_es:"Pablo, apóstol de Jesucristo por la voluntad de Dios, a los santos y fieles en Cristo Jesús que están en Éfeso:",
  summary_fr:"Paul, apôtre de Jésus-Christ par la volonté de Dieu, aux saints qui sont à Éphèse et aux fidèles en Jésus-Christ :"},
{day:9,reading:"Ephesians 2",topic:"Saved by Grace Through Faith",topic_es:"Salvos por gracia por medio de la fe",topic_fr:"Sauvés par la grâce, par le moyen de la foi",
  summary:"And you were dead in the trespasses and sins",
  summary_es:"Y él os dio vida a vosotros, cuando estabais muertos en vuestros delitos y pecados,",
  summary_fr:"Vous étiez morts par vos offenses et par vos péchés,"},
{day:10,reading:"Ephesians 3",topic:"The Mystery of Christ Revealed",topic_es:"El misterio de Cristo revelado",topic_fr:"Le mystère du Christ révélé",
  summary:"For this reason I, Paul, a prisoner for Christ Jesus on behalf of you Gentiles —",
  summary_es:"Por esta causa yo Pablo, prisionero de Cristo Jesús por vosotros los gentiles;",
  summary_fr:"À cause de cela, moi Paul, le prisonnier de Christ pour vous païens…"},
{day:11,reading:"Ephesians 4",topic:"Unity & the New Self",topic_es:"Unidad y el nuevo hombre",topic_fr:"Unité et l’homme nouveau",
  summary:"I therefore, a prisoner for the Lord, urge you to walk in a manner worthy of the calling to which you have been called,",
  summary_es:"Yo pues, preso en el Señor, os ruego que andéis como es digno de la vocación con que fuisteis llamados,",
  summary_fr:"Je vous exhorte donc, moi, le prisonnier dans le Seigneur, à marcher d’une manière digne de la vocation qui vous a été adressée,"},
{day:12,reading:"Ephesians 5",topic:"Walk in Love & Light",topic_es:"Andad en amor y en luz",topic_fr:"Marchez dans l’amour et la lumière",
  summary:"Therefore be imitators of God, as beloved children.",
  summary_es:"Sed, pues, imitadores de Dios como hijos amados.",
  summary_fr:"Devenez donc les imitateurs de Dieu, comme des enfants bien-aimés ;"},
{day:13,reading:"Ephesians 6",topic:"The Armor of God",topic_es:"La armadura de Dios",topic_fr:"L’armure de Dieu",
  summary:"Children, obey your parents in the Lord, for this is right.",
  summary_es:"Hijos, obedeced en el Señor a vuestros padres, porque esto es justo.",
  summary_fr:"Enfants, obéissez à vos parents, selon le Seigneur, car cela est juste."},
{day:14,reading:"Ephesians 1–6",topic:"Ephesians Re-Read",topic_es:"Relectura de Efesios",topic_fr:"Relecture des Éphésiens",
  summary:"Read all six chapters of Ephesians in one sitting. The blessing, the gospel, the church, the walk, the armor — one cohesive vision.",
  summary_es:"Lee los seis capítulos de Efesios de una sola vez. La bendición, el evangelio, la iglesia, el andar, la armadura — una visión coherente.",
  summary_fr:"Lis les six chapitres des Éphésiens d’une traite. La bénédiction, l’évangile, l’Église, la marche, l’armure — une vision cohérente."},
{day:15,reading:"Philippians 1",topic:"To Live Is Christ",topic_es:"El vivir es Cristo",topic_fr:"Vivre, c’est Christ",ph:3,
  summary:"Paul and Timothy, servants of Christ Jesus, To all the saints in Christ Jesus who are at Philippi, with the overseers and deacons:",
  summary_es:"Pablo y Timoteo, siervos de Jesucristo, a todos los santos en Cristo Jesús que están en Filipos, con los obispos y diáconos:",
  summary_fr:"Paul et Timothée, serviteurs de Jésus-Christ, à tous les saints en Jésus-Christ qui sont à Philippes, aux évêques et aux diacres :"},
{day:16,reading:"Philippians 2:1–12",topic:"The Mind of Christ",topic_es:"El sentir de Cristo",topic_fr:"La pensée du Christ",
  summary:"So if there is any encouragement in Christ, any comfort from love, any participation in the Spirit, any affection and sympathy,",
  summary_es:"Por tanto, si hay alguna consolación en Cristo, si algún consuelo de amor, si alguna comunión del Espíritu, si algún afecto entrañable, si alguna misericordia,",
  summary_fr:"Si donc il y a quelque consolation en Christ, s’il y a quelque soulagement dans la charité, s’il y a quelque union d’esprit, s’il y a quelque compassion et quelque miséricorde,"},
{day:17,reading:"Philippians 2:13–30",topic:"Working Out Your Salvation",topic_es:"Ocupaos en vuestra salvación",topic_fr:"Travailler à votre salut",
  summary:"for it is God who works in you, both to will and to work for his good pleasure.",
  summary_es:"porque Dios es el que en vosotros produce así el querer como el hacer, por su buena voluntad.",
  summary_fr:"car c’est Dieu qui produit en vous le vouloir et le faire, selon son bon plaisir."},
{day:18,reading:"Philippians 3",topic:"Pressing Toward the Goal",topic_es:"Prosiguiendo hacia la meta",topic_fr:"Courir vers le but",
  summary:"Finally, my brothers, rejoice in the Lord. To write the same things to you is no trouble to me and is safe for you.",
  summary_es:"Por lo demás, hermanos, gozaos en el Señor. A mí no me es molesto el escribiros las mismas cosas, y para vosotros es seguro.",
  summary_fr:"Au reste, mes frères, réjouissez-vous dans le Seigneur. Je ne me lasse point de vous écrire les mêmes choses, et pour vous cela est salutaire."},
{day:19,reading:"Philippians 4:1–9",topic:"Rejoice & the Peace of God",topic_es:"Regocijaos y la paz de Dios",topic_fr:"Réjouissez-vous et la paix de Dieu",
  summary:"Therefore, my brothers, whom I love and long for, my joy and crown, stand firm thus in the Lord, my beloved.",
  summary_es:"Así que, hermanos míos amados y deseados, gozo y corona mía, estad así firmes en el Señor, amados.",
  summary_fr:"C’est pourquoi, mes bien-aimés, et très chers frères, vous qui êtes ma joie et ma couronne, demeurez ainsi fermes dans le Seigneur, mes bien-aimés !"},
{day:20,reading:"Philippians 4:10–23",topic:"Contentment in Christ",topic_es:"Contentamiento en Cristo",topic_fr:"Le contentement en Christ",
  summary:"I rejoiced in the Lord greatly that now at length you have revived your concern for me. You were indeed concerned for me, but you had no opportunity.",
  summary_es:"En gran manera me gocé en el Señor de que ya al fin habéis revivido vuestro cuidado de mí; de lo cual también estabais solícitos, pero os faltaba la oportunidad.",
  summary_fr:"J’ai éprouvé une grande joie dans le Seigneur de ce que vous avez pu enfin renouveler l’expression de vos sentiments pour moi ; vous y pensiez bien, mais l’occasion vous manquait."},
{day:21,reading:"Philippians 1–4",topic:"Philippians Re-Read",topic_es:"Relectura de Filipenses",topic_fr:"Relecture des Philippiens",
  summary:"Read all four chapters of Philippians in one sitting. Joy and the mind of Christ from start to finish, even from a prison cell.",
  summary_es:"Lee los cuatro capítulos de Filipenses de una sola vez. Gozo y el sentir de Cristo de principio a fin, aun desde una celda.",
  summary_fr:"Lis les quatre chapitres des Philippiens d’une traite. La joie et la pensée du Christ du début à la fin, même depuis une cellule."},
{day:22,reading:"Colossians 1–4",topic:"Colossians Overview",topic_es:"Vista general de Colosenses",topic_fr:"Vue d’ensemble des Colossiens",
  summary:"Paul, an apostle of Christ Jesus by the will of God, and Timothy our brother,",
  summary_es:"Pablo, apóstol de Jesucristo por la voluntad de Dios, y el hermano Timoteo,",
  summary_fr:"Paul, apôtre de Jésus-Christ par la volonté de Dieu, et le frère Timothée,"},
{day:23,reading:"Colossians 1:1–14",topic:"Thanksgiving & Prayer",topic_es:"Acción de gracias y oración",topic_fr:"Action de grâces et prière",ph:4,
  summary:"Paul, an apostle of Christ Jesus by the will of God, and Timothy our brother,",
  summary_es:"Pablo, apóstol de Jesucristo por la voluntad de Dios, y el hermano Timoteo,",
  summary_fr:"Paul, apôtre de Jésus-Christ par la volonté de Dieu, et le frère Timothée,"},
{day:24,reading:"Colossians 1:15–23",topic:"The Supremacy of Christ",topic_es:"La supremacía de Cristo",topic_fr:"La suprématie du Christ",
  summary:"He is the image of the invisible God, the firstborn of all creation.",
  summary_es:"Él es la imagen del Dios invisible, el primogénito de toda creación.",
  summary_fr:"Il est l’image du Dieu invisible, le premier-né de toute la création."},
{day:25,reading:"Colossians 2",topic:"Rooted in Christ, Not Tradition",topic_es:"Arraigados en Cristo, no en la tradición",topic_fr:"Enracinés en Christ, non dans la tradition",
  summary:"For I want you to know how great a struggle I have for you and for those at Laodicea and for all who have not seen me face to face,",
  summary_es:"Porque quiero que sepáis cuán gran lucha sostengo por vosotros, y por los que están en Laodicea, y por todos los que nunca han visto mi rostro;",
  summary_fr:"Je veux, en effet, que vous sachiez combien est grand le combat que je soutiens pour vous, et pour ceux qui sont à Laodicée, et pour tous ceux qui n’ont pas vu mon visage,"},
{day:26,reading:"Colossians 3:1–11",topic:"Set Your Mind on Things Above",topic_es:"Poned la mira en las cosas de arriba",topic_fr:"Affectionnez-vous aux choses d’en haut",
  summary:"If then you have been raised with Christ, seek the things that are above, where Christ is, seated at the right hand of God.",
  summary_es:"Si, pues, habéis resucitado con Cristo, buscad las cosas de arriba, donde está Cristo sentado a la diestra de Dios.",
  summary_fr:"Si donc vous êtes ressuscités avec Christ, cherchez les choses d’en haut, où Christ est assis à la droite de Dieu."},
{day:27,reading:"Colossians 3:12–17",topic:"Put On the New Self",topic_es:"Vestíos del nuevo hombre",topic_fr:"Revêtez-vous de l’homme nouveau",
  summary:"Put on then, as God’s chosen ones, holy and beloved, compassionate hearts, kindness, humility, meekness, and patience,",
  summary_es:"Vestíos, pues, como escogidos de Dios, santos y amados, de entrañable misericordia, de benignidad, de humildad, de mansedumbre, de paciencia;",
  summary_fr:"Ainsi donc, comme des élus de Dieu, saints et bien-aimés, revêtez-vous d’entrailles de miséricorde, de bonté, d’humilité, de douceur, de patience."},
{day:28,reading:"Colossians 3:18–25",topic:"Christian Relationships",topic_es:"Relaciones cristianas",topic_fr:"Relations chrétiennes",
  summary:"Wives, submit to your husbands, as is fitting in the Lord.",
  summary_es:"Casadas, estad sujetas a vuestros maridos, como conviene en el Señor.",
  summary_fr:"Femmes, soyez soumises à vos maris, comme il convient dans le Seigneur."},
{day:29,reading:"Colossians 4",topic:"Final Greetings & Prayer",topic_es:"Saludos finales y oración",topic_fr:"Salutations finales et prière",
  summary:"Masters, treat your bondservants justly and fairly, knowing that you also have a Master in heaven.",
  summary_es:"Amos, haced lo que es justo y recto con vuestros siervos, sabiendo que también vosotros tenéis un Amo en los cielos.",
  summary_fr:"Maîtres, accordez à vos serviteurs ce qui est juste et équitable, sachant que vous aussi vous avez un maître dans le ciel."},
{day:30,reading:"Colossians 1–4",topic:"Colossians Re-Read",topic_es:"Relectura de Colosenses",topic_fr:"Relecture des Colossiens",
  summary:"Read all four chapters of Colossians in one sitting. Christ is supreme — in creation, in redemption, in you. Let it settle.",
  summary_es:"Lee los cuatro capítulos de Colosenses de una sola vez. Cristo es supremo — en la creación, en la redención, en ti. Déjalo asentarse.",
  summary_fr:"Lis les quatre chapitres des Colossiens d’une traite. Christ est suprême — dans la création, dans la rédemption, en toi. Laisse cela s’installer."}
],
  verses: {
1:{r:"Galatians 2:20",r_es:"Gálatas 2:20",r_fr:"Galates 2:20",
  t:"I have been crucified with Christ. It is no longer I who live, but Christ who lives in me. And the life I now live in the flesh I live by faith in the Son of God, who loved me and gave himself for me.",
  t_es:"Con Cristo estoy juntamente crucificado, y ya no vivo yo, mas vive Cristo en mí; y lo que ahora vivo en la carne, lo vivo en la fe del Hijo de Dios, el cual me amó y se entregó a sí mismo por mí.",
  t_fr:"J’ai été crucifié avec Christ ; et si je vis, ce n’est plus moi qui vis, c’est Christ qui vit en moi ; si je vis maintenant dans la chair, je vis dans la foi au Fils de Dieu, qui m’a aimé et qui s’est livré lui-même pour moi."},
8:{r:"Ephesians 2:8–9",r_es:"Efesios 2:8–9",r_fr:"Éphésiens 2:8–9",
  t:"For by grace you have been saved through faith. And this is not your own doing; it is the gift of God, not a result of works, so that no one may boast.",
  t_es:"Porque por gracia sois salvos por medio de la fe; y esto no de vosotros, pues es don de Dios; no por obras, para que nadie se gloríe.",
  t_fr:"Car c’est par la grâce que vous êtes sauvés, par le moyen de la foi. Et cela ne vient pas de vous, c’est le don de Dieu. Ce n’est point par les œuvres, afin que personne ne se glorifie."},
15:{r:"Philippians 1:21",r_es:"Filipenses 1:21",r_fr:"Philippiens 1:21",
  t:"For to me to live is Christ, and to die is gain.",
  t_es:"Porque para mí el vivir es Cristo, y el morir es ganancia.",
  t_fr:"car Christ est ma vie, et la mort m’est un gain."},
23:{r:"Colossians 3:2–3",r_es:"Colosenses 3:2–3",r_fr:"Colossiens 3:2–3",
  t:"Set your minds on things that are above, not on things that are on earth. For you have died, and your life is hidden with Christ in God.",
  t_es:"Poned la mira en las cosas de arriba, no en las de la tierra. Porque habéis muerto, y vuestra vida está escondida con Cristo en Dios.",
  t_fr:"Affectionnez-vous aux choses d’en haut, et non à celles qui sont sur la terre. Car vous êtes morts, et votre vie est cachée avec Christ en Dieu."}
},
  checks: [
  {k:"read",l:"Read the passage",l_es:"Lee el pasaje",l_fr:"Lis le passage"},
  {k:"pray",l:"Pray & journal",l_es:"Ora y escribe en tu diario",l_fr:"Prie et tiens un journal"},
  {k:"workout",l:"Workout (3–5x/week)",l_es:"Entrena (3–5x por semana)",l_fr:"Entraînement (3–5x par semaine)"},
  {k:"abstain",l:"Abstain from your one thing",l_es:"Abstente de aquello que decidiste",l_fr:"Abstiens-toi de la chose que tu as choisie"},
  {k:"marco",l:"Marco Polo update",l_es:"Mensaje en Marco Polo",l_fr:"Mise à jour Marco Polo"}
]
};
