// Iron Sharpens Iron v2.2.0 — 30 Attributes of God (September) Config (en/es/fr)
// No assigned memory verses this month per the tracker — the daily "memorize"
// check covers a self-chosen verse from each day's reading.
window.PLAN = {
  title: "30 Attributes of God",
  title_es: "30 Atributos de Dios",
  title_fr: "30 attributs de Dieu",
  subtitle: "30 ATTRIBUTES OF GOD — 30-DAY CHALLENGE",
  subtitle_es: "30 ATRIBUTOS DE DIOS — RETO DE 30 DÍAS",
  subtitle_fr: "30 ATTRIBUTS DE DIEU — DÉFI DE 30 JOURS",
  storageKey: "isi-september-v1",
  startDate: "2026-09-01",
  totalDays: 30,
  days: [
{day:1,reading:"Psalm 90; Isaiah 40:28",topic:"Eternal",topic_es:"Eterno",topic_fr:"Éternel",
  summary:"Before the mountains were brought forth, or ever you had formed the earth and the world, from everlasting to everlasting you are God.",
  summary_es:"Antes que naciesen los montes y formases la tierra y el mundo, desde el siglo y hasta el siglo, tú eres Dios.",
  summary_fr:"Avant que les montagnes fussent nées, et que tu eusses créé la terre et le monde, d’éternité en éternité tu es Dieu."},
{day:2,reading:"Genesis 1–2; John 1:1–5",topic:"Creator",topic_es:"Creador",topic_fr:"Créateur",
  summary:"In the beginning, God created the heavens and the earth.",
  summary_es:"En el principio creó Dios los cielos y la tierra.",
  summary_fr:"Au commencement, Dieu créa les cieux et la terre."},
{day:3,reading:"Romans 8:28; Ephesians 1:11",topic:"Sovereign",topic_es:"Soberano",topic_fr:"Souverain",
  summary:"And we know that for those who love God all things work together for good, for those who are called according to his purpose.",
  summary_es:"Y sabemos que a los que aman a Dios, todas las cosas les ayudan a bien, esto es, a los que conforme a su propósito son llamados.",
  summary_fr:"Nous savons, du reste, que toutes choses concourent au bien de ceux qui aiment Dieu, de ceux qui sont appelés selon son dessein."},
{day:4,reading:"Jeremiah 32:17–27; Luke 1:37",topic:"Omnipotent",topic_es:"Omnipotente",topic_fr:"Tout-puissant",
  summary:"Ah, Lord God! It is you who have made the heavens and the earth by your great power and by your outstretched arm! Nothing is too hard for you.",
  summary_es:"¡Oh Señor Jehová! he aquí que tú hiciste el cielo y la tierra con tu gran poder, y con tu brazo extendido, ni hay nada que sea difícil para ti.",
  summary_fr:"Ah ! Seigneur Éternel, voici, tu as fait les cieux et la terre par ta grande puissance et par ton bras étendu : rien n’est étonnant de ta part."},
{day:5,reading:"Psalm 139; 1 John 3:20",topic:"Omniscient",topic_es:"Omnisciente",topic_fr:"Omniscient",
  summary:"O Lord, you have searched me and known me! You know when I sit down and when I rise up; you discern my thoughts from afar.",
  summary_es:"Oh Jehová, tú me has examinado y conocido. Tú has conocido mi sentarme y mi levantarme; has entendido desde lejos mis pensamientos.",
  summary_fr:"Éternel ! tu me sondes et tu me connais, tu sais quand je m’assieds et quand je me lève, tu pénètres de loin ma pensée."},
{day:6,reading:"Psalm 139:7–12",topic:"Omnipresent",topic_es:"Omnipresente",topic_fr:"Omniprésent",
  summary:"Where shall I go from your Spirit? Or where shall I flee from your presence? If I ascend to heaven, you are there! If I make my bed in Sheol, you are there!",
  summary_es:"¿A dónde me iré de tu Espíritu? ¿Y a dónde huiré de tu presencia? Si subiere a los cielos, allí estás tú; y si en el Seol hiciere mi estrado, he aquí, allí tú estás.",
  summary_fr:"Où irais-je loin de ton esprit, et où fuirais-je loin de ta face ? Si je monte aux cieux, tu y es ; si je me couche au séjour des morts, t’y voilà."},
{day:7,reading:"Malachi 3:6; James 1:17",topic:"Immutable",topic_es:"Inmutable",topic_fr:"Immuable",
  summary:"For I the Lord do not change; therefore you, O children of Jacob, are not consumed.",
  summary_es:"Porque yo Jehová no cambio; por esto, hijos de Jacob, no habéis sido consumidos.",
  summary_fr:"Car je suis l’Éternel, je ne change pas ; et vous, enfants de Jacob, vous n’avez pas été consumés."},
{day:8,reading:"Isaiah 6:1–8; 1 Peter 1:13–16",topic:"Holy",topic_es:"Santo",topic_fr:"Saint",
  summary:"And one called to another and said: “Holy, holy, holy is the Lord of hosts; the whole earth is full of his glory!”",
  summary_es:"Y el uno al otro daba voces, diciendo: Santo, santo, santo, Jehová de los ejércitos; toda la tierra está llena de su gloria.",
  summary_fr:"Ils criaient l’un à l’autre, et disaient : Saint, saint, saint est l’Éternel des armées ! toute la terre est pleine de sa gloire !"},
{day:9,reading:"Psalm 11; Romans 3:21–26",topic:"Righteous",topic_es:"Recto",topic_fr:"Droit",
  summary:"For the Lord is righteous; he loves righteous deeds; the upright shall behold his face.",
  summary_es:"Porque Jehová es justo, y ama la justicia; el hombre recto mirará su rostro.",
  summary_fr:"Car l’Éternel est juste, il aime la justice ; les hommes droits contemplent sa face."},
{day:10,reading:"Deuteronomy 32:1–4; Micah 6:8",topic:"Just",topic_es:"Justo",topic_fr:"Juste",
  summary:"The Rock, his work is perfect, for all his ways are justice. A God of faithfulness and without iniquity, just and upright is he.",
  summary_es:"Él es la Roca, cuya obra es perfecta, porque todos sus caminos son rectitud; Dios de verdad, y sin ninguna iniquidad en él; es justo y recto.",
  summary_fr:"Il est le rocher ; ses œuvres sont parfaites, car toutes ses voies sont justes ; c’est un Dieu fidèle et sans iniquité, il est juste et droit."},
{day:11,reading:"Numbers 23:19; John 14:6",topic:"Truth",topic_es:"Verdad",topic_fr:"Vérité",
  summary:"Jesus said to him, “I am the way, and the truth, and the life. No one comes to the Father except through me.”",
  summary_es:"Jesús le dijo: Yo soy el camino, y la verdad, y la vida; nadie viene al Padre, sino por mí.",
  summary_fr:"Jésus lui dit : Je suis le chemin, la vérité, et la vie. Nul ne vient au Père que par moi."},
{day:12,reading:"1 John 1:5–10; John 8:12",topic:"Light",topic_es:"Luz",topic_fr:"Lumière",
  summary:"This is the message we have heard from him and proclaim to you, that God is light, and in him is no darkness at all.",
  summary_es:"Este es el mensaje que hemos oído de él, y os anunciamos: Dios es luz, y no hay ningunas tinieblas en él.",
  summary_fr:"La nouvelle que nous avons apprise de lui, et que nous vous annonçons, c’est que Dieu est lumière, et qu’il n’y a point en lui de ténèbres."},
{day:13,reading:"Habakkuk 1; Romans 1:18–25",topic:"Hates Sin",topic_es:"Aborrece el pecado",topic_fr:"Il hait le péché",
  summary:"For the wrath of God is revealed from heaven against all ungodliness and unrighteousness of men, who by their unrighteousness suppress the truth.",
  summary_es:"Porque la ira de Dios se revela desde el cielo contra toda impiedad e injusticia de los hombres que detienen con injusticia la verdad.",
  summary_fr:"La colère de Dieu se révèle du ciel contre toute impiété et toute injustice des hommes qui retiennent injustement la vérité captive."},
{day:14,reading:"Revelation 4; Psalm 95",topic:"Worthy of Worship",topic_es:"Digno de adoración",topic_fr:"Digne d’adoration",
  summary:"Worthy are you, our Lord and God, to receive glory and honor and power, for you created all things, and by your will they existed and were created.",
  summary_es:"Señor, digno eres de recibir la gloria y la honra y el poder; porque tú creaste todas las cosas, y por tu voluntad existen y fueron creadas.",
  summary_fr:"Tu es digne, notre Seigneur et notre Dieu, de recevoir la gloire et l’honneur et la puissance ; car tu as créé toutes choses, et c’est par ta volonté qu’elles existent et qu’elles ont été créées."},
{day:15,reading:"1 John 4:7–21",topic:"Love",topic_es:"Amor",topic_fr:"Amour",
  summary:"Anyone who does not love does not know God, because God is love.",
  summary_es:"El que no ama, no ha conocido a Dios; porque Dios es amor.",
  summary_fr:"Celui qui n’aime pas n’a pas connu Dieu, car Dieu est amour."},
{day:16,reading:"Psalm 103; Luke 15:11–32",topic:"Merciful",topic_es:"Misericordioso",topic_fr:"Miséricordieux",
  summary:"The Lord is merciful and gracious, slow to anger and abounding in steadfast love.",
  summary_es:"Misericordioso y clemente es Jehová; lento para la ira, y grande en misericordia.",
  summary_fr:"L’Éternel est miséricordieux et compatissant, lent à la colère et riche en bonté."},
{day:17,reading:"Ephesians 2:1–10",topic:"Gracious",topic_es:"Lleno de gracia",topic_fr:"Plein de grâce",
  summary:"For by grace you have been saved through faith. And this is not your own doing; it is the gift of God, not a result of works, so that no one may boast.",
  summary_es:"Porque por gracia sois salvos por medio de la fe; y esto no de vosotros, pues es don de Dios; no por obras, para que nadie se gloríe.",
  summary_fr:"Car c’est par la grâce que vous êtes sauvés, par le moyen de la foi. Et cela ne vient pas de vous, c’est le don de Dieu. Ce n’est point par les œuvres, afin que personne ne se glorifie."},
{day:18,reading:"Exodus 34:1–7; 2 Peter 3:8–9",topic:"Patient",topic_es:"Paciente",topic_fr:"Patient",
  summary:"The Lord is not slow to fulfill his promise as some count slowness, but is patient toward you, not wishing that any should perish, but that all should reach repentance.",
  summary_es:"El Señor no retarda su promesa, según algunos la tienen por tardanza, sino que es paciente para con nosotros, no queriendo que ninguno perezca, sino que todos procedan al arrepentimiento.",
  summary_fr:"Le Seigneur ne tarde pas dans l’accomplissement de la promesse, comme quelques-uns le croient ; mais il use de patience envers vous, ne voulant pas qu’aucun périsse, mais voulant que tous arrivent à la repentance."},
{day:19,reading:"Psalm 51; 1 John 1:9",topic:"Forgiving",topic_es:"Perdonador",topic_fr:"Qui pardonne",
  summary:"If we confess our sins, he is faithful and just to forgive us our sins and to cleanse us from all unrighteousness.",
  summary_es:"Si confesamos nuestros pecados, él es fiel y justo para perdonar nuestros pecados, y limpiarnos de toda maldad.",
  summary_fr:"Si nous confessons nos péchés, il est fidèle et juste pour nous les pardonner, et pour nous purifier de toute iniquité."},
{day:20,reading:"Matthew 9:35–38; Lamentations 3:22–23",topic:"Compassionate",topic_es:"Compasivo",topic_fr:"Compatissant",
  summary:"When he saw the crowds, he had compassion for them, because they were harassed and helpless, like sheep without a shepherd.",
  summary_es:"Y al ver las multitudes, tuvo compasión de ellas; porque estaban desamparadas y dispersas como ovejas que no tienen pastor.",
  summary_fr:"Voyant la foule, il fut ému de compassion pour elle, parce qu’elle était languissante et abattue, comme des brebis qui n’ont point de berger."},
{day:21,reading:"Lamentations 3:19–26; 2 Timothy 2:11–13",topic:"Faithful",topic_es:"Fiel",topic_fr:"Fidèle",
  summary:"The steadfast love of the Lord never ceases; his mercies never come to an end; they are new every morning; great is your faithfulness.",
  summary_es:"Por la misericordia de Jehová no hemos sido consumidos, porque nunca decayeron sus misericordias. Nuevas son cada mañana; grande es tu fidelidad.",
  summary_fr:"Les bontés de l’Éternel ne sont pas épuisées, ses compassions ne sont pas à leur terme ; elles se renouvellent chaque matin. Oh ! que ta fidélité est grande !"},
{day:22,reading:"Romans 11:33–36; Proverbs 3:5–7",topic:"Wise",topic_es:"Sabio",topic_fr:"Sage",
  summary:"Oh, the depth of the riches and wisdom and knowledge of God! How unsearchable are his judgments and how inscrutable his ways!",
  summary_es:"¡Oh profundidad de las riquezas de la sabiduría y de la ciencia de Dios! ¡Cuán insondables son sus juicios, e inescrutables sus caminos!",
  summary_fr:"Ô profondeur de la richesse, de la sagesse et de la science de Dieu ! Que ses jugements sont insondables, et ses voies incompréhensibles !"},
{day:23,reading:"Psalm 34; James 1:16–18",topic:"Good",topic_es:"Bueno",topic_fr:"Bon",
  summary:"Oh, taste and see that the Lord is good! Blessed is the man who takes refuge in him!",
  summary_es:"Gustad, y ved que es bueno Jehová; dichoso el hombre que confía en él.",
  summary_fr:"Sentez et voyez combien l’Éternel est bon ! Heureux l’homme qui cherche en lui son refuge !"},
{day:24,reading:"Psalm 23; John 10:1–18",topic:"Our Shepherd",topic_es:"Nuestro Pastor",topic_fr:"Notre Berger",
  summary:"The Lord is my shepherd; I shall not want.",
  summary_es:"Jehová es mi pastor; nada me faltará.",
  summary_fr:"L’Éternel est mon berger : je ne manquerai de rien."},
{day:25,reading:"Psalm 46; Nahum 1:7",topic:"Our Refuge",topic_es:"Nuestro Refugio",topic_fr:"Notre Refuge",
  summary:"God is our refuge and strength, a very present help in trouble.",
  summary_es:"Dios es nuestro amparo y fortaleza, nuestro pronto auxilio en las tribulaciones.",
  summary_fr:"Dieu est pour nous un refuge et un appui, un secours qui ne manque jamais dans la détresse."},
{day:26,reading:"Philippians 4:4–9; Judges 6:24",topic:"Peace",topic_es:"Paz",topic_fr:"Paix",
  summary:"And the peace of God, which surpasses all understanding, will guard your hearts and your minds in Christ Jesus.",
  summary_es:"Y la paz de Dios, que sobrepasa todo entendimiento, guardará vuestros corazones y vuestros pensamientos en Cristo Jesús.",
  summary_fr:"Et la paix de Dieu, qui surpasse toute intelligence, gardera vos cœurs et vos pensées en Jésus-Christ."},
{day:27,reading:"Psalm 147; Isaiah 61:1–3",topic:"Near to the Brokenhearted",topic_es:"Cercano al quebrantado de corazón",topic_fr:"Proche des cœurs brisés",
  summary:"He heals the brokenhearted and binds up their wounds.",
  summary_es:"Él sana a los quebrantados de corazón, y venda sus heridas.",
  summary_fr:"Il guérit ceux qui ont le cœur brisé, et il panse leurs blessures."},
{day:28,reading:"Isaiah 53; Titus 3:3–7",topic:"Savior",topic_es:"Salvador",topic_fr:"Sauveur",
  summary:"But he was pierced for our transgressions; he was crushed for our iniquities; upon him was the chastisement that brought us peace, and with his stripes we are healed.",
  summary_es:"Mas él herido fue por nuestras rebeliones, molido por nuestros pecados; el castigo de nuestra paz fue sobre él, y por su llaga fuimos nosotros curados.",
  summary_fr:"Mais il était blessé pour nos péchés, brisé pour nos iniquités ; le châtiment qui nous donne la paix est tombé sur lui, et c’est par ses meurtrissures que nous sommes guéris."},
{day:29,reading:"Ecclesiastes 12:13–14",topic:"Will Judge the World",topic_es:"Juzgará al mundo",topic_fr:"Il jugera le monde",
  summary:"For God will bring every deed into judgment, with every secret thing, whether good or evil.",
  summary_es:"Porque Dios traerá toda obra a juicio, juntamente con toda cosa encubierta, sea buena o sea mala.",
  summary_fr:"Car Dieu amènera toute œuvre en jugement, au sujet de tout ce qui est caché, soit bien, soit mal."},
{day:30,reading:"Revelation 21–22",topic:"Makes All Things New",topic_es:"Hace nuevas todas las cosas",topic_fr:"Il fait toutes choses nouvelles",
  summary:"And he who was seated on the throne said, “Behold, I am making all things new.” Also he said, “Write this down, for these words are trustworthy and true.”",
  summary_es:"Y el que estaba sentado en el trono dijo: He aquí, yo hago nuevas todas las cosas. Y me dijo: Escribe; porque estas palabras son fieles y verdaderas.",
  summary_fr:"Et celui qui était assis sur le trône dit : Voici, je fais toutes choses nouvelles. Et il dit : Écris ; car ces paroles sont certaines et véritables."}
],
  verses: {},
  checks: [
  {k:"read",l:"Read the passage",l_es:"Lee el pasaje",l_fr:"Lis le passage"},
  {k:"pray",l:"Pray & journal",l_es:"Ora y escribe en tu diario",l_fr:"Prie et tiens un journal"},
  {k:"workout",l:"Workout (3–5x/week)",l_es:"Entrena (3–5x por semana)",l_fr:"Entraînement (3–5x par semaine)"},
  {k:"abstain",l:"Abstain from your one thing",l_es:"Abstente de aquello que decidiste",l_fr:"Abstiens-toi de la chose que tu as choisie"},
  {k:"memorize",l:"Memorize a verse from today’s reading",l_es:"Memoriza un versículo de la lectura de hoy",l_fr:"Mémorise un verset de la lecture du jour"},
  {k:"marco",l:"Marco Polo update",l_es:"Mensaje en Marco Polo",l_fr:"Mise à jour Marco Polo"}
]
};
