// Iron Sharpens Iron v2.2.0 — Proverbs Config (en/es/fr)
window.PLAN = {
  title: "Proverbs",
  title_es: "Proverbios",
  title_fr: "Proverbes",
  subtitle: "PROVERBS — 30-DAY CHALLENGE",
  subtitle_es: "PROVERBIOS — RETO DE 30 DÍAS",
  subtitle_fr: "PROVERBES — DÉFI DE 30 JOURS",
  storageKey: "isi-proverbs-v2",
  totalDays: 30,
  days: [
{day:1,reading:"Proverbs 1",topic:"The Beginning of Knowledge",topic_es:"El principio del conocimiento",topic_fr:"Le commencement de la connaissance",ph:1,
  summary:"Solomon sets the stage: the fear of the Lord is the beginning of knowledge. Wisdom cries out in the streets — will you listen or turn away?",
  summary_es:"Salomón presenta el marco: el temor de Jehová es el principio del conocimiento. La sabiduría clama en las calles — ¿la oirás o te apartarás?",
  summary_fr:"Salomon pose le décor : la crainte de l’Éternel est le commencement de la connaissance. La sagesse crie dans les rues — l’écouteras-tu ou te détourneras-tu ?"},
{day:2,reading:"Proverbs 2",topic:"The Value of Wisdom",topic_es:"El valor de la sabiduría",topic_fr:"La valeur de la sagesse",
  summary:"Seek wisdom like silver and search for it like hidden treasure. God gives wisdom, and from His mouth come knowledge and understanding.",
  summary_es:"Busca la sabiduría como a la plata, y escudríñala como a tesoros escondidos. Jehová da la sabiduría, y de su boca vienen el conocimiento y la inteligencia.",
  summary_fr:"Cherche la sagesse comme l’argent, et recherche-la comme un trésor caché. C’est l’Éternel qui donne la sagesse ; de sa bouche sortent la connaissance et l’intelligence."},
{day:3,reading:"Proverbs 3",topic:"Trust in the Lord",topic_es:"Confía en Jehová",topic_fr:"Confie-toi en l’Éternel",
  summary:"Trust in the Lord with all your heart and lean not on your own understanding. In all your ways acknowledge Him, and He will make your paths straight.",
  summary_es:"Fíate de Jehová de todo tu corazón, y no te apoyes en tu propia prudencia. Reconócelo en todos tus caminos, y él enderezará tus veredas.",
  summary_fr:"Confie-toi en l’Éternel de tout ton cœur, et ne t’appuie pas sur ton intelligence. Reconnais-le dans toutes tes voies, et il aplanira tes sentiers."},
{day:4,reading:"Proverbs 4",topic:"Guard Your Heart",topic_es:"Guarda tu corazón",topic_fr:"Garde ton cœur",
  summary:"Above all else, guard your heart, for everything you do flows from it. The path of the righteous is like the morning sun, shining brighter until full day.",
  summary_es:"Sobre toda cosa guardada, guarda tu corazón, porque de él mana la vida. La senda de los justos es como la luz de la aurora, que va en aumento hasta que el día es perfecto.",
  summary_fr:"Garde ton cœur plus que toute autre chose, car de lui viennent les sources de la vie. Le sentier des justes est comme la lumière resplendissante, dont l’éclat va croissant jusqu’au milieu du jour."},
{day:5,reading:"Proverbs 5",topic:"Warning Against Adultery",topic_es:"Advertencia contra el adulterio",topic_fr:"Avertissement contre l’adultère",
  summary:"Solomon warns his son about the seductive woman and the destruction of unfaithfulness. Drink water from your own cistern — rejoice in the wife of your youth.",
  summary_es:"Salomón advierte a su hijo sobre la mujer seductora y la ruina de la infidelidad. Bebe el agua de tu misma cisterna — alégrate con la mujer de tu juventud.",
  summary_fr:"Salomon avertit son fils contre la femme séductrice et la ruine de l’infidélité. Bois l’eau de ta propre citerne — réjouis-toi avec la femme de ta jeunesse."},
{day:6,reading:"Proverbs 6",topic:"Warnings Against Folly",topic_es:"Advertencias contra la insensatez",topic_fr:"Avertissements contre la folie",
  summary:"Go to the ant, you sluggard. Six things the Lord hates, seven that are an abomination. Warnings against laziness, dishonesty, and sexual sin.",
  summary_es:"Ve a la hormiga, oh perezoso. Seis cosas aborrece Jehová, y aun siete abomina su alma. Advertencias contra la pereza, el engaño y el pecado sexual.",
  summary_fr:"Va vers la fourmi, paresseux. L’Éternel hait six choses, et il en est sept qu’il a en abomination. Avertissements contre la paresse, le mensonge et le péché sexuel."},
{day:7,reading:"Proverbs 7",topic:"The Wayward Woman",topic_es:"La mujer extraña",topic_fr:"La femme étrangère",
  summary:"A vivid narrative warning against temptation. The young man lacks sense and walks into the trap. Her house is a highway to the grave.",
  summary_es:"Un relato vívido que advierte contra la tentación. El joven falto de entendimiento cae en la trampa. Su casa es camino al Seol.",
  summary_fr:"Un récit saisissant contre la tentation. Le jeune homme dépourvu de sens tombe dans le piège. Sa maison est le chemin du séjour des morts."},
{day:8,reading:"Proverbs 8",topic:"Wisdom’s Call",topic_es:"El llamado de la sabiduría",topic_fr:"L’appel de la sagesse",ph:2,
  summary:"Wisdom speaks: she was there before creation, beside God as a master craftsman. Whoever finds wisdom finds life and receives favor from the Lord.",
  summary_es:"La sabiduría habla: estaba antes de la creación, junto a Dios como artífice maestro. El que halla la sabiduría halla la vida, y alcanza el favor de Jehová.",
  summary_fr:"La sagesse parle : elle était là avant la création, aux côtés de Dieu comme un maître ouvrier. Celui qui trouve la sagesse trouve la vie, et obtient la faveur de l’Éternel."},
{day:9,reading:"Proverbs 9",topic:"Two Invitations",topic_es:"Dos invitaciones",topic_fr:"Deux invitations",
  summary:"Wisdom has built her house and set her table. Folly also calls out. Two invitations, two paths — life or death. The fear of the Lord is the beginning of wisdom.",
  summary_es:"La sabiduría edificó su casa y aderezó su mesa. La necedad también llama. Dos invitaciones, dos caminos — vida o muerte. El temor de Jehová es el principio de la sabiduría.",
  summary_fr:"La sagesse a bâti sa maison et dressé sa table. La folie aussi appelle. Deux invitations, deux chemins — la vie ou la mort. La crainte de l’Éternel est le commencement de la sagesse."},
{day:10,reading:"Proverbs 10",topic:"Proverbs of Solomon Begin",topic_es:"Comienzan los proverbios de Salomón",topic_fr:"Les proverbes de Salomon commencent",
  summary:"The contrast begins: wise son vs. foolish son, righteousness vs. wickedness, diligence vs. laziness. The mouth of the righteous is a fountain of life.",
  summary_es:"Comienza el contraste: el hijo sabio frente al necio, la justicia frente a la maldad, la diligencia frente a la pereza. La boca del justo es manantial de vida.",
  summary_fr:"Le contraste commence : le fils sage et l’insensé, la justice et la méchanceté, la diligence et la paresse. La bouche du juste est une source de vie."},
{day:11,reading:"Proverbs 11",topic:"Integrity and Generosity",topic_es:"Integridad y generosidad",topic_fr:"Intégrité et générosité",
  summary:"A false balance is an abomination. The integrity of the upright guides them. Whoever refreshes others will be refreshed. The generous soul will prosper.",
  summary_es:"El peso falso es abominación. La integridad de los rectos los encaminará. El que sacia, también será saciado. El alma generosa prosperará.",
  summary_fr:"Une balance fausse est en horreur. L’intégrité des hommes droits les dirige. Celui qui désaltère sera lui-même rassasié. L’âme bienfaisante sera dans l’abondance."},
{day:12,reading:"Proverbs 12",topic:"Discipline and Truth",topic_es:"Disciplina y verdad",topic_fr:"Discipline et vérité",
  summary:"Whoever loves discipline loves knowledge. The words of the wicked lie in wait for blood, but the speech of the upright rescues them. Truthful lips endure forever.",
  summary_es:"El que ama la corrección ama el conocimiento. Las palabras de los impíos acechan sangre; mas la boca de los rectos los librará. El labio veraz permanece para siempre.",
  summary_fr:"Celui qui aime la correction aime la science. Les paroles des méchants sont des embûches pour verser le sang, mais la bouche des hommes droits les délivre. La lèvre véridique est affermie pour toujours."},
{day:13,reading:"Proverbs 13",topic:"Guarding Your Mouth",topic_es:"Guarda tu boca",topic_fr:"Garde ta bouche",
  summary:"Whoever guards his mouth preserves his life. Wealth gained hastily will dwindle, but whoever gathers little by little will increase it.",
  summary_es:"El que guarda su boca guarda su alma. Las riquezas de vanidad disminuirán; pero el que recoge con mano laboriosa las aumenta.",
  summary_fr:"Celui qui veille sur sa bouche garde son âme. La richesse mal acquise diminue, mais celui qui amasse peu à peu l’augmente."},
{day:14,reading:"Proverbs 14",topic:"The Wise and the Foolish",topic_es:"El sabio y el necio",topic_fr:"Le sage et l’insensé",
  summary:"The wise woman builds her house, but the foolish tears it down with her own hands. There is a way that seems right to a man, but its end is the way of death.",
  summary_es:"La mujer sabia edifica su casa, mas la necia con sus manos la derriba. Hay camino que al hombre le parece derecho; pero su fin es camino de muerte.",
  summary_fr:"La femme sage bâtit sa maison, mais la femme insensée la renverse de ses propres mains. Telle voie paraît droite à un homme, mais son issue, c’est la voie de la mort."},
{day:15,reading:"Proverbs 15",topic:"A Gentle Answer",topic_es:"La blanda respuesta",topic_fr:"La réponse douce",ph:3,
  summary:"A gentle answer turns away wrath, but a harsh word stirs up anger. The eyes of the Lord are everywhere. The prayer of the upright pleases Him.",
  summary_es:"La blanda respuesta quita la ira, mas la palabra áspera hace subir el furor. Los ojos de Jehová están en todo lugar. La oración de los rectos es su gozo.",
  summary_fr:"Une réponse douce calme la fureur, mais une parole dure excite la colère. Les yeux de l’Éternel sont en tout lieu. La prière des hommes droits lui est agréable."},
{day:16,reading:"Proverbs 16",topic:"The Lord Directs Our Steps",topic_es:"Jehová endereza los pasos",topic_fr:"L’Éternel dirige nos pas",
  summary:"The heart of man plans his way, but the Lord establishes his steps. Pride goes before destruction, and a haughty spirit before a fall.",
  summary_es:"El corazón del hombre piensa su camino, mas Jehová endereza sus pasos. Antes del quebrantamiento es la soberbia, y antes de la caída la altivez de espíritu.",
  summary_fr:"Le cœur de l’homme médite sa voie, mais c’est l’Éternel qui dirige ses pas. L’arrogance précède la ruine, et l’orgueil précède la chute."},
{day:17,reading:"Proverbs 17",topic:"Friendship and Restraint",topic_es:"Amistad y dominio propio",topic_fr:"Amitié et retenue",
  summary:"A friend loves at all times, and a brother is born for adversity. Even a fool who keeps silent is considered wise. Better a dry morsel with quiet than a feast with strife.",
  summary_es:"En todo tiempo ama el amigo, y es como un hermano en tiempo de angustia. Aun el necio, cuando calla, es contado por sabio. Mejor es un bocado seco, y en paz, que casa de contiendas llena de provisiones.",
  summary_fr:"L’ami aime en tout temps, et dans le malheur il se montre un frère. L’insensé même, quand il se tait, passe pour sage. Mieux vaut un morceau de pain sec, avec la paix, qu’une maison pleine de viandes, avec des querelles."},
{day:18,reading:"Proverbs 18",topic:"The Power of Words",topic_es:"El poder de las palabras",topic_fr:"Le pouvoir des paroles",
  summary:"Death and life are in the power of the tongue. The name of the Lord is a strong tower; the righteous run into it and are safe.",
  summary_es:"La muerte y la vida están en poder de la lengua. Torre fuerte es el nombre de Jehová; a él correrá el justo, y será levantado.",
  summary_fr:"La mort et la vie sont au pouvoir de la langue. Le nom de l’Éternel est une tour forte ; le juste s’y réfugie, et se trouve en sûreté."},
{day:19,reading:"Proverbs 19",topic:"Patience and Kindness",topic_es:"Paciencia y bondad",topic_fr:"Patience et bonté",
  summary:"Whoever is generous to the poor lends to the Lord. A man of great wrath will pay the penalty. Listen to advice and accept instruction.",
  summary_es:"A Jehová presta el que da al pobre. El de grande ira llevará la pena. Escucha el consejo, y acepta la corrección.",
  summary_fr:"Celui qui a pitié du pauvre prête à l’Éternel. L’homme violent en subit les conséquences. Écoute les conseils, et reçois l’instruction."},
{day:20,reading:"Proverbs 20",topic:"Justice and Sobriety",topic_es:"Justicia y sobriedad",topic_fr:"Justice et sobriété",
  summary:"Wine is a mocker, strong drink a brawler. The Lord detests differing weights. Who can say, ‘I have kept my heart pure’?",
  summary_es:"El vino es escarnecedor, la sidra alborotadora. Pesas falsas son abominación a Jehová. ¿Quién podrá decir: ‘Yo he limpiado mi corazón’?",
  summary_fr:"Le vin est moqueur, les boissons fortes sont tumultueuses. L’Éternel a en horreur les poids divers. Qui peut dire : ‘J’ai purifié mon cœur’ ?"},
{day:21,reading:"Proverbs 21",topic:"The Lord Weighs the Heart",topic_es:"Jehová pesa el corazón",topic_fr:"L’Éternel pèse les cœurs",
  summary:"Every way of a man is right in his own eyes, but the Lord weighs the heart. The horse is made ready for the day of battle, but victory belongs to the Lord.",
  summary_es:"Todo camino del hombre es recto en su propia opinión; pero Jehová pesa los corazones. El caballo se alista para el día de la batalla; mas Jehová es el que da la victoria.",
  summary_fr:"Toutes les voies de l’homme sont droites à ses yeux, mais celui qui pèse les cœurs, c’est l’Éternel. Le cheval est équipé pour le jour de la bataille, mais la délivrance appartient à l’Éternel."},
{day:22,reading:"Proverbs 22",topic:"A Good Name",topic_es:"El buen nombre",topic_fr:"Une bonne renommée",ph:4,
  summary:"A good name is more desirable than great riches. Train up a child in the way he should go; even when he is old he will not depart from it.",
  summary_es:"De más estima es el buen nombre que las muchas riquezas. Instruye al niño en su camino, y aun cuando fuere viejo no se apartará de él.",
  summary_fr:"La réputation est préférable à de grandes richesses. Instruis l’enfant selon la voie qu’il doit suivre ; et quand il sera vieux, il ne s’en détournera pas."},
{day:23,reading:"Proverbs 23",topic:"Warnings Against Excess",topic_es:"Advertencias contra el exceso",topic_fr:"Avertissements contre l’excès",
  summary:"Do not wear yourself out to get rich. Do not envy sinners, but always be zealous for the fear of the Lord. Listen to your father who gave you life.",
  summary_es:"No te afanes por hacerte rico. No tenga tu corazón envidia de los pecadores, antes persevera en el temor de Jehová todo el tiempo. Oye a tu padre, a aquel que te engendró.",
  summary_fr:"Ne te tourmente pas pour t’enrichir. Que ton cœur n’envie point les pécheurs, mais qu’il ait toujours la crainte de l’Éternel. Écoute ton père, qui t’a engendré."},
{day:24,reading:"Proverbs 24",topic:"Wisdom Builds the House",topic_es:"La sabiduría edifica la casa",topic_fr:"La sagesse bâtit la maison",
  summary:"By wisdom a house is built, and through understanding it is established. Do not gloat when your enemy falls. If you faint in the day of adversity, your strength is small.",
  summary_es:"Con sabiduría se edificará la casa, y con prudencia se afirmará. Cuando cayere tu enemigo, no te regocijes. Si flaqueares en día de adversidad, tu fuerza será reducida.",
  summary_fr:"C’est par la sagesse qu’une maison s’élève, et par l’intelligence qu’elle s’affermit. Ne te réjouis pas de la chute de ton ennemi. Si tu faiblis au jour de la détresse, ta force n’est que peu de chose."},
{day:25,reading:"Proverbs 25",topic:"Kings, Fools, and Self-Control",topic_es:"Reyes, necios y dominio propio",topic_fr:"Rois, insensés et maîtrise de soi",
  summary:"It is the glory of God to conceal things, but the glory of kings to search things out. Like a city breached without walls is a man who lacks self-control.",
  summary_es:"Gloria de Dios es encubrir un asunto; pero honra del rey es escudriñarlo. Como ciudad derribada y sin muro es el hombre cuyo espíritu no tiene rienda.",
  summary_fr:"La gloire de Dieu, c’est de cacher les choses ; la gloire des rois, c’est de sonder les choses. Comme une ville forcée et sans murailles, ainsi est l’homme qui n’est pas maître de lui-même."},
{day:26,reading:"Proverbs 26",topic:"Sluggards and Fools",topic_es:"Perezosos y necios",topic_fr:"Paresseux et insensés",
  summary:"Like snow in summer or rain in harvest, honor is not fitting for a fool. The sluggard buries his hand in the dish and will not even bring it back to his mouth.",
  summary_es:"Como no conviene la nieve en el verano, ni la lluvia en la siega, así no conviene al necio la honra. Mete el perezoso su mano en el plato, y se cansa de llevarla a su boca.",
  summary_fr:"Comme la neige en été, et la pluie pendant la moisson, ainsi la gloire ne convient pas à un insensé. Le paresseux plonge sa main dans le plat, et il trouve pénible de la ramener à sa bouche."},
{day:27,reading:"Proverbs 27",topic:"Iron Sharpens Iron",topic_es:"Hierro con hierro se aguza",topic_fr:"Le fer aiguise le fer",
  summary:"As iron sharpens iron, so one person sharpens another. Faithful are the wounds of a friend. Boast not about tomorrow, for you do not know what a day may bring.",
  summary_es:"Hierro con hierro se aguza; y así el hombre aguza el rostro de su amigo. Fieles son las heridas del que ama. No te jactes del día de mañana, porque no sabes qué dará de sí el día.",
  summary_fr:"Comme le fer aiguise le fer, ainsi un homme excite la colère d’un homme. Les blessures faites par celui qui aime sont fidèles. Ne te vante pas du lendemain, car tu ne sais pas ce qu’un jour peut enfanter."},
{day:28,reading:"Proverbs 28",topic:"The Righteous Are Bold",topic_es:"Los justos son osados",topic_fr:"Les justes sont hardis",
  summary:"The wicked flee when no one pursues, but the righteous are bold as a lion. Whoever conceals his transgressions will not prosper, but he who confesses them will find mercy.",
  summary_es:"Huye el impío sin que nadie lo persiga; mas el justo está confiado como un león. El que encubre sus pecados no prosperará; mas el que los confiesa y se aparta alcanzará misericordia.",
  summary_fr:"Le méchant prend la fuite sans qu’on le poursuive, mais le juste a de l’assurance comme un jeune lion. Celui qui cache ses transgressions ne prospère point, mais celui qui les avoue et les délaisse obtient miséricorde."},
{day:29,reading:"Proverbs 29",topic:"Discipline and Vision",topic_es:"Disciplina y visión",topic_fr:"Discipline et vision",
  summary:"Where there is no prophetic vision the people cast off restraint, but blessed is he who keeps the law. The fear of man lays a snare, but whoever trusts in the Lord is safe.",
  summary_es:"Sin profecía el pueblo se desenfrena; mas el que guarda la ley es bienaventurado. El temor del hombre pondrá lazo; mas el que confía en Jehová será exaltado.",
  summary_fr:"Quand il n’y a pas de révélation, le peuple est sans frein ; heureux s’il observe la loi ! La crainte des hommes tend un piège, mais celui qui se confie en l’Éternel est protégé."},
{day:30,reading:"Proverbs 30–31",topic:"Agur’s Wisdom & The Noble Wife",topic_es:"La sabiduría de Agur y la mujer virtuosa",topic_fr:"La sagesse d’Agur et la femme vertueuse",
  summary:"Agur’s humility before God. The words of King Lemuel’s mother. The book closes with the portrait of the excellent wife — strength, dignity, and the fear of the Lord.",
  summary_es:"La humildad de Agur ante Dios. Las palabras de la madre del rey Lemuel. El libro cierra con el retrato de la mujer virtuosa — fuerza, dignidad y el temor de Jehová.",
  summary_fr:"L’humilité d’Agur devant Dieu. Les paroles de la mère du roi Lemuel. Le livre se clôt par le portrait de la femme vertueuse — force, dignité et crainte de l’Éternel."}
],
  verses: {
1:{r:"Proverbs 1:7",r_es:"Proverbios 1:7",r_fr:"Proverbes 1:7",
  t:"The fear of the Lord is the beginning of knowledge; fools despise wisdom and instruction.",
  t_es:"El principio de la sabiduría es el temor de Jehová; los insensatos desprecian la sabiduría y la enseñanza.",
  t_fr:"La crainte de l’Éternel est le commencement de la science ; les insensés méprisent la sagesse et l’instruction."},
8:{r:"Proverbs 10:9",r_es:"Proverbios 10:9",r_fr:"Proverbes 10:9",
  t:"Whoever walks in integrity walks securely, but he who makes his ways crooked will be found out.",
  t_es:"El que camina en integridad anda confiado; mas el que pervierte sus caminos será quebrantado.",
  t_fr:"Celui qui marche dans l’intégrité marche avec assurance, mais celui qui prend des voies tortueuses sera découvert."},
15:{r:"Proverbs 16:9",r_es:"Proverbios 16:9",r_fr:"Proverbes 16:9",
  t:"The heart of man plans his way, but the Lord establishes his steps.",
  t_es:"El corazón del hombre piensa su camino; mas Jehová endereza sus pasos.",
  t_fr:"Le cœur de l’homme médite sa voie, mais c’est l’Éternel qui dirige ses pas."},
22:{r:"Proverbs 21:31",r_es:"Proverbios 21:31",r_fr:"Proverbes 21:31",
  t:"The horse is made ready for the day of battle, but the victory belongs to the Lord.",
  t_es:"El caballo se alista para el día de la batalla; mas Jehová es el que da la victoria.",
  t_fr:"Le cheval est équipé pour le jour de la bataille, mais la délivrance appartient à l’Éternel."}
},
  checks: [
  {k:"read",l:"Read the passage",l_es:"Lee el pasaje",l_fr:"Lis le passage"},
  {k:"pray",l:"Pray & journal",l_es:"Ora y escribe en tu diario",l_fr:"Prie et tiens un journal"},
  {k:"workout",l:"Lift weights (3–5x/week)",l_es:"Levanta pesas (3–5x por semana)",l_fr:"Soulève des poids (3–5x par semaine)"},
  {k:"cardio",l:"Cardio session (1x/week)",l_es:"Sesión de cardio (1x por semana)",l_fr:"Séance de cardio (1x par semaine)"},
  {k:"danger",l:"Stay Dangerous (1x/phase)",l_es:"Mantente peligroso (1x por fase)",l_fr:"Reste dangereux (1x par phase)"},
  {k:"abstain",l:"Abstain from your one thing",l_es:"Abstente de aquello que decidiste",l_fr:"Abstiens-toi de la chose que tu as choisie"},
  {k:"christ",l:"Christ-centered activity at home",l_es:"Actividad centrada en Cristo en casa",l_fr:"Activité centrée sur Christ à la maison"},
  {k:"marco",l:"Marco Polo update",l_es:"Mensaje en Marco Polo",l_fr:"Mise à jour Marco Polo"}
]
};
