// Iron Sharpens Iron v2.2.0 — Gospel of John Config (en/es/fr)
window.PLAN = {
  title: "Gospel of John",
  title_es: "Evangelio de Juan",
  title_fr: "Évangile de Jean",
  subtitle: "GOSPEL OF JOHN — 30-DAY CHALLENGE",
  subtitle_es: "EVANGELIO DE JUAN — RETO DE 30 DÍAS",
  subtitle_fr: "ÉVANGILE DE JEAN — DÉFI DE 30 JOURS",
  storageKey: "isi-john-v2",
  totalDays: 30,
  days: [
{day:1,reading:"John 1",topic:"The Word Became Flesh",topic_es:"El Verbo se hizo carne",topic_fr:"La Parole s’est faite chair",ph:1,
  summary:"In the beginning was the Word. John the Baptist testifies. Jesus calls His first disciples — Andrew, Peter, Philip, and Nathanael. ‘We have found the Messiah.’",
  summary_es:"En el principio era el Verbo. Juan el Bautista da testimonio. Jesús llama a sus primeros discípulos — Andrés, Pedro, Felipe y Natanael. ‘Hemos hallado al Mesías.’",
  summary_fr:"Au commencement était la Parole. Jean-Baptiste rend témoignage. Jésus appelle ses premiers disciples — André, Pierre, Philippe et Nathanaël. ‘Nous avons trouvé le Messie.’"},
{day:2,reading:"John 2",topic:"Water to Wine & Temple Cleansing",topic_es:"Agua en vino y purificación del templo",topic_fr:"L’eau changée en vin et la purification du temple",
  summary:"Jesus turns water into wine at Cana — His first sign. He drives out the money changers: ‘Destroy this temple, and in three days I will raise it up.’",
  summary_es:"Jesús convierte el agua en vino en Caná — su primera señal. Echa a los cambistas: ‘Destruid este templo, y en tres días lo levantaré.’",
  summary_fr:"Jésus change l’eau en vin à Cana — son premier signe. Il chasse les changeurs : ‘Détruisez ce temple, et en trois jours je le relèverai.’"},
{day:3,reading:"John 3",topic:"You Must Be Born Again",topic_es:"Es necesario nacer de nuevo",topic_fr:"Il faut naître de nouveau",
  summary:"Jesus tells Nicodemus about the new birth. ‘For God so loved the world, that He gave His only Son.’ John the Baptist: ‘He must increase, I must decrease.’",
  summary_es:"Jesús habla a Nicodemo del nuevo nacimiento. ‘De tal manera amó Dios al mundo, que ha dado a su Hijo unigénito.’ Juan el Bautista: ‘Es necesario que él crezca, y que yo mengüe.’",
  summary_fr:"Jésus parle à Nicodème de la nouvelle naissance. ‘Dieu a tant aimé le monde qu’il a donné son Fils unique.’ Jean-Baptiste : ‘Il faut qu’il croisse, et que je diminue.’"},
{day:4,reading:"John 4",topic:"The Woman at the Well",topic_es:"La mujer junto al pozo",topic_fr:"La femme au puits",
  summary:"Jesus crosses cultural barriers to offer living water to the Samaritan woman. ‘God is spirit, and those who worship Him must worship in spirit and truth.’",
  summary_es:"Jesús cruza las barreras culturales y ofrece agua viva a la samaritana. ‘Dios es espíritu; y los que le adoran, en espíritu y en verdad es necesario que adoren.’",
  summary_fr:"Jésus franchit les barrières culturelles pour offrir l’eau vive à la Samaritaine. ‘Dieu est Esprit, et il faut que ceux qui l’adorent l’adorent en esprit et en vérité.’"},
{day:5,reading:"John 5",topic:"Healing at the Pool & the Son’s Authority",topic_es:"Sanidad en el estanque y la autoridad del Hijo",topic_fr:"Guérison à la piscine et l’autorité du Fils",
  summary:"Jesus heals the man at Bethesda on the Sabbath and claims equality with the Father. ‘The Son gives life to whom He will.’ The religious leaders seek to kill Him.",
  summary_es:"Jesús sana al hombre en Betesda en sábado y afirma su igualdad con el Padre. ‘El Hijo da vida a los que él quiere.’ Los líderes religiosos buscan matarlo.",
  summary_fr:"Jésus guérit l’homme à Béthesda un jour de sabbat et se déclare égal au Père. ‘Le Fils donne la vie à qui il veut.’ Les chefs religieux cherchent à le tuer."},
{day:6,reading:"John 1–5",topic:"Phase 1 Re-Read (Part 1)",topic_es:"Relectura de la Fase 1 (parte 1)",topic_fr:"Relecture de la phase 1 (partie 1)",
  summary:"Re-read the first five chapters. Watch the themes emerge: the Word made flesh, new birth, living water, and the authority of the Son. Let it sink deeper.",
  summary_es:"Relee los cinco primeros capítulos. Observa cómo emergen los temas: el Verbo hecho carne, el nuevo nacimiento, el agua viva y la autoridad del Hijo. Que cale más hondo.",
  summary_fr:"Relis les cinq premiers chapitres. Vois les thèmes émerger : la Parole faite chair, la nouvelle naissance, l’eau vive et l’autorité du Fils. Laisse cela descendre plus profondément."},
{day:7,reading:"John 1–5",topic:"Phase 1 Re-Read (Part 2)",topic_es:"Relectura de la Fase 1 (parte 2)",topic_fr:"Relecture de la phase 1 (partie 2)",
  summary:"Second pass through John 1–5. What did you miss the first time? What is the Spirit highlighting? Journal what stands out.",
  summary_es:"Segunda lectura de Juan 1–5. ¿Qué se te pasó la primera vez? ¿Qué destaca el Espíritu? Anota lo que resalte.",
  summary_fr:"Deuxième passage dans Jean 1–5. Qu’as-tu manqué la première fois ? Que met en lumière l’Esprit ? Note ce qui ressort."},
{day:8,reading:"John 6",topic:"Bread of Life",topic_es:"El Pan de Vida",topic_fr:"Le Pain de Vie",ph:2,
  summary:"Jesus feeds the 5,000, walks on water, and declares: ‘I am the bread of life. Whoever comes to me shall not hunger.’ Many disciples turn back. Peter stays.",
  summary_es:"Jesús alimenta a los 5.000, camina sobre el agua y declara: ‘Yo soy el pan de vida; el que a mí viene, nunca tendrá hambre.’ Muchos discípulos se vuelven atrás. Pedro se queda.",
  summary_fr:"Jésus nourrit les 5 000, marche sur l’eau et déclare : ‘Je suis le pain de vie. Celui qui vient à moi n’aura jamais faim.’ Beaucoup de disciples s’en retournent. Pierre reste."},
{day:9,reading:"John 7",topic:"Division Over Jesus",topic_es:"División por causa de Jesús",topic_fr:"Division au sujet de Jésus",
  summary:"Jesus goes to the Feast of Tabernacles. The crowds are divided — some say He is the Prophet, others say the Christ. ‘If anyone thirsts, let him come to me and drink.’",
  summary_es:"Jesús sube a la fiesta de los Tabernáculos. La multitud está dividida — unos dicen que es el Profeta, otros que el Cristo. ‘Si alguno tiene sed, venga a mí y beba.’",
  summary_fr:"Jésus monte à la fête des Tabernacles. La foule est divisée — certains disent qu’il est le Prophète, d’autres le Christ. ‘Si quelqu’un a soif, qu’il vienne à moi, et qu’il boive.’"},
{day:10,reading:"John 8",topic:"The Light of the World",topic_es:"La Luz del mundo",topic_fr:"La Lumière du monde",
  summary:"The woman caught in adultery. ‘I am the light of the world.’ Jesus confronts the Pharisees: ‘Before Abraham was, I AM.’ They pick up stones.",
  summary_es:"La mujer sorprendida en adulterio. ‘Yo soy la luz del mundo.’ Jesús confronta a los fariseos: ‘Antes que Abraham fuese, YO SOY.’ Toman piedras.",
  summary_fr:"La femme prise en adultère. ‘Je suis la lumière du monde.’ Jésus confronte les pharisiens : ‘Avant qu’Abraham fût, JE SUIS.’ Ils prennent des pierres."},
{day:11,reading:"John 9",topic:"Healing the Man Born Blind",topic_es:"Sanidad del ciego de nacimiento",topic_fr:"Guérison de l’aveugle-né",
  summary:"Jesus heals a man blind from birth. The Pharisees interrogate him. ‘One thing I do know: I was blind, but now I see.’ Jesus reveals Himself as the Son of Man.",
  summary_es:"Jesús sana a un hombre ciego de nacimiento. Los fariseos lo interrogan. ‘Una cosa sé: que habiendo yo sido ciego, ahora veo.’ Jesús se revela como el Hijo del Hombre.",
  summary_fr:"Jésus guérit un homme aveugle de naissance. Les pharisiens l’interrogent. ‘Je sais une chose : c’est que j’étais aveugle, et maintenant je vois.’ Jésus se révèle comme le Fils de l’homme."},
{day:12,reading:"John 10",topic:"The Good Shepherd",topic_es:"El Buen Pastor",topic_fr:"Le Bon Berger",
  summary:"‘I am the good shepherd. The good shepherd lays down his life for the sheep.’ Jesus claims oneness with the Father. ‘I give them eternal life, and they will never perish.’",
  summary_es:"‘Yo soy el buen pastor; el buen pastor su vida da por las ovejas.’ Jesús afirma su unidad con el Padre. ‘Yo les doy vida eterna; y no perecerán jamás.’",
  summary_fr:"‘Je suis le bon berger. Le bon berger donne sa vie pour ses brebis.’ Jésus affirme son unité avec le Père. ‘Je leur donne la vie éternelle ; et elles ne périront jamais.’"},
{day:13,reading:"John 6–10",topic:"Phase 2 Re-Read (Part 1)",topic_es:"Relectura de la Fase 2 (parte 1)",topic_fr:"Relecture de la phase 2 (partie 1)",
  summary:"Re-read John 6–10. The ‘I AM’ statements are building. Bread of life, light of the world, the good shepherd. Who is Jesus claiming to be?",
  summary_es:"Relee Juan 6–10. Las declaraciones ‘YO SOY’ se acumulan. Pan de vida, luz del mundo, buen pastor. ¿Quién dice Jesús que es?",
  summary_fr:"Relis Jean 6–10. Les déclarations ‘JE SUIS’ s’accumulent. Pain de vie, lumière du monde, bon berger. Qui Jésus prétend-il être ?"},
{day:14,reading:"John 6–10",topic:"Phase 2 Re-Read (Part 2)",topic_es:"Relectura de la Fase 2 (parte 2)",topic_fr:"Relecture de la phase 2 (partie 2)",
  summary:"Second pass through John 6–10. Pay attention to the responses — belief, division, hostility. How do people respond to Jesus today?",
  summary_es:"Segunda lectura de Juan 6–10. Fíjate en las respuestas — fe, división, hostilidad. ¿Cómo responde la gente a Jesús hoy?",
  summary_fr:"Deuxième passage dans Jean 6–10. Observe les réponses — la foi, la division, l’hostilité. Comment les gens répondent-ils à Jésus aujourd’hui ?"},
{day:15,reading:"John 11",topic:"The Resurrection and the Life",topic_es:"La Resurrección y la Vida",topic_fr:"La Résurrection et la Vie",ph:3,
  summary:"Lazarus dies. Jesus weeps. Then He calls Lazarus out of the tomb. ‘I am the resurrection and the life. Whoever believes in me, though he die, yet shall he live.’",
  summary_es:"Lázaro muere. Jesús llora. Luego llama a Lázaro fuera del sepulcro. ‘Yo soy la resurrección y la vida; el que cree en mí, aunque esté muerto, vivirá.’",
  summary_fr:"Lazare meurt. Jésus pleure. Puis il appelle Lazare hors du tombeau. ‘Je suis la résurrection et la vie. Celui qui croit en moi vivra, quand même il serait mort.’"},
{day:16,reading:"John 12",topic:"The Triumphal Entry",topic_es:"La Entrada Triunfal",topic_fr:"L’entrée triomphale",
  summary:"Mary anoints Jesus’ feet. The crowd shouts Hosanna as He enters Jerusalem on a donkey. ‘Unless a grain of wheat falls into the earth and dies, it remains alone.’",
  summary_es:"María unge los pies de Jesús. La multitud grita Hosanna cuando entra en Jerusalén sobre un asno. ‘Si el grano de trigo no cae en la tierra y muere, queda solo.’",
  summary_fr:"Marie oint les pieds de Jésus. La foule crie Hosanna quand il entre à Jérusalem sur un âne. ‘Si le grain de blé qui est tombé en terre ne meurt, il reste seul.’"},
{day:17,reading:"John 13",topic:"The Last Supper & Foot Washing",topic_es:"La Última Cena y el lavamiento de los pies",topic_fr:"La Cène et le lavement des pieds",
  summary:"Jesus washes the disciples’ feet — the King becomes the servant. ‘A new commandment I give to you: love one another as I have loved you.’ Judas departs into the night.",
  summary_es:"Jesús lava los pies de los discípulos — el Rey se hace siervo. ‘Un mandamiento nuevo os doy: que os améis unos a otros, como yo os he amado.’ Judas sale a la noche.",
  summary_fr:"Jésus lave les pieds de ses disciples — le Roi devient serviteur. ‘Je vous donne un commandement nouveau : aimez-vous les uns les autres, comme je vous ai aimés.’ Judas sort dans la nuit."},
{day:18,reading:"John 14",topic:"The Way, the Truth, the Life",topic_es:"El Camino, la Verdad y la Vida",topic_fr:"Le Chemin, la Vérité et la Vie",
  summary:"‘I am the way, the truth, and the life. No one comes to the Father except through me.’ Jesus promises the Holy Spirit — the Helper who will be with them forever.",
  summary_es:"‘Yo soy el camino, y la verdad, y la vida; nadie viene al Padre, sino por mí.’ Jesús promete el Espíritu Santo — el Consolador que estará con ellos para siempre.",
  summary_fr:"‘Je suis le chemin, la vérité et la vie. Nul ne vient au Père que par moi.’ Jésus promet le Saint-Esprit — le Consolateur qui sera avec eux pour toujours."},
{day:19,reading:"John 15",topic:"The Vine and the Branches",topic_es:"La Vid y los pámpanos",topic_fr:"Le Cep et les sarments",
  summary:"‘I am the vine; you are the branches.’ Abide in Him and bear fruit. ‘Greater love has no one than this: that someone lay down his life for his friends.’",
  summary_es:"‘Yo soy la vid, vosotros los pámpanos.’ Permaneced en él y llevad fruto. ‘Nadie tiene mayor amor que este, que uno ponga su vida por sus amigos.’",
  summary_fr:"‘Je suis le cep, vous êtes les sarments.’ Demeurez en lui et portez du fruit. ‘Il n’y a pas de plus grand amour que de donner sa vie pour ses amis.’"},
{day:20,reading:"John 11–15",topic:"Phase 3 Re-Read (Part 1)",topic_es:"Relectura de la Fase 3 (parte 1)",topic_fr:"Relecture de la phase 3 (partie 1)",
  summary:"Re-read John 11–15. The upper room discourse. Jesus prepares His disciples for what’s coming — His death, the Spirit, and the command to love.",
  summary_es:"Relee Juan 11–15. El discurso del aposento alto. Jesús prepara a sus discípulos para lo que viene — su muerte, el Espíritu y el mandamiento de amar.",
  summary_fr:"Relis Jean 11–15. Le discours de la chambre haute. Jésus prépare ses disciples à ce qui vient — sa mort, l’Esprit et le commandement d’aimer."},
{day:21,reading:"John 11–15",topic:"Phase 3 Re-Read (Part 2)",topic_es:"Relectura de la Fase 3 (parte 2)",topic_fr:"Relecture de la phase 3 (partie 2)",
  summary:"Second pass through John 11–15. The vine, the foot washing, the promise of the Helper. What is Jesus asking of you in this season?",
  summary_es:"Segunda lectura de Juan 11–15. La vid, el lavamiento de los pies, la promesa del Consolador. ¿Qué te pide Jesús en este tiempo?",
  summary_fr:"Deuxième passage dans Jean 11–15. Le cep, le lavement des pieds, la promesse du Consolateur. Que te demande Jésus en cette saison ?"},
{day:22,reading:"John 16",topic:"The Spirit of Truth",topic_es:"El Espíritu de verdad",topic_fr:"L’Esprit de vérité",ph:4,
  summary:"Jesus warns of persecution and promises the Spirit will guide them into all truth. ‘In the world you will have tribulation. But take heart; I have overcome the world.’",
  summary_es:"Jesús advierte de la persecución y promete que el Espíritu los guiará a toda verdad. ‘En el mundo tendréis aflicción; pero confiad, yo he vencido al mundo.’",
  summary_fr:"Jésus prévient de la persécution et promet que l’Esprit les conduira dans toute la vérité. ‘Vous aurez des tribulations dans le monde ; mais prenez courage, j’ai vaincu le monde.’"},
{day:23,reading:"John 17",topic:"Jesus’ High Priestly Prayer",topic_es:"La oración sumo sacerdotal de Jesús",topic_fr:"La prière sacerdotale de Jésus",
  summary:"Jesus prays for Himself, His disciples, and all who will believe. ‘Sanctify them in the truth; your word is truth.’ He prays for their unity and protection.",
  summary_es:"Jesús ora por sí mismo, por sus discípulos y por todos los que creerán. ‘Santifícalos en tu verdad; tu palabra es verdad.’ Pide por su unidad y protección.",
  summary_fr:"Jésus prie pour lui-même, pour ses disciples et pour tous ceux qui croiront. ‘Sanctifie-les par ta vérité : ta parole est la vérité.’ Il prie pour leur unité et leur protection."},
{day:24,reading:"John 18",topic:"Betrayal and Arrest",topic_es:"Traición y arresto",topic_fr:"Trahison et arrestation",
  summary:"Judas betrays Jesus in the garden. Peter draws his sword, then denies Jesus three times. Jesus stands before Pilate: ‘My kingdom is not of this world.’",
  summary_es:"Judas traiciona a Jesús en el huerto. Pedro saca la espada y luego niega a Jesús tres veces. Jesús comparece ante Pilato: ‘Mi reino no es de este mundo.’",
  summary_fr:"Judas trahit Jésus au jardin. Pierre tire l’épée, puis renie Jésus trois fois. Jésus comparaît devant Pilate : ‘Mon royaume n’est pas de ce monde.’"},
{day:25,reading:"John 19",topic:"The Crucifixion",topic_es:"La Crucifixión",topic_fr:"La Crucifixion",
  summary:"Jesus is scourged, crowned with thorns, and crucified. ‘It is finished.’ The Lamb of God takes away the sin of the world. Joseph and Nicodemus bury Him.",
  summary_es:"Jesús es azotado, coronado de espinas y crucificado. ‘Consumado es.’ El Cordero de Dios quita el pecado del mundo. José y Nicodemo lo sepultan.",
  summary_fr:"Jésus est flagellé, couronné d’épines et crucifié. ‘Tout est accompli.’ L’Agneau de Dieu ôte le péché du monde. Joseph et Nicodème l’ensevelissent."},
{day:26,reading:"John 20",topic:"The Resurrection",topic_es:"La Resurrección",topic_fr:"La Résurrection",
  summary:"The empty tomb. Mary sees the risen Lord. Jesus appears to the disciples and to Thomas. ‘My Lord and my God!’ ‘Blessed are those who have not seen and yet have believed.’",
  summary_es:"La tumba vacía. María ve al Señor resucitado. Jesús se aparece a los discípulos y a Tomás. ‘¡Señor mío, y Dios mío!’ ‘Bienaventurados los que no vieron, y creyeron.’",
  summary_fr:"Le tombeau vide. Marie voit le Seigneur ressuscité. Jésus apparaît aux disciples et à Thomas. ‘Mon Seigneur et mon Dieu !’ ‘Heureux ceux qui n’ont pas vu, et qui ont cru !’"},
{day:27,reading:"John 21",topic:"Restoration of Peter",topic_es:"La restauración de Pedro",topic_fr:"La restauration de Pierre",
  summary:"Jesus appears at the Sea of Galilee. The miraculous catch. Three times He asks Peter: ‘Do you love me?’ Three times: ‘Feed my sheep.’ Peter is restored.",
  summary_es:"Jesús se aparece junto al mar de Galilea. La pesca milagrosa. Tres veces pregunta a Pedro: ‘¿Me amas?’ Tres veces: ‘Apacienta mis ovejas.’ Pedro es restaurado.",
  summary_fr:"Jésus apparaît au bord de la mer de Galilée. La pêche miraculeuse. Trois fois il demande à Pierre : ‘M’aimes-tu ?’ Trois fois : ‘Pais mes brebis.’ Pierre est restauré."},
{day:28,reading:"John 16–21",topic:"Phase 4 Re-Read (Part 1)",topic_es:"Relectura de la Fase 4 (parte 1)",topic_fr:"Relecture de la phase 4 (partie 1)",
  summary:"Re-read John 16–21. The prayer, the cross, the empty tomb, the restoration. The whole gospel in six chapters.",
  summary_es:"Relee Juan 16–21. La oración, la cruz, la tumba vacía, la restauración. Todo el evangelio en seis capítulos.",
  summary_fr:"Relis Jean 16–21. La prière, la croix, le tombeau vide, la restauration. Tout l’évangile en six chapitres."},
{day:29,reading:"John 16–21",topic:"Phase 4 Re-Read (Part 2)",topic_es:"Relectura de la Fase 4 (parte 2)",topic_fr:"Relecture de la phase 4 (partie 2)",
  summary:"Second pass through John 16–21. Sit with the cross. Sit with the resurrection. What has changed in you over these 30 days?",
  summary_es:"Segunda lectura de Juan 16–21. Detente en la cruz. Detente en la resurrección. ¿Qué ha cambiado en ti en estos 30 días?",
  summary_fr:"Deuxième passage dans Jean 16–21. Assieds-toi devant la croix. Assieds-toi devant la résurrection. Qu’a-t-il changé en toi en ces 30 jours ?"},
{day:30,reading:"John 1–21",topic:"Full Book Re-Read",topic_es:"Relectura completa del libro",topic_fr:"Relecture intégrale du livre",
  summary:"Read the entire Gospel of John in one sitting. From ‘In the beginning was the Word’ to ‘Feed my sheep.’ You’ve lived in this book for a month. Now see the whole picture.",
  summary_es:"Lee todo el Evangelio de Juan de una sola vez. Desde ‘En el principio era el Verbo’ hasta ‘Apacienta mis ovejas.’ Has vivido en este libro un mes. Ahora ve el cuadro completo.",
  summary_fr:"Lis tout l’Évangile de Jean d’une traite. De ‘Au commencement était la Parole’ jusqu’à ‘Pais mes brebis.’ Tu as vécu un mois dans ce livre. Vois maintenant la vision d’ensemble."}
],
  verses: {
1:{r:"2 Corinthians 5:21",r_es:"2 Corintios 5:21",r_fr:"2 Corinthiens 5:21",
  t:"For our sake he made him to be sin who knew no sin, so that in him we might become the righteousness of God.",
  t_es:"Al que no conoció pecado, por nosotros lo hizo pecado, para que nosotros fuésemos hechos justicia de Dios en él.",
  t_fr:"Celui qui n’a point connu le péché, il l’a fait devenir péché pour nous, afin que nous devenions en lui justice de Dieu."},
8:{r:"1 Corinthians 9:27",r_es:"1 Corintios 9:27",r_fr:"1 Corinthiens 9:27",
  t:"But I discipline my body and keep it under control, lest after preaching to others I myself should be disqualified.",
  t_es:"Sino que golpeo mi cuerpo, y lo pongo en servidumbre, no sea que habiendo sido heraldo para otros, yo mismo venga a ser eliminado.",
  t_fr:"Mais je traite durement mon corps et je le tiens assujetti, de peur d’être moi-même rejeté, après avoir prêché aux autres."},
15:{r:"1 Peter 5:8",r_es:"1 Pedro 5:8",r_fr:"1 Pierre 5:8",
  t:"Be sober-minded; be watchful. Your adversary the devil prowls around like a roaring lion, seeking someone to devour.",
  t_es:"Sed sobrios, y velad; porque vuestro adversario el diablo, como león rugiente, anda alrededor buscando a quien devorar.",
  t_fr:"Soyez sobres, veillez. Votre adversaire, le diable, rôde comme un lion rugissant, cherchant qui il dévorera."},
22:{r:"2 Timothy 1:7",r_es:"2 Timoteo 1:7",r_fr:"2 Timothée 1:7",
  t:"For God gave us a spirit not of fear but of power and love and self-control.",
  t_es:"Porque no nos ha dado Dios espíritu de cobardía, sino de poder, de amor y de dominio propio.",
  t_fr:"Car ce n’est pas un esprit de timidité que Dieu nous a donné, mais un esprit de force, d’amour et de sagesse."}
},
  checks: [
  {k:"read",l:"Read the passage",l_es:"Lee el pasaje",l_fr:"Lis le passage"},
  {k:"pray",l:"Pray & journal",l_es:"Ora y escribe en tu diario",l_fr:"Prie et tiens un journal"},
  {k:"workout",l:"Lift weights (3–5x/week)",l_es:"Levanta pesas (3–5x por semana)",l_fr:"Soulève des poids (3–5x par semaine)"},
  {k:"cardio",l:"Cardio session (1x/week)",l_es:"Sesión de cardio (1x por semana)",l_fr:"Séance de cardio (1x par semaine)"},
  {k:"danger",l:"Stay Dangerous (1x/phase)",l_es:"Mantente peligroso (1x por fase)",l_fr:"Reste dangereux (1x par phase)"},
  {k:"abstain",l:"Abstain from your one thing",l_es:"Abstente de aquello que decidiste",l_fr:"Abstiens-toi de la chose que tu as choisie"},
  {k:"christ",l:"Christ-centered activity at home",l_es:"Actividad centrada en Cristo en casa",l_fr:"Activité centrée sur Christ à la maison"},
  {k:"marco",l:"Marco Polo update",l_es:"Mensaje en Marco Polo",l_fr:"Mise à jour Marco Polo"}
]
};
